//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Replacement element containing Competency Qualifications for the Job Profile
 * When updating a Job Profile, all Competencies for the Job Profile will be replaced by the submitted data. If no data is submitted, then the existing Competencies are not changed.
 * 
 * <p>Java class for Competency_Qualification_Profile_Replacement_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Competency_Qualification_Profile_Replacement_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Competency_Reference" type="{urn:com.workday/bsvc}CompetencyObjectType"/&gt;
 *         &lt;element name="Proficiency_Rating_Reference" type="{urn:com.workday/bsvc}Proficiency_RatingObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Required" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Competency_Qualification_Profile_Replacement_DataType", propOrder = {
    "competencyReference",
    "proficiencyRatingReference",
    "required"
})
public class CompetencyQualificationProfileReplacementDataType {

    @XmlElement(name = "Competency_Reference", required = true)
    protected CompetencyObjectType competencyReference;
    @XmlElement(name = "Proficiency_Rating_Reference")
    protected ProficiencyRatingObjectType proficiencyRatingReference;
    @XmlElement(name = "Required")
    protected Boolean required;

    /**
     * Gets the value of the competencyReference property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyObjectType }
     *     
     */
    public CompetencyObjectType getCompetencyReference() {
        return competencyReference;
    }

    /**
     * Sets the value of the competencyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyObjectType }
     *     
     */
    public void setCompetencyReference(CompetencyObjectType value) {
        this.competencyReference = value;
    }

    /**
     * Gets the value of the proficiencyRatingReference property.
     * 
     * @return
     *     possible object is
     *     {@link ProficiencyRatingObjectType }
     *     
     */
    public ProficiencyRatingObjectType getProficiencyRatingReference() {
        return proficiencyRatingReference;
    }

    /**
     * Sets the value of the proficiencyRatingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProficiencyRatingObjectType }
     *     
     */
    public void setProficiencyRatingReference(ProficiencyRatingObjectType value) {
        this.proficiencyRatingReference = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

}
