//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Encapsulating element containing all Period Salary Plan Compensation data.
 * 
 * <p>Java class for Proposed_Period_Salary_Plan_Assignment_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Proposed_Period_Salary_Plan_Assignment_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Period_Salary_Plan_Reference" type="{urn:com.workday/bsvc}Period_Salary_PlanObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Compensation_Period_Reference" type="{urn:com.workday/bsvc}Compensation_PeriodObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Manage_by_Compensation_Basis_Override_Amount" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="26"/&gt;
 *               &lt;fractionDigits value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Currency_Reference" type="{urn:com.workday/bsvc}CurrencyObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Compensation_Period_Multiplier" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="18"/&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;fractionDigits value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Frequency_Reference" type="{urn:com.workday/bsvc}FrequencyObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Actual_End_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Proposed_Period_Salary_Plan_Assignment_DataType", propOrder = {
    "periodSalaryPlanReference",
    "compensationPeriodReference",
    "manageByCompensationBasisOverrideAmount",
    "currencyReference",
    "compensationPeriodMultiplier",
    "frequencyReference",
    "actualEndDate"
})
public class ProposedPeriodSalaryPlanAssignmentDataType {

    @XmlElement(name = "Period_Salary_Plan_Reference")
    protected PeriodSalaryPlanObjectType periodSalaryPlanReference;
    @XmlElement(name = "Compensation_Period_Reference")
    protected CompensationPeriodObjectType compensationPeriodReference;
    @XmlElement(name = "Manage_by_Compensation_Basis_Override_Amount")
    protected BigDecimal manageByCompensationBasisOverrideAmount;
    @XmlElement(name = "Currency_Reference")
    protected CurrencyObjectType currencyReference;
    @XmlElement(name = "Compensation_Period_Multiplier")
    protected BigDecimal compensationPeriodMultiplier;
    @XmlElement(name = "Frequency_Reference")
    protected FrequencyObjectType frequencyReference;
    @XmlElement(name = "Actual_End_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar actualEndDate;

    /**
     * Gets the value of the periodSalaryPlanReference property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodSalaryPlanObjectType }
     *     
     */
    public PeriodSalaryPlanObjectType getPeriodSalaryPlanReference() {
        return periodSalaryPlanReference;
    }

    /**
     * Sets the value of the periodSalaryPlanReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodSalaryPlanObjectType }
     *     
     */
    public void setPeriodSalaryPlanReference(PeriodSalaryPlanObjectType value) {
        this.periodSalaryPlanReference = value;
    }

    /**
     * Gets the value of the compensationPeriodReference property.
     * 
     * @return
     *     possible object is
     *     {@link CompensationPeriodObjectType }
     *     
     */
    public CompensationPeriodObjectType getCompensationPeriodReference() {
        return compensationPeriodReference;
    }

    /**
     * Sets the value of the compensationPeriodReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensationPeriodObjectType }
     *     
     */
    public void setCompensationPeriodReference(CompensationPeriodObjectType value) {
        this.compensationPeriodReference = value;
    }

    /**
     * Gets the value of the manageByCompensationBasisOverrideAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getManageByCompensationBasisOverrideAmount() {
        return manageByCompensationBasisOverrideAmount;
    }

    /**
     * Sets the value of the manageByCompensationBasisOverrideAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setManageByCompensationBasisOverrideAmount(BigDecimal value) {
        this.manageByCompensationBasisOverrideAmount = value;
    }

    /**
     * Gets the value of the currencyReference property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyObjectType }
     *     
     */
    public CurrencyObjectType getCurrencyReference() {
        return currencyReference;
    }

    /**
     * Sets the value of the currencyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyObjectType }
     *     
     */
    public void setCurrencyReference(CurrencyObjectType value) {
        this.currencyReference = value;
    }

    /**
     * Gets the value of the compensationPeriodMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCompensationPeriodMultiplier() {
        return compensationPeriodMultiplier;
    }

    /**
     * Sets the value of the compensationPeriodMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCompensationPeriodMultiplier(BigDecimal value) {
        this.compensationPeriodMultiplier = value;
    }

    /**
     * Gets the value of the frequencyReference property.
     * 
     * @return
     *     possible object is
     *     {@link FrequencyObjectType }
     *     
     */
    public FrequencyObjectType getFrequencyReference() {
        return frequencyReference;
    }

    /**
     * Sets the value of the frequencyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrequencyObjectType }
     *     
     */
    public void setFrequencyReference(FrequencyObjectType value) {
        this.frequencyReference = value;
    }

    /**
     * Gets the value of the actualEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualEndDate() {
        return actualEndDate;
    }

    /**
     * Sets the value of the actualEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualEndDate(XMLGregorianCalendar value) {
        this.actualEndDate = value;
    }

}
