package com.polus.fibicomp.constants;

import java.math.BigDecimal;

public interface Constants {


    // Security constants
    String SECRET = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJt6Aa8aOs06KyiBZ3pwiKdfgmdbosVuNPpxO9hUd6gsKk3lxTx+pBpkaONP/WHWkv5g/GvgOt9R+aItSxf3LEcCAwEAAQ==";
    long EXPIRATION_TIME = 43_200_000; // 12 hour
    String TOKEN_PREFIX = "Bearer ";
    String HEADER_STRING = "Authorization";
    String SIGN_UP_URL = "/fibi-comp/login";
    String EXTERNAL_AUTHORIZATION = "EXTERNALAUTH";
    String TRUE = "Y";
    Integer UNAUTHORIZED = 401;
    String LOGIN_PERSON_ID = "personId";
    String LOGIN_PERSON_UNIT = "unitNumber";
    String LOGIN_USER_FULL_NAME = "fullName";
    String IS_EXTERNAL_USER = "isExternalUser";

    // Grant Call


    // Module Code
    Integer AWARD_MODULE_CODE = 1;
    Integer DEV_PROPOSAL_MODULE_CODE = 3;

    String YES = "Y";
    String NO = "N";

    String JAVA_ERROR = "ERR";
    String DB_PROC_ERROR = "ERRP";
    String DB_FN_ERROR = "ERRF";
	String PROPOSAL_DISCLOSURE = "2";
    String AWARD_DISCLOSURE = "3";
	String DISCLOSURE_SEQUENCE_STATUS_PENDING = "1";
	String DISCLOSURE_SEQUENCE_STATUS_ACTIVE = "2";
	String DISCLOSURE_STATUS_PENDING = "1";
    /** COI */
    Integer COI_MODULE_CODE = 8;
    Integer COI_SUBMODULE_CODE = 0;
    Integer COI_SFI_SUBMODULE_CODE = 801;

    String COI_ACTIVE_STATUS = "ACTIVE";
    String COI_ARCHIVE_STATUS = "ARCHIVE";
    Integer COI_INITIAL_VERSION_NUMBER = 1;
    String COI_PENDING_STATUS = "PENDING";
    String COI_INACTIVE_STATUS = "INACTIVE";



    String TYPE_SYNC_FCOI_ON_CREATE = "F";
    String TYPE_SYNC_PROJECT_DISCLOSURE_ON_CREATE = "P";
    String TYPE_SYNC_SFI_WITH_DISCLOSURE_PROJECTS = "SD";
    
    String TRAVEL_STATUS_CODE = "1";
    String TRAVEL_DOCUMENT_STATUS_CODE_DRAFT = "1";
    String TRAVEL_DOCUMENT_STATUS_CODE_APPROVED = "2";
    String TRAVEL_DISCLOSURE_STATUS_CODE = "1";

    String TRAVEL_REVIEW_STATUS_CODE_PENDING = "1";
    String TRAVEL_REVIEW_STATUS_CODE_SUBMITTED = "2";
    String TRAVEL_REVIEW_STATUS_CODE_INPROGRESS = "3";
    String TRAVEL_REVIEW_STATUS_CODE_RETURNED_TO_PI = "4";
    String TRAVEL_REVIEW_STATUS_CODE_WITHDRAWN = "5";
    String TRAVEL_REVIEW_STATUS_CODE_COMPLETED = "6";
    String TRAVEL_REVIEW_STATUS_CODE_APPROVED = "7";
    String TRAVEL_VERSION_STATUS_CODE = "1";
    String TRAVEL_VERSION_STATUS_PENDING = "PENDING";
    String TRAVE_VERSION_STATUS_ACTIVE = "ACTIVE";
    Integer DEFAULT_TRAVEL_VERSION_NUMBER = 1;
    String COI_ENTITY_STATUS_VERIFIED = "1";

    String COI_ENTITY_CREATE_ACTION_LOG_CODE = "1";
    String COI_ENTITY_ACTIVATE_ACTION_LOG_CODE = "2";
    String COI_ENTITY_INACTIVATE_ACTION_LOG_CODE = "3";
    String COI_ENTITY_VERIFY_ACTION_LOG_CODE = "4";
    String COI_ENTITY_MODIFY_RISK_ACTION_LOG_CODE = "5";
    String COI_ENTITY_MODIFY_ACTION_LOG_CODE = "6";
    String COI_ENTITY_RISK_ADD_ACTION_LOG_CODE = "7";

    String COI_DISCLOSURE_ACTION_LOG_CREATED = "1";
    String COI_DISCLOSURE_ACTION_LOG_REVISED = "28";
    String COI_DISCLOSURE_ACTION_LOG_SUBMITTED = "2";
    String COI_DISCLOSURE_ACTION_LOG_WITHDRAWN = "3";
    String COI_DISCLOSURE_ACTION_LOG_ASSIGN_ADMIN = "4";
    String COI_DISCLOSURE_ACTION_LOG_REASSIGN_ADMIN = "5";
    String COI_DISCLOSURE_ACTION_LOG_RETURNED = "6";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_REVIEW_COMPLETED = "11";
    String COI_DISCLOSURE_ACTION_LOG_ASSIGNED_FOR_REVIEW = "7";
    String COI_DISCLOSURE_ACTION_LOG_ASSIGNED_REVIEW_COMPLETED = "8";
    String COI_DISCLOSURE_ACTION_LOG_MODIFY_RISK = "10";
    String COI_DISCLOSURE_ACTION_LOG_ADD_CONFLICT_STATUS = "30";
    String COI_DISCLOSURE_ACTION_LOG_MODIFY_CONFLICT_STATUS = "29";
    String COI_DISCLOSURE_ACTION_LOG_ADD_RISK = "9";
    String COI_DIS_ACTION_LOG_CREATED_REVIEW_WITH_REVIEWER = "16";
    String COI_DISCLOSURE_ACTION_LOG_REVIEWER_START_REVIEW = "17";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_START_REVIEW_WITH_REVIEWER = "18";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_START_REVIEW_WITHOUT_REVIEWER = "25";
    String COI_DISCLOSURE_ACTION_LOG_REVIEWER_COMPLETE_REVIEW = "19";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITH_REVIEWER = "20";
    String COI_DISCLOSURE_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITHOUT_REVIEWER = "26";
    String COI_DISCLOSURE_ACTION_LOG_REVIEW_REMOVED_WITH_REVIEWER = "21";
    String COI_DISCLOSURE_ACTION_LOG_REVIEW_REMOVED_WITHOUT_REVIEWER = "27";
    String COI_DIS_ACTION_LOG_MODIFIED_REVIEW_WITH_REVIEWER = "22";
    String COI_DIS_ACTION_LOG_MODIFIED_REVIEW_WITHOUT_REVIEWER = "24";
    String COI_DIS_ACTION_LOG_CREATED_REVIEW_WITHOUT_REVIEWER = "23";
    String COI_DISCLOSURE_STATUS_WITHDRAW = "6";
    String COI_DISCLOSURE_STATUS_RETURN = "5";
    String COI_DISCLOSURE_STATUS_COMPLETED = "4";
    String COI_DISCLOSURE_STATUS_SUBMITTED = "2";

    String COI_REVIEWER_REVIEW_STATUS_COMPLETED = "2";
    String COI_REVIEWER_REVIEW_STATUS_START = "3";
    String COI_DISCLOSURE_REVIEWER_STATUS_COMPLETED = "8";
    String COI_DISCLOSURE_REVIEWER_STATUS_ASSIGNED = "7";

    Integer OPA_MODULE_CODE = 23;
    String OPA_DISCLOSURE_STATUS_SUBMIT = "2";
    String OPA_DISCLOSURE_STATUS_REVIEW_IN_PROGRESS = "3";
    String OPA_DISCLOSURE_STATUS_WITHDRAW = "6";
    String OPA_DISCLOSURE_STATUS_RETURN = "5";
    String OPA_DISCLOSURE_STATUS_COMPLETED = "4";
    String OPA_DISCLOSURE_STATUS_REVIEW_ASSIGNED = "7";
    String OPA_DISCLOSURE_STATUS_REVIEW_COMPLETED = "8";
    String OPA_DISCLOSURE_STATUS_PENDING = "1";

    String OPA_DISPOSITION_STATUS_PENDING = "1";
    String OPA_DISPOSITION_STATUS_COMPLETED = "3";

    String OPA_ACTION_LOG_TYPE_CREATED = "1";
    String OPA_ACTION_LOG_TYPE_SUBMITTED = "2";
    String OPA_ACTION_LOG_TYPE_WITHDRAWN = "3";
    String OPA_ACTION_LOG_TYPE_RETURNED = "4";
    String OPA_ACTION_LOG_TYPE_APPROVED = "5";
    String OPA_ACTION_LOG_TYPE_ADMIN_ASSIGNED = "6";
    String OPA_ACTION_LOG_TYPE_ADMIN_REASSIGNED = "7";

    // Consulting Disclosure
    Integer CONSULT_DISCL_MODULE_CODE = 27;
    String CONSULT_DISCL_MODULE_ITEM_CODE = "27";
    String CONSULT_DISCL_MODULE_SUB_ITEM_CODE = "0";
    String CONSULT_DISCL_STATUS_SUBMIT = "2";
    String CONSULT_DISCL_STATUS_REVIEW_IN_PROGRESS = "3";
    String CONSULT_DISCL_STATUS_WITHDRAW = "7";
    String CONSULT_DISCL_STATUS_RETURN = "8";
    String CONSULT_DISCL_STATUS_COMPLETED = "6";
    String CONSULT_DISCL_STATUS_REVIEW_ASSIGNED = "4";
    String CONSULT_DISCL_STATUS_REVIEW_COMPLETED = "6";
    String CONSULT_DISCL_STATUS_PENDING = "1";

    String CONSULT_DISCL_DISPOSITION_STATUS_PENDING = "1";
    String CONSULT_DISCL_DISPOSITION_STATUS_COMPLETED = "2";

    String CONSULT_DISCL_ACTION_LOG_TYPE_CREATED = "1";
    String CONSULT_DISCL_ACTION_LOG_TYPE_SUBMITTED = "2";
    String CONSULT_DISCL_ACTION_LOG_TYPE_WITHDRAWN = "3";
    String CONSULT_DISCL_ACTION_LOG_TYPE_RETURNED = "4";
    String CONSULT_DISCL_ACTION_LOG_TYPE_APPROVED = "5";
    String CONSULT_DISCL_ACTION_LOG_TYPE_ADMIN_ASSIGNED = "6";
    String CONSULT_DISCL_ACTION_LOG_TYPE_ADMIN_REASSIGNED = "7";
    //

    String COI_PERSON_ENTITY_ACTION_LOG_CREATED = "1";
    String COI_PERSON_ENTITY_ACTION_LOG_ACTIVATED = "2";
    String COI_PERSON_ENTITY_ACTION_LOG_INACTIVATED = "3";
    String COI_PERSON_ENTITY_ACTION_LOG_MODIFIED = "4";
    String COI_PERSON_ENTITY_ACTION_LOG_REL_ADDED = "5";
    String COI_PERSON_ENTITY_ACTION_LOG_REL_REMOVED = "6";
    String COI_PERSON_ENTITY_ACTION_LOG_FORM_COMPLETED = "7";
    String COI_DISCLOSURE_REVIEW_STATUS_PENDING = "1";
    String OPA_MODULE_ITEM_CODE = "23";
    String OPA_MODULE_SUB_ITEM_CODE = "0";
    String OPA_REVIEW_ASSIGNED = "1";
    String OPA_REVIEW_IN_PROGRESS = "2";
    String OPA_REVIEW_COMPLETED = "3";

    String OPA_DIS_ACTION_LOG_MODIFIED_REVIEW_WITH_REVIEWER = "10";
    String OPA_DIS_ACTION_LOG_MODIFIED_REVIEW_WITHOUT_REVIEWER = "11";
    String OPA_DIS_ACTION_LOG_CREATED_REVIEW_WITHOUT_REVIEWER = "9";
    String OPA_DIS_ACTION_LOG_CREATED_REVIEW_WITH_REVIEWER = "8";
    String OPA_DIS_ACTION_LOG_ADMIN_START_REVIEW_WITH_REVIEWER = "12";
    String OPA_DIS_ACTION_LOG_ADMIN_START_REVIEW_WITHOUT_REVIEWER = "13";
    String OPA_DIS_ACTION_LOG_ADMIN_START_REVIEW_BY_REVIEWER = "14";
    String OPA_DIS_ACTION_LOG_ADMIN_COMPLETE_REVIEW_BY_REVIEWER = "17";
    String OPA_DIS_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITH_REVIEWER = "16";
    String OPA_DIS_ACTION_LOG_ADMIN_COMPLETE_REVIEW_WITHOUT_REVIEWER = "15";
    String OPA_DIS_ACTION_LOG_ADMIN_REMOVED_REVIEW_WITH_REVIEWER = "19";
    String OPA_DIS_ACTION_LOG_ADMIN_REMOVED_REVIEW_WITHOUT_REVIEWER = "18";
    String OPA_DISCLOSURE_DETAIL_COMMENT_TYPE = "3";

    String COI_DISCL_CONFLICT_RELATION_COMMENT_TYPE = "1";
    String COI_DISCL_CONFLICT_RELATION_COMPONENT_TYPE = "1";
    String COI_TRAVEL_DISCL_CONFLICT_RELATION_COMPONENT_TYPE = "2";
    String COI_DISCL_REVIEW_COMPONENT_TYPE = "8";
    String ACTIVE_ANSWERED_UNANSWERED = "ACTIVE_ANSWERED_UNANSWERED";
    Integer TRAVEL_MODULE_CODE = 24;
    String COI_VALIDATION_PRO_SFI_ACTION_TYPE = "PS";
    Integer TRAVEL_SELF_RELATIONSHIP = 4;

    String DISCLOSURE_TYPE_CODE_FCOI = "1";
    String DISCLOSURE_TYPE_CODE_AWARD = "3";
    String DISCLOSURE_TYPE_CODE_PROPOSAL = "2";
    String DISCLOSURE_TYPE_CODE_REVISION = "4";
    String PROJECT_DISCL_FCOI_TYPE_CODE = "2";
}
