package com.polus.fibicomp.constants;

public interface StaticPlaceholders {

    String DISCLOSURE_STATUS = "DISCLOSURE_STATUS";
    String CERTIFICATION_DATE = "CERTIFICATION_DATE"; // overriding query value
    String WITHDRAWAL_REASON = "WITHDRAWAL_REASON";
    String ADMINISTRATOR_NAME = "ADMINISTRATOR_NAME";
    String RETURN_REASON = "RETURN_REASON";
    String ADMIN_ASSIGNED_BY = "ADMIN_ASSIGNED_BY";
    String ADMIN_ASSIGNED_TO = "ADMIN_ASSIGNED_TO";
    String REVIEWER_REVIEW_STATUS = "REVIEWER_REVIEW_STATUS";
}
