\. ./Scripts/Table_scripts.sql 

\. ./Lookups/account_type.sql
\. ./Lookups/activity_grantcall_mapping.sql
\. ./Lookups/activity_type.sql
\. ./Lookups/admin_group.sql
\. ./Lookups/appointment_type.sql
\. ./Lookups/arg_value_lookup.sql
\. ./Lookups/audit_log_config.sql
\. ./Lookups/audit_report_type.sql
\. ./Lookups/award_association_type.sql
\. ./Lookups/award_attachment_type.sql
\. ./Lookups/award_basis_of_payment.sql
\. ./Lookups/award_budget_fund_type.sql
\. ./Lookups/award_budget_status.sql
\. ./Lookups/award_contact_type.sql
\. ./Lookups/award_document_status.sql
\. ./Lookups/award_document_type.sql
\. ./Lookups/award_method_of_payment.sql
\. ./Lookups/award_status.sql
\. ./Lookups/award_task_type_mapping.sql
\. ./Lookups/award_transaction_status.sql
\. ./Lookups/award_transaction_type.sql
\. ./Lookups/award_type.sql
\. ./Lookups/award_workflow_status.sql
\. ./Lookups/budget_category.sql
\. ./Lookups/budget_category_type.sql
\. ./Lookups/budget_status.sql
\. ./Lookups/budget_type.sql
\. ./Lookups/BUILD_DETAILS.sql
\. ./Lookups/coeus_module.sql
\. ./Lookups/coeus_sub_module.sql
\. ./Lookups/column_lookup.sql
\. ./Lookups/comment_type.sql
\. ./Lookups/contact_role_type.sql
\. ./Lookups/cost_element.sql
\. ./Lookups/country.sql
\. ./Lookups/currency.sql
\. ./Lookups/currency_rate.sql
\. ./Lookups/custom_data_elements_data_type.sql
\. ./Lookups/degree_type.sql
\. ./Lookups/delegations_status.sql
\. ./Lookups/document_status.sql
\. ./Lookups/dyn_modules_config.sql
\. ./Lookups/dyn_section_config.sql
\. ./Lookups/dyn_subsection_config.sql
\. ./Lookups/ENVELOPE_STATUS.sql
\. ./Lookups/eps_prop_person_role.sql
\. ./Lookups/eps_proposal_action_type.sql
\. ./Lookups/eps_proposal_attach_type.sql
\. ./Lookups/eps_proposal_document_status.sql
\. ./Lookups/eps_proposal_key_personnel_attach_type.sql
\. ./Lookups/eps_proposal_resrch_type.sql
\. ./Lookups/eps_proposal_status.sql
\. ./Lookups/eps_proposal_type.sql
\. ./Lookups/ESIGN_RECIPIENT_TYPE.sql
\. ./Lookups/ESIGNATURE_CONFIGURATION.sql
\. ./Lookups/evaluation_recommendation.sql
\. ./Lookups/ext_rev_reviewer_flow_status.sql
\. ./Lookups/ext_review_action_type.sql
\. ./Lookups/ext_review_attachment_type.sql
\. ./Lookups/ext_review_comment_type.sql
\. ./Lookups/ext_review_reviewers_status.sql
\. ./Lookups/ext_review_service_type.sql
\. ./Lookups/ext_review_status.sql
\. ./Lookups/ext_reviewer_academic_area.sql
\. ./Lookups/ext_reviewer_academic_rank.sql
\. ./Lookups/ext_reviewer_affiliation.sql
\. ./Lookups/ext_reviewer_attachment_type.sql
\. ./Lookups/ext_reviewer_cira.sql
\. ./Lookups/ext_reviewer_originality.sql
\. ./Lookups/ext_reviewer_thoroughness.sql
\. ./Lookups/ext_reviewers_status.sql
\. ./Lookups/faq_category.sql
\. ./Lookups/faq_sub_category.sql
\. ./Lookups/fibi_workflow_map.sql
\. ./Lookups/fibi_workflow_role_type.sql
\. ./Lookups/fibi_workflow_status.sql
\. ./Lookups/field_section_mapping.sql
\. ./Lookups/file_type.sql
\. ./Lookups/final_evaluation_status.sql
\. ./Lookups/frequency.sql
\. ./Lookups/frequency_base.sql
\. ./Lookups/funding_scheme.sql
\. ./Lookups/funding_source_type.sql
\. ./Lookups/invoice_frequency.sql
\. ./Lookups/letter_template_type.sql
\. ./Lookups/locale.sql
\. ./Lookups/lock_configuration.sql
\. ./Lookups/message.sql
\. ./Lookups/milestone_status.sql
\. ./Lookups/mitkc_unit_with_children.sql
\. ./Lookups/module_derived_roles.sql
\. ./Lookups/module_variable_section.sql
\. ./Lookups/narrative_status.sql
\. ./Lookups/notification_recipient.sql
\. ./Lookups/notification_type.sql
\. ./Lookups/orcid_webhook_action_types.sql
\. ./Lookups/orcid_work_category.sql
\. ./Lookups/orcid_work_citation_type.sql
\. ./Lookups/orcid_work_status.sql
\. ./Lookups/orcid_work_type.sql
\. ./Lookups/organization.sql
\. ./Lookups/organization_type.sql
\. ./Lookups/parameter.sql
\. ./Lookups/person.sql
\. ./Lookups/person_role_type.sql
\. ./Lookups/person_roles.sql
\. ./Lookups/person_training.sql
\. ./Lookups/pre_review_section_type.sql
\. ./Lookups/pre_review_status.sql
\. ./Lookups/pre_review_type.sql
\. ./Lookups/preference_type.sql
\. ./Lookups/proposal_action_item.sql
\. ./Lookups/proposal_action_type.sql
\. ./Lookups/proposal_attach_type.sql
\. ./Lookups/proposal_funding_status.sql
\. ./Lookups/proposal_resrch_type.sql
\. ./Lookups/proposal_status.sql
\. ./Lookups/proposal_type.sql
\. ./Lookups/quest_column_nextvalue.sql
\. ./Lookups/quest_group_type.sql
\. ./Lookups/quick_links.sql
\. ./Lookups/rate_class.sql
\. ./Lookups/rate_class_type.sql
\. ./Lookups/rate_type.sql
\. ./Lookups/RECIPIENT_STATUS.sql
\. ./Lookups/relevant_field.sql
\. ./Lookups/report_last_sync_time.sql
\. ./Lookups/research_areas.sql
\. ./Lookups/research_center.sql
\. ./Lookups/research_sub_area.sql
\. ./Lookups/research_type.sql
\. ./Lookups/research_type_area.sql
\. ./Lookups/research_type_sub_area.sql
\. ./Lookups/review_status.sql
\. ./Lookups/review_type.sql
\. ./Lookups/right_section_mapping.sql
\. ./Lookups/rights.sql
\. ./Lookups/rights_type.sql
\. ./Lookups/role.sql
\. ./Lookups/role_rights.sql
\. ./Lookups/role_type.sql
\. ./Lookups/science_keyword.sql
\. ./Lookups/scoring_criteria.sql
\. ./Lookups/section_module.sql
\. ./Lookups/section_type.sql
\. ./Lookups/societal_challenge_area.sql
\. ./Lookups/societal_challenge_subarea.sql
\. ./Lookups/sp_rev_approval_type.sql
\. ./Lookups/special_review.sql
\. ./Lookups/special_review_usage.sql
\. ./Lookups/sponsor.sql
\. ./Lookups/sponsor_hierarchy.sql
\. ./Lookups/sponsor_report.sql
\. ./Lookups/sponsor_role.sql
\. ./Lookups/sponsor_term_type.sql
\. ./Lookups/sponsor_type.sql
\. ./Lookups/training.sql
\. ./Lookups/unit.sql
\. ./Lookups/unit_administrator_type.sql
\. ./Lookups/unit_level.sql
\. ./Lookups/UNIT_TYPE.sql
\. ./Lookups/web_socket_con_config.sql
\. ./Lookups/workflow_map_type.sql
\. ./Lookups/workflow_status.sql

-- \. ./Scripts/migration_scripts.sql

\. ./Procedures/ADD_TO_INBOX.sql
\. ./Procedures/CHECK_USER_HAS_RIGHT_IN_DOC.sql
\. ./Procedures/GET_ADMINISTRATIVE_DETAILS.sql
\. ./Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./Procedures/GET_ALL_SYSTEM_RIGHTS.sql
\. ./Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql
\. ./Procedures/GET_CURRENT_AND_PENDING_DETAILS.sql
\. ./Procedures/GET_PERSON_BASED_RIGHT_AND_UNIT.sql
\. ./Procedures/GET_PERSON_HAS_PERMISSION.sql
\. ./Procedures/GET_PERSON_TRAINING_LATESTDATE.sql
\. ./Procedures/GET_RESEARCH_SUMMARY_DETAILS.sql
\. ./Procedures/GET_RULE_EVALUATE_NOTIFICATION.sql
\. ./Procedures/GET_RULE_EVALUATE_VALIDATION.sql
\. ./Procedures/GET_TRAINING_DASHBOARD_COUNT.sql
\. ./Procedures/GET_TRAINING_DASHBOARD.sql
\. ./Procedures/GET_UNIT_BASED_PERSON_AND_RIGHT.sql
\. ./Procedures/GET_UNIT_HIERARCHY.sql
\. ./Procedures/GET_UNIT_ORGANIZATION.sql
\. ./Procedures/GET_UNIT_WITH_CHILDREN.sql
\. ./Procedures/GET_WIDGET_DATA_IN_DETAIL.sql
\. ./Procedures/INSERT_CURRENT_AND_PENDING_DETAILS.sql
\. ./Procedures/INSERT_QUESTIONNAIRE_ANS_HEADER.sql
\. ./Procedures/INSERT_QUESTIONNAIRE_ANSWERS.sql
\. ./Procedures/INSERT_WORKFLOW_ALTER_APPROVER.sql
\. ./Procedures/INSERT_WORKFLOW_FOR_ROLE_TYPE.sql
\. ./Procedures/IS_FINAL_APPROVAL.sql
\. ./Procedures/MIGRATION_METARULE.sql
\. ./Procedures/PERSON_ROLE_SYNCH.sql
\. ./Procedures/QUESTION_ANSWER_CHECK.sql
\. ./Procedures/REFRESH_PERSON_ROLE_RT.sql
\. ./Procedures/REFRESH_UNIT_HIERARCHY_TMP_TAB.sql
\. ./Procedures/ROLE_RIGHTS_AUDIT_PROC.sql
\. ./Procedures/RULE_EVAL_CHK_CURRENT_APPROVER.sql
\. ./Procedures/RULE_EVALUATE_EXPRESSION.sql
\. ./Procedures/RULE_EVALUATE_FUNCTION.sql
\. ./Procedures/RULE_EVALUATE_QUESTION.sql
\. ./Procedures/RULE_EVALUATE_VARIABLE.sql
\. ./Procedures/RULE_EVALUATE_WORKFLOW.sql
\. ./Procedures/RULE_EVALUATION.sql
\. ./Procedures/RULE_VERIFY_EXPRESSION.sql
\. ./Procedures/SUPPORT_WIDGETS.sql
\. ./Procedures/SYNC_UNIT_WITH_CHILDREN_PERSON_ROLE.sql
\. ./Procedures/UPD_ANS_TO_NEW_QUEST_VERSN.sql
\. ./Procedures/UPDATE_CUSTOM_DATA.sql
\. ./Procedures/USER_VALIDATION.sql

\. ./Functions/FN_CHECK_USER_HAS_RIGHT_IN_DOC.sql
\. ./Functions/FN_CHK_AGREEMENT_QNR_COMPLETE.sql
\. ./Functions/FN_FEED_INST_PROPOSAL.sql
\. ./Functions/FN_FOR_ALL_AGREEMENT.sql
\. ./Functions/FN_FOR_ALL_AWARD.sql
\. ./Functions/FN_FOR_ALL_CLAIMS.sql
\. ./Functions/FN_FOR_ALL_NDA.sql
\. ./Functions/FN_FOR_ALL_NEGOTIATION.sql
\. ./Functions/FN_FOR_ALL_PROGRESS_REPORT.sql
\. ./Functions/FN_FOR_ALL_PROPOSAL.sql
\. ./Functions/FN_FOR_ALL_SR.sql
\. ./Functions/FN_GET_CHILD_NODES.sql
\. ./Functions/FN_GET_DATE_DIFFERENCE.sql
\. ./Functions/FN_GET_HIERARCHY_LEVEL.sql
\. ./Functions/FN_GET_UNIT_HIERARCHY_LEVEL.sql
\. ./Functions/FN_IS_SPONSOR_ADMIN_VERIFIED.sql
\. ./Functions/FN_KEY_PERSON_EFFORT_NULL_CHK.sql
\. ./Functions/FN_LEAD_UNIT_BELOW.sql
\. ./Functions/FN_PERSON_HAS_AUTHORIZATION.sql
\. ./Functions/FN_PERSON_HAS_RIGHTS.sql
\. ./Functions/FN_PERSON_TRAINING_COMPLETED.sql
\. ./Functions/FN_PRIME_SPONSOR_NULL.sql
\. ./Functions/FN_PRIME_SPONSOR_TYPE.sql
\. ./Functions/FN_PROPOSAL_PERSON_CERT_COMPLETE.sql
\. ./Functions/FN_RULE_BUILD_EVALUATION_PANEL.sql
\. ./Functions/FN_RULE_BUILD_WORKFLOW.sql
\. ./Functions/FN_SPONSOR_EQUAL_PRIME_SPONSOR.sql
\. ./Functions/FN_SPONSOR_TYPE.sql
\. ./Functions/FN_WORKFLOW_APPROVE.sql
\. ./Functions/FN_WORKFLOW_HANDLE_DELEGATIONS.sql

SET FOREIGN_KEY_CHECKS = 1;