DELIMITER //
CREATE PROCEDURE `GET_DISCLOSURE_RELATIONS`(
	AV_MODULE_CODE            INT(3),
	AV_PERSON_ID              VARCHAR(40),
	AV_DISCLOSURE_ID          INT(10)
)
BEGIN
	
    IF AV_MODULE_CODE = 1 THEN
    
		IF AV_DISCLOSURE_ID != null THEN
			SELECT DISTINCT T2.AWARD_ID, T2.AWARD_NUMBER, T2.TITLE, T2.BEGIN_DATE, T2.FINAL_EXPIRATION_DATE, T2.LEAD_UNIT_NUMBER, T3.UNIT_NAME, T4.SPONSOR_NAME ,
            T5.FULL_NAME, T6.DESCRIPTION AS STATUS FROM COI_DISCLOSURE_DETAILS T1 INNER JOIN AWARD T2 ON  
            T2.AWARD_ID=T1.MODULE_ITEM_KEY INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T2.LEAD_UNIT_NUMBER INNER JOIN sponsor T4 ON T4.SPONSOR_CODE = T2.SPONSOR_CODE
            INNER JOIN award_persons T5 on (T5.AWARD_ID = T2.AWARD_ID AND T5.PI_FLAG = 'Y') INNER JOIN award_status T6 ON T6.status_code = T2.status_code
            WHERE T1.MODULE_CODE = 1 AND (T2.AWARD_SEQUENCE_STATUS ='ACTIVE' OR
            (T2.AWARD_SEQUENCE_STATUS='PENDING' AND AWARD_DOCUMENT_TYPE_CODE=1))AND T2.AWARD_SEQUENCE_STATUS IN ( 'ACTIVE','PENDING') AND T1.DISCLOSURE_ID= AV_DISCLOSURE_ID;
            
		else
			SELECT DISTINCT T1.AWARD_ID, T1.AWARD_NUMBER, T1.TITLE, T1.BEGIN_DATE, T1.FINAL_EXPIRATION_DATE, T1.LEAD_UNIT_NUMBER, T3.UNIT_NAME, T4.SPONSOR_NAME,
            T5.FULL_NAME AS PI, T6.DESCRIPTION AS STATUS FROM AWARD T1 INNER JOIN UNIT T3 
            ON T3.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER INNER JOIN sponsor T4 ON T4.SPONSOR_CODE = T1.SPONSOR_CODE
            INNER JOIN award_persons T5 on (T5.AWARD_ID = T1.AWARD_ID AND T5.PI_FLAG = 'Y') INNER JOIN award_status T6 ON T6.status_code = T1.status_code 
            INNER JOIN award_persons T7 on T7.AWARD_ID = T1.AWARD_ID WHERE
            (T1.AWARD_SEQUENCE_STATUS ='ACTIVE' OR (T1.AWARD_SEQUENCE_STATUS='PENDING' AND T1.AWARD_DOCUMENT_TYPE_CODE=1)) and T7.PERSON_ID = AV_PERSON_ID;
            
        END IF;

	ELSE IF AV_MODULE_CODE = 3 THEN

		IF AV_DISCLOSURE_ID != null THEN
			SELECT DISTINCT T2.PROPOSAL_ID, T2.TITLE, T3.DESCRIPTION AS STATUS, T2.START_DATE, T2.END_DATE, T2.HOME_UNIT_NUMBER, T2.HOME_UNIT_NAME,
            T4.SPONSOR_NAME AS SPONSOR_NAME, T5.SPONSOR_NAME AS PRIME_SPONSOR_NAME FROM COI_DISCLOSURE_DETAILS T1 INNER JOIN EPS_PROPOSAL T2 
            ON T2.PROPOSAL_ID=T1.MODULE_ITEM_KEY INNER JOIN eps_proposal_status T3 ON T2.STATUS_CODE = T3.STATUS_CODE 
            INNER JOIN SPONSOR T4 ON T4.SPONSOR_CODE = T2.SPONSOR_CODE INNER JOIN SPONSOR T5 ON T5.SPONSOR_CODE = T2.PRIME_SPONSOR_CODE
            WHERE T1.MODULE_CODE = 3 AND T2.DOCUMENT_STATUS_CODE <> 3 AND 
            T2.STATUS_CODE not IN (1,29,35,9,22,20,24,30,3,12,11) AND T2.DOCUMENT_STATUS_CODE <> 3 AND T1.DISCLOSURE_ID= AV_DISCLOSURE_ID;
            
		else
			SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T3.DESCRIPTION AS STATUS, T1.START_DATE, T1.END_DATE, T1.HOME_UNIT_NUMBER, T1.HOME_UNIT_NAME,
            T4.SPONSOR_NAME AS SPONSOR_NAME, T5.SPONSOR_NAME AS PRIME_SPONSOR_NAME, T6.FULL_NAME AS PI FROM EPS_PROPOSAL T1 INNER JOIN eps_proposal_status T3 ON T3.STATUS_CODE = T1.STATUS_CODE 
            INNER JOIN SPONSOR T4 ON T4.SPONSOR_CODE = T1.SPONSOR_CODE INNER JOIN SPONSOR T5 ON T5.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE
            INNER JOIN EPS_PROPOSAL_PERSONS T6 ON (T6.PROPOSAL_ID=T1.PROPOSAL_ID AND T6.PROP_PERSON_ROLE_ID = 3 AND T6.PI_FLAG = 'Y')
            INNER JOIN EPS_PROPOSAL_PERSONS T7 ON T7.PROPOSAL_ID=T1.PROPOSAL_ID WHERE T1.DOCUMENT_STATUS_CODE <> 3 AND T1.STATUS_CODE not IN (1,29,35,9,22,20,24,30,3,12,11) 
            AND T1.DOCUMENT_STATUS_CODE <> 3 and T7.PERSON_ID = AV_PERSON_ID;
        END IF;
	END IF;
    end if;
END

END
//