DELIMITER //
CREATE PROCEDURE `GET_QUICK_CARD_COUNTS`(
	AV_TYPE                         VARCHAR(20),
	AV_PERSON_ID                    VARCHAR(200))
BEGIN

DECLARE LS_DYN_SQL LONGTEXT;
SET LS_DYN_SQL ='';

IF AV_TYPE = 'ADMIN' THEN
	SET LS_DYN_SQL ='';
ELSEIF AV_TYPE = 'REVIEWER' THEN
	SET LS_DYN_SQL =CONCAT('SELECT (SELECT COUNT(DISTINCT T1.DISCLOSURE_ID)  FROM COI_DISCLOSURE T1 
					LEFT JOIN COI_REVIEW T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID WHERE T2.REVIEW_STATUS_TYPE_CODE <>3 AND T2.ASSIGNEE_PERSON_ID = ',AV_PERSON_ID,
                    ') AS NEW_SUBMISSIONS, (SELECT COUNT(DISTINCT T1.DISCLOSURE_ID) FROM COI_DISCLOSURE T1 
					LEFT JOIN COI_REVIEW T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID) AS CONFLICTS_IDENTIFIED');
END IF;

SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
END
//
