DELIMITER //
CREATE PROCEDURE `GET_DISCLOSURE_PROJECTS`(
	AV_DISCLOSURE_ID          INT
)
BEGIN

        SELECT DISTINCT
			COALESCE(T2.EXTERNAL_SYSTEM_REF_ID, T3.EXTERNAL_SYSTEM_REF_ID, T4.EXTERNAL_SYSTEM_REF_ID) AS PROJECT_ID,
			COALESCE(T2.AWARD_NUMBER, T3.PROPOSAL_NUMBER, T4.PROPOSAL_NUMBER) AS PROJECT_NUMBER,
            COALESCE(T2.TITLE, T3.TITLE, T4.TITLE) AS PROJECT_TITLE,
			COALESCE(T2.AWARD_STATUS, T3.PROPOSAL_STATUS, T4.PROPOSAL_STATUS) AS PROJECT_STATUS,
			COALESCE(T2.AWARD_START_DATE, T3.PROPOSAL_START_DATE, T4.PROPOSAL_START_DATE) AS PROJECT_START_DATE,
            COALESCE(T2.AWARD_END_DATE, T3.PROPOSAL_END_DATE, T4.PROPOSAL_END_DATE) AS PROJECT_END_DATE,
			COALESCE(T2.LEAD_UNIT_NUMBER, T3.LEAD_UNIT_NUMBER, T4.LEAD_UNIT_NUMBER) AS LEAD_UNIT_NUMBER,
			COALESCE(T2.LEAD_UNIT_NAME, T3.LEAD_UNIT_NAME, T4.LEAD_UNIT_NAME) AS LEAD_UNIT_NAME,
            COALESCE(T2.SPONSOR_NAME, T3.SPONSOR_NAME, T4.SPONSOR_NAME) AS PROJECT_SPONSOR_NAME,
			COALESCE(T2.PRIME_SPONSOR_NAME, T3.PRIME_SPONSOR_NAME, T4.PRIME_SPONSOR_NAME) AS PROJECT_PRIME_SPONSOR_NAME,
			COALESCE(T2.PI_NAME, T3.PI_NAME, T4.PI_NAME) AS PI_NAME,
			COALESCE(T2.KEY_PERSON_NAME, T3.KEY_PERSON_NAME, T4.KEY_PERSON_NAME) AS KEY_PERSON_NAME,
			COALESCE(T2.KEY_PERSON_ID, T3.KEY_PERSON_ID, T4.KEY_PERSON_ID) AS KEY_PERSON_ID,
			COALESCE(T2.KEY_PERSON_ROLE_NAME, T3.KEY_PERSON_ROLE_NAME, T4.KEY_PERSON_ROLE_NAME) AS REPORTER_ROLE,
			T1.MODULE_CODE,
            (CASE WHEN T7.IS_PROJECT_COMPLETED_COUNT IS NOT NULL THEN false ELSE true END) AS IS_PROJECT_COMPLETED,
            T8.CONFLICT_STATUS_COUNT,
			T9.COI_PROJECT_TYPE_CODE,
			T9.DESCRIPTION AS COI_PROJECT_TYPE,
            T9.BADGE_COLOR,
			T9.PROJECT_ICON,
			T1.COI_DISCL_PROJECTS_ID
			FROM COI_DISCLOSURE T0
			INNER JOIN COI_DISCL_PROJECTS T1 ON T1.DISCLOSURE_ID = T0.DISCLOSURE_ID
            LEFT JOIN COI_PROJECT_AWARD_V T2 ON (T2.EXTERNAL_SYSTEM_REF_ID = T1.MODULE_ITEM_KEY AND T1.MODULE_CODE = 1 AND T0.PERSON_ID = T2.KEY_PERSON_ID)
            LEFT JOIN COI_PROJECT_INSTITUTE_PROPOSAL_V T3 ON (T3.EXTERNAL_SYSTEM_REF_ID = T1.MODULE_ITEM_KEY AND T1.MODULE_CODE = 2 AND T0.PERSON_ID = T3.KEY_PERSON_ID)
            LEFT JOIN COI_PROJECT_PROPOSAL_V T4 ON (T4.EXTERNAL_SYSTEM_REF_ID = T1.MODULE_ITEM_KEY AND T1.MODULE_CODE = 3 AND T0.PERSON_ID = T4.KEY_PERSON_ID)
            LEFT JOIN (SELECT COUNT(C1.COI_DISCL_PROJECT_ENTITY_REL_ID) AS IS_PROJECT_COMPLETED_COUNT, C2.MODULE_ITEM_KEY
						FROM COI_DISCL_PROJECT_ENTITY_REL C1
						INNER JOIN COI_DISCL_PROJECTS C2 ON C2.COI_DISCL_PROJECTS_ID = C1.COI_DISCL_PROJECTS_ID
						WHERE C1.PROJECT_CONFLICT_STATUS_CODE IS NULL
						AND C2.DISCLOSURE_ID = AV_DISCLOSURE_ID
						AND C2.MODULE_CODE = 1 ) T7 ON T7.MODULE_ITEM_KEY = T2.EXTERNAL_SYSTEM_REF_ID
            LEFT JOIN (SELECT CONCAT('[', GROUP_CONCAT(JSON_OBJECT(CONFLICT_STATUS_GROUP, CONFLICT_COUNT)), ']') AS CONFLICT_STATUS_COUNT,
						COI_DISCL_PROJECTS_ID
						FROM ( SELECT CASE WHEN C2.PROJECT_CONFLICT_STATUS_CODE BETWEEN 100 AND 199 THEN 1
							WHEN C2.PROJECT_CONFLICT_STATUS_CODE BETWEEN 200 AND 299 THEN 2
							WHEN C2.PROJECT_CONFLICT_STATUS_CODE BETWEEN 300 AND 399 THEN 3
							END AS CONFLICT_STATUS_GROUP,
							C1.COI_DISCL_PROJECTS_ID,
							COUNT(C2.PROJECT_CONFLICT_STATUS_CODE) AS CONFLICT_COUNT
							FROM COI_DISCL_PROJECT_ENTITY_REL C2
							INNER JOIN COI_DISCL_PROJECTS C1 ON C1.COI_DISCL_PROJECTS_ID = C2.COI_DISCL_PROJECTS_ID
							WHERE C2.PROJECT_CONFLICT_STATUS_CODE IS NOT NULL
							AND C1.DISCLOSURE_ID = AV_DISCLOSURE_ID
							GROUP BY CONFLICT_STATUS_GROUP, C1.COI_DISCL_PROJECTS_ID ) AS grouped
						GROUP BY COI_DISCL_PROJECTS_ID) T8 ON T8.COI_DISCL_PROJECTS_ID = T1.COI_DISCL_PROJECTS_ID
            LEFT JOIN COI_PROJECT_TYPE T9 ON (T9.COI_PROJECT_TYPE_CODE = T2.COI_PROJECT_TYPE_CODE
				OR T9.COI_PROJECT_TYPE_CODE = T3.COI_PROJECT_TYPE_CODE OR T9.COI_PROJECT_TYPE_CODE = T4.COI_PROJECT_TYPE_CODE)
            WHERE T0.DISCLOSURE_ID= AV_DISCLOSURE_ID;

END
//
