//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 06:30:11 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.payroll;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Specifies what the allocation will be applied to
 * 
 * <p>Java class for Costing_Allocation_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Costing_Allocation_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Worker_Reference" type="{urn:com.workday/bsvc}WorkerObjectType"/&gt;
 *           &lt;element name="Position_Restriction_Reference" type="{urn:com.workday/bsvc}Position_ElementObjectType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Position_Reference" type="{urn:com.workday/bsvc}Position_ElementObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Earning_Reference" type="{urn:com.workday/bsvc}Earning__All_ObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Position_Element_Effective_As-of_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Replace_Existing_Costing_Allocation_Intervals" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Costing_Allocation_Interval_Data" type="{urn:com.workday/bsvc}Costing_Allocation_Interval_DataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Costing_Allocation_DataType", propOrder = {
    "workerReference",
    "positionRestrictionReference",
    "positionReference",
    "earningReference",
    "positionElementEffectiveAsOfDate",
    "replaceExistingCostingAllocationIntervals",
    "costingAllocationIntervalData"
})
public class CostingAllocationDataType {

    @XmlElement(name = "Worker_Reference")
    protected WorkerObjectType workerReference;
    @XmlElement(name = "Position_Restriction_Reference")
    protected PositionElementObjectType positionRestrictionReference;
    @XmlElement(name = "Position_Reference")
    protected PositionElementObjectType positionReference;
    @XmlElement(name = "Earning_Reference")
    protected EarningAllObjectType earningReference;
    @XmlElement(name = "Position_Element_Effective_As-of_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar positionElementEffectiveAsOfDate;
    @XmlElement(name = "Replace_Existing_Costing_Allocation_Intervals")
    protected Boolean replaceExistingCostingAllocationIntervals;
    @XmlElement(name = "Costing_Allocation_Interval_Data")
    protected List<CostingAllocationIntervalDataType> costingAllocationIntervalData;

    /**
     * Gets the value of the workerReference property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerObjectType }
     *     
     */
    public WorkerObjectType getWorkerReference() {
        return workerReference;
    }

    /**
     * Sets the value of the workerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerObjectType }
     *     
     */
    public void setWorkerReference(WorkerObjectType value) {
        this.workerReference = value;
    }

    /**
     * Gets the value of the positionRestrictionReference property.
     * 
     * @return
     *     possible object is
     *     {@link PositionElementObjectType }
     *     
     */
    public PositionElementObjectType getPositionRestrictionReference() {
        return positionRestrictionReference;
    }

    /**
     * Sets the value of the positionRestrictionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionElementObjectType }
     *     
     */
    public void setPositionRestrictionReference(PositionElementObjectType value) {
        this.positionRestrictionReference = value;
    }

    /**
     * Gets the value of the positionReference property.
     * 
     * @return
     *     possible object is
     *     {@link PositionElementObjectType }
     *     
     */
    public PositionElementObjectType getPositionReference() {
        return positionReference;
    }

    /**
     * Sets the value of the positionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionElementObjectType }
     *     
     */
    public void setPositionReference(PositionElementObjectType value) {
        this.positionReference = value;
    }

    /**
     * Gets the value of the earningReference property.
     * 
     * @return
     *     possible object is
     *     {@link EarningAllObjectType }
     *     
     */
    public EarningAllObjectType getEarningReference() {
        return earningReference;
    }

    /**
     * Sets the value of the earningReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarningAllObjectType }
     *     
     */
    public void setEarningReference(EarningAllObjectType value) {
        this.earningReference = value;
    }

    /**
     * Gets the value of the positionElementEffectiveAsOfDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPositionElementEffectiveAsOfDate() {
        return positionElementEffectiveAsOfDate;
    }

    /**
     * Sets the value of the positionElementEffectiveAsOfDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPositionElementEffectiveAsOfDate(XMLGregorianCalendar value) {
        this.positionElementEffectiveAsOfDate = value;
    }

    /**
     * Gets the value of the replaceExistingCostingAllocationIntervals property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReplaceExistingCostingAllocationIntervals() {
        return replaceExistingCostingAllocationIntervals;
    }

    /**
     * Sets the value of the replaceExistingCostingAllocationIntervals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReplaceExistingCostingAllocationIntervals(Boolean value) {
        this.replaceExistingCostingAllocationIntervals = value;
    }

    /**
     * Gets the value of the costingAllocationIntervalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costingAllocationIntervalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostingAllocationIntervalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CostingAllocationIntervalDataType }
     * 
     * 
     */
    public List<CostingAllocationIntervalDataType> getCostingAllocationIntervalData() {
        if (costingAllocationIntervalData == null) {
            costingAllocationIntervalData = new ArrayList<CostingAllocationIntervalDataType>();
        }
        return this.costingAllocationIntervalData;
    }

}
