//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 06:30:11 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.payroll;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of the Salary over the Cap allocation, (e.g., a set of allocation dimensions and percentages)
 * 
 * <p>Java class for Salary_Over_the_Cap_Costing_Allocation_Detail_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Salary_Over_the_Cap_Costing_Allocation_Detail_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SOC_Order" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SOC_Default_from_Organization_Assignment" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SOC_Costing_Override_Company_Reference" type="{urn:com.workday/bsvc}CompanyObjectType" minOccurs="0"/&gt;
 *         &lt;element name="SOC_Override_Worktag_Reference" type="{urn:com.workday/bsvc}Tenanted_Payroll_WorktagObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SOC_Distribution_Percent"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="9"/&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;fractionDigits value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Salary_Over_the_Cap_Costing_Allocation_Detail_DataType", propOrder = {
    "socOrder",
    "socDefaultFromOrganizationAssignment",
    "socCostingOverrideCompanyReference",
    "socOverrideWorktagReference",
    "socDistributionPercent"
})
public class SalaryOverTheCapCostingAllocationDetailDataType {

    @XmlElement(name = "SOC_Order", required = true)
    protected String socOrder;
    @XmlElement(name = "SOC_Default_from_Organization_Assignment")
    protected Boolean socDefaultFromOrganizationAssignment;
    @XmlElement(name = "SOC_Costing_Override_Company_Reference")
    protected CompanyObjectType socCostingOverrideCompanyReference;
    @XmlElement(name = "SOC_Override_Worktag_Reference")
    protected List<TenantedPayrollWorktagObjectType> socOverrideWorktagReference;
    @XmlElement(name = "SOC_Distribution_Percent", required = true)
    protected BigDecimal socDistributionPercent;

    /**
     * Gets the value of the socOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOCOrder() {
        return socOrder;
    }

    /**
     * Sets the value of the socOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOCOrder(String value) {
        this.socOrder = value;
    }

    /**
     * Gets the value of the socDefaultFromOrganizationAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSOCDefaultFromOrganizationAssignment() {
        return socDefaultFromOrganizationAssignment;
    }

    /**
     * Sets the value of the socDefaultFromOrganizationAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSOCDefaultFromOrganizationAssignment(Boolean value) {
        this.socDefaultFromOrganizationAssignment = value;
    }

    /**
     * Gets the value of the socCostingOverrideCompanyReference property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyObjectType }
     *     
     */
    public CompanyObjectType getSOCCostingOverrideCompanyReference() {
        return socCostingOverrideCompanyReference;
    }

    /**
     * Sets the value of the socCostingOverrideCompanyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyObjectType }
     *     
     */
    public void setSOCCostingOverrideCompanyReference(CompanyObjectType value) {
        this.socCostingOverrideCompanyReference = value;
    }

    /**
     * Gets the value of the socOverrideWorktagReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the socOverrideWorktagReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSOCOverrideWorktagReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TenantedPayrollWorktagObjectType }
     * 
     * 
     */
    public List<TenantedPayrollWorktagObjectType> getSOCOverrideWorktagReference() {
        if (socOverrideWorktagReference == null) {
            socOverrideWorktagReference = new ArrayList<TenantedPayrollWorktagObjectType>();
        }
        return this.socOverrideWorktagReference;
    }

    /**
     * Gets the value of the socDistributionPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSOCDistributionPercent() {
        return socDistributionPercent;
    }

    /**
     * Sets the value of the socDistributionPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSOCDistributionPercent(BigDecimal value) {
        this.socDistributionPercent = value;
    }

}
