
DROP PROCEDURE IF EXISTS COI_INT_GET_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;

\. ./Procedures/COI_INT_GET_ENTITY_DETAILS.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
