
DROP PROCEDURE IF EXISTS COI_INT_GET_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS GET_HEIR_PROJECT_DETAIL;
DROP PROCEDURE IF EXISTS GET_HEIR_PROJECT_TREE;
DROP PROCEDURE IF EXISTS COI_DISCL_GENERATE_JSON_PROJECT_DETAILS;
DROP VIEW IF EXISTS coi_project_award_v;
DROP VIEW IF EXISTS coi_project_institute_proposal_v;
DROP VIEW IF EXISTS coi_project_proposal_v;

\. ./Procedures/COI_INT_GET_ENTITY_DETAILS.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./Procedures/COI_DISCL_GENERATE_JSON_PROJECT_DETAILS.sql
\. ./Procedures/GET_DISCLOSURE_PROJECTS.sql
\. ./Procedures/GET_HEIR_PROJECT_DETAIL.sql
\. ./Procedures/GET_HEIR_PROJECT_TREE.sql
\. ./Views/coi_project_award_v.sql
\. ./Views/coi_project_institute_proposal_v.sql
\. ./Views/coi_project_proposal_v.sql

