
DROP PROCEDURE IF EXISTS COI_INT_GET_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS GET_HEIR_PROJECT_DETAIL;
DROP PROCEDURE IF EXISTS GET_HEIR_PROJECT_TREE;
DROP PROCEDURE IF EXISTS COI_DISCL_GENERATE_JSON_PROJECT_SNAPSHOT;
DROP VIEW IF EXISTS coi_project_award_v;
DROP VIEW IF EXISTS coi_project_institute_proposal_v;
DROP VIEW IF EXISTS coi_project_proposal_v;
DROP PROCEDURE IF EXISTS GET_COI_PROJECTS;
DROP PROCEDURE IF EXISTS COI_INT_KC_SPON_ORG_RESPONSE;
DROP PROCEDURE IF EXISTS COI_SYNC_FCOI_DISCLOSURE;
DROP PROCEDURE IF EXISTS COI_SYNC_INSERT_DISCL_PROJECTS;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_GENERAL_DETAILS;
DROP PROCEDURE IF EXISTS COI_SYNC_REMOVE_DEACTIVATED_PROJECTS;
DROP PROCEDURE IF EXISTS COI_SYNC_UPDATE_DISCL_INTEG_UPDATES;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_HISTORY;
DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;
DROP PROCEDURE IF EXISTS COI_INT_PROP_PERSON_DISCL_STATUS;
DROP FUNCTION  IF EXISTS COI_INT_PROP_DISCL_STATUS;
DROP FUNCTION  IF EXISTS COI_INT_PRSN_DISCL_EXP_DATE;


\. ./Procedures/COI_INT_GET_ENTITY_DETAILS.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./Procedures/COI_DISCL_GENERATE_JSON_PROJECT_SNAPSHOT.sql
\. ./Procedures/GET_DISCLOSURE_PROJECTS.sql
\. ./Procedures/GET_HEIR_PROJECT_DETAIL.sql
\. ./Procedures/GET_HEIR_PROJECT_TREE.sql
\. ./Views/coi_project_award_v.sql
\. ./Views/coi_project_institute_proposal_v.sql
\. ./Views/coi_project_proposal_v.sql
\. ./Procedures/GET_COI_PROJECTS.sql
\. ./Procedures/COI_INT_KC_SPON_ORG_RESPONSE.sql
\. ./Procedures/COI_SYNC_FCOI_DISCLOSURE.sql
\. ./Procedures/COI_SYNC_INSERT_DISCL_PROJECTS.sql
\. ./Procedures/GET_COI_DISCL_GENERAL_DETAILS.sql
\. ./Procedures/COI_SYNC_REMOVE_DEACTIVATED_PROJECTS.sql
\. ./Procedures/COI_SYNC_UPDATE_DISCL_INTEG_UPDATES.sql
\. ./Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./Procedures/VALIDATE_PROJECT_DISCLOSURE.sql
\. ./Procedures/COI_INT_PROP_PERSON_DISCL_STATUS.sql
\. ./Functions/COI_INT_PROP_DISCL_STATUS.sql
\. ./Functions/COI_INT_PRSN_DISCL_EXP_DATE.sql
