//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains optional costing allocation override values
 * 
 * <p>Java class for Assign_Costing_Allocation_Sub_Business_ProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Costing_Allocation_Sub_Business_ProcessType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Business_Sub_Process_Parameters" type="{urn:com.workday/bsvc}Business_Sub_Process_ParametersType" minOccurs="0"/&gt;
 *         &lt;element name="Position_Costing_Allocation_Assignment_Data" type="{urn:com.workday/bsvc}Assign_Costing_Allocation_Event_DataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Costing_Allocation_Sub_Business_ProcessType", propOrder = {
    "businessSubProcessParameters",
    "positionCostingAllocationAssignmentData"
})
public class AssignCostingAllocationSubBusinessProcessType {

    @XmlElement(name = "Business_Sub_Process_Parameters")
    protected BusinessSubProcessParametersType businessSubProcessParameters;
    @XmlElement(name = "Position_Costing_Allocation_Assignment_Data")
    protected AssignCostingAllocationEventDataType positionCostingAllocationAssignmentData;

    /**
     * Gets the value of the businessSubProcessParameters property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessSubProcessParametersType }
     *     
     */
    public BusinessSubProcessParametersType getBusinessSubProcessParameters() {
        return businessSubProcessParameters;
    }

    /**
     * Sets the value of the businessSubProcessParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessSubProcessParametersType }
     *     
     */
    public void setBusinessSubProcessParameters(BusinessSubProcessParametersType value) {
        this.businessSubProcessParameters = value;
    }

    /**
     * Gets the value of the positionCostingAllocationAssignmentData property.
     * 
     * @return
     *     possible object is
     *     {@link AssignCostingAllocationEventDataType }
     *     
     */
    public AssignCostingAllocationEventDataType getPositionCostingAllocationAssignmentData() {
        return positionCostingAllocationAssignmentData;
    }

    /**
     * Sets the value of the positionCostingAllocationAssignmentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignCostingAllocationEventDataType }
     *     
     */
    public void setPositionCostingAllocationAssignmentData(AssignCostingAllocationEventDataType value) {
        this.positionCostingAllocationAssignmentData = value;
    }

}
