//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Wrapper element for Assign Position Organization business process.
 * 
 * <p>Java class for Assign_Position_Organization_Event_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Position_Organization_Event_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Company_Assignments_Reference" type="{urn:com.workday/bsvc}CompanyObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Cost_Center_Assignments_Reference" type="{urn:com.workday/bsvc}Cost_CenterObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Region_Assignments_Reference" type="{urn:com.workday/bsvc}RegionObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Custom_Organization_Assignment_Data" type="{urn:com.workday/bsvc}Custom_Organization_Assignment_DataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Fund_Assignments_Reference" type="{urn:com.workday/bsvc}FundObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Grant_Assignments_Reference" type="{urn:com.workday/bsvc}GrantObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Program_Assignments_Reference" type="{urn:com.workday/bsvc}ProgramObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Business_Unit_Assignments_Reference" type="{urn:com.workday/bsvc}Business_UnitObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Gift_Assignments_Reference" type="{urn:com.workday/bsvc}GiftObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Position_Organization_Event_DataType", propOrder = {
    "companyAssignmentsReference",
    "costCenterAssignmentsReference",
    "regionAssignmentsReference",
    "customOrganizationAssignmentData",
    "fundAssignmentsReference",
    "grantAssignmentsReference",
    "programAssignmentsReference",
    "businessUnitAssignmentsReference",
    "giftAssignmentsReference"
})
public class AssignPositionOrganizationEventDataType {

    @XmlElement(name = "Company_Assignments_Reference")
    protected List<CompanyObjectType> companyAssignmentsReference;
    @XmlElement(name = "Cost_Center_Assignments_Reference")
    protected List<CostCenterObjectType> costCenterAssignmentsReference;
    @XmlElement(name = "Region_Assignments_Reference")
    protected List<RegionObjectType> regionAssignmentsReference;
    @XmlElement(name = "Custom_Organization_Assignment_Data")
    protected List<CustomOrganizationAssignmentDataType> customOrganizationAssignmentData;
    @XmlElement(name = "Fund_Assignments_Reference")
    protected List<FundObjectType> fundAssignmentsReference;
    @XmlElement(name = "Grant_Assignments_Reference")
    protected List<GrantObjectType> grantAssignmentsReference;
    @XmlElement(name = "Program_Assignments_Reference")
    protected List<ProgramObjectType> programAssignmentsReference;
    @XmlElement(name = "Business_Unit_Assignments_Reference")
    protected List<BusinessUnitObjectType> businessUnitAssignmentsReference;
    @XmlElement(name = "Gift_Assignments_Reference")
    protected List<GiftObjectType> giftAssignmentsReference;

    /**
     * Gets the value of the companyAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the companyAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompanyAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompanyObjectType }
     * 
     * 
     */
    public List<CompanyObjectType> getCompanyAssignmentsReference() {
        if (companyAssignmentsReference == null) {
            companyAssignmentsReference = new ArrayList<CompanyObjectType>();
        }
        return this.companyAssignmentsReference;
    }

    /**
     * Gets the value of the costCenterAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costCenterAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostCenterAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CostCenterObjectType }
     * 
     * 
     */
    public List<CostCenterObjectType> getCostCenterAssignmentsReference() {
        if (costCenterAssignmentsReference == null) {
            costCenterAssignmentsReference = new ArrayList<CostCenterObjectType>();
        }
        return this.costCenterAssignmentsReference;
    }

    /**
     * Gets the value of the regionAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegionObjectType }
     * 
     * 
     */
    public List<RegionObjectType> getRegionAssignmentsReference() {
        if (regionAssignmentsReference == null) {
            regionAssignmentsReference = new ArrayList<RegionObjectType>();
        }
        return this.regionAssignmentsReference;
    }

    /**
     * Gets the value of the customOrganizationAssignmentData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customOrganizationAssignmentData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomOrganizationAssignmentData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomOrganizationAssignmentDataType }
     * 
     * 
     */
    public List<CustomOrganizationAssignmentDataType> getCustomOrganizationAssignmentData() {
        if (customOrganizationAssignmentData == null) {
            customOrganizationAssignmentData = new ArrayList<CustomOrganizationAssignmentDataType>();
        }
        return this.customOrganizationAssignmentData;
    }

    /**
     * Gets the value of the fundAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fundAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFundAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FundObjectType }
     * 
     * 
     */
    public List<FundObjectType> getFundAssignmentsReference() {
        if (fundAssignmentsReference == null) {
            fundAssignmentsReference = new ArrayList<FundObjectType>();
        }
        return this.fundAssignmentsReference;
    }

    /**
     * Gets the value of the grantAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grantAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrantAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrantObjectType }
     * 
     * 
     */
    public List<GrantObjectType> getGrantAssignmentsReference() {
        if (grantAssignmentsReference == null) {
            grantAssignmentsReference = new ArrayList<GrantObjectType>();
        }
        return this.grantAssignmentsReference;
    }

    /**
     * Gets the value of the programAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the programAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgramAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProgramObjectType }
     * 
     * 
     */
    public List<ProgramObjectType> getProgramAssignmentsReference() {
        if (programAssignmentsReference == null) {
            programAssignmentsReference = new ArrayList<ProgramObjectType>();
        }
        return this.programAssignmentsReference;
    }

    /**
     * Gets the value of the businessUnitAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the businessUnitAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBusinessUnitAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessUnitObjectType }
     * 
     * 
     */
    public List<BusinessUnitObjectType> getBusinessUnitAssignmentsReference() {
        if (businessUnitAssignmentsReference == null) {
            businessUnitAssignmentsReference = new ArrayList<BusinessUnitObjectType>();
        }
        return this.businessUnitAssignmentsReference;
    }

    /**
     * Gets the value of the giftAssignmentsReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the giftAssignmentsReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGiftAssignmentsReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GiftObjectType }
     * 
     * 
     */
    public List<GiftObjectType> getGiftAssignmentsReference() {
        if (giftAssignmentsReference == null) {
            giftAssignmentsReference = new ArrayList<GiftObjectType>();
        }
        return this.giftAssignmentsReference;
    }

}
