//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the costing allocation for the position.
 * 
 * <p>Java class for Assign_Costing_Allocation_Event_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Costing_Allocation_Event_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Costing_Override_Data" type="{urn:com.workday/bsvc}Costing_Allocation_Interval_DataType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="Costing_Allocation_Level_Reference" type="{urn:com.workday/bsvc}Costing_Allocation_LevelObjectType"/&gt;
 *         &lt;element name="Costing_Allocation_Earning_Reference" type="{urn:com.workday/bsvc}Earning__All_ObjectType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Costing_Allocation_Event_DataType", propOrder = {
    "costingOverrideData",
    "costingAllocationLevelReference",
    "costingAllocationEarningReference"
})
public class AssignCostingAllocationEventDataType {

    @XmlElement(name = "Costing_Override_Data", required = true)
    protected List<CostingAllocationIntervalDataType> costingOverrideData;
    @XmlElement(name = "Costing_Allocation_Level_Reference", required = true)
    protected CostingAllocationLevelObjectType costingAllocationLevelReference;
    @XmlElement(name = "Costing_Allocation_Earning_Reference")
    protected EarningAllObjectType costingAllocationEarningReference;

    /**
     * Gets the value of the costingOverrideData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costingOverrideData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostingOverrideData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CostingAllocationIntervalDataType }
     * 
     * 
     */
    public List<CostingAllocationIntervalDataType> getCostingOverrideData() {
        if (costingOverrideData == null) {
            costingOverrideData = new ArrayList<CostingAllocationIntervalDataType>();
        }
        return this.costingOverrideData;
    }

    /**
     * Gets the value of the costingAllocationLevelReference property.
     * 
     * @return
     *     possible object is
     *     {@link CostingAllocationLevelObjectType }
     *     
     */
    public CostingAllocationLevelObjectType getCostingAllocationLevelReference() {
        return costingAllocationLevelReference;
    }

    /**
     * Sets the value of the costingAllocationLevelReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostingAllocationLevelObjectType }
     *     
     */
    public void setCostingAllocationLevelReference(CostingAllocationLevelObjectType value) {
        this.costingAllocationLevelReference = value;
    }

    /**
     * Gets the value of the costingAllocationEarningReference property.
     * 
     * @return
     *     possible object is
     *     {@link EarningAllObjectType }
     *     
     */
    public EarningAllObjectType getCostingAllocationEarningReference() {
        return costingAllocationEarningReference;
    }

    /**
     * Sets the value of the costingAllocationEarningReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EarningAllObjectType }
     *     
     */
    public void setCostingAllocationEarningReference(EarningAllObjectType value) {
        this.costingAllocationEarningReference = value;
    }

}
