//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Wrapper element for Assign Pay Group for Position Restriction when it is a sub business process to Create Position.
 * 
 * <p>Java class for Assign_Pay_Group_for_Position_Restriction_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Pay_Group_for_Position_Restriction_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Pay_Group_Reference" type="{urn:com.workday/bsvc}Pay_GroupObjectType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Pay_Group_for_Position_Restriction_DataType", propOrder = {
    "payGroupReference"
})
public class AssignPayGroupForPositionRestrictionDataType {

    @XmlElement(name = "Pay_Group_Reference", required = true)
    protected PayGroupObjectType payGroupReference;

    /**
     * Gets the value of the payGroupReference property.
     * 
     * @return
     *     possible object is
     *     {@link PayGroupObjectType }
     *     
     */
    public PayGroupObjectType getPayGroupReference() {
        return payGroupReference;
    }

    /**
     * Sets the value of the payGroupReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayGroupObjectType }
     *     
     */
    public void setPayGroupReference(PayGroupObjectType value) {
        this.payGroupReference = value;
    }

}
