//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data element that contains the compensation default information.  If a section is to be provided, it must be provided fully as it will fully replace the current default compensation.
 * 
 * <p>Java class for Compensation_Default_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Compensation_Default_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Primary_Compensation_Basis" minOccurs="0"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                 &lt;totalDigits value="26"/&gt;
 *                 &lt;fractionDigits value="6"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Primary_Compensation_Basis_Amount_Change" minOccurs="0"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                 &lt;totalDigits value="26"/&gt;
 *                 &lt;fractionDigits value="6"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Primary_Compensation_Basis_Percent_Change" minOccurs="0"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *                 &lt;totalDigits value="21"/&gt;
 *                 &lt;fractionDigits value="6"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Guidelines_Data" type="{urn:com.workday/bsvc}Compensatable_Default_Guidelines_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Pay_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Base_Pay_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Unit_Salary_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Salary_Unit_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Allowance_Plan_Non-Unit_Based_Data" type="{urn:com.workday/bsvc}Proposed_Allowance_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Allowance_Plan_Unit_Based_Data" type="{urn:com.workday/bsvc}Proposed_Allowance_Unit_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Bonus_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Bonus_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Merit_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Merit_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Commission_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Commission_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Stock_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Stock_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Period_Salary_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Period_Salary_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *         &lt;element name="Calculated_Plan_Data" type="{urn:com.workday/bsvc}Proposed_Calculated_Plan_Assignment_Container_DataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Compensation_Default_DataType", propOrder = {
    "primaryCompensationBasis",
    "primaryCompensationBasisAmountChange",
    "primaryCompensationBasisPercentChange",
    "guidelinesData",
    "payPlanData",
    "unitSalaryPlanData",
    "allowancePlanNonUnitBasedData",
    "allowancePlanUnitBasedData",
    "bonusPlanData",
    "meritPlanData",
    "commissionPlanData",
    "stockPlanData",
    "periodSalaryPlanData",
    "calculatedPlanData"
})
public class CompensationDefaultDataType {

    @XmlElement(name = "Primary_Compensation_Basis")
    protected BigDecimal primaryCompensationBasis;
    @XmlElement(name = "Primary_Compensation_Basis_Amount_Change")
    protected BigDecimal primaryCompensationBasisAmountChange;
    @XmlElement(name = "Primary_Compensation_Basis_Percent_Change")
    protected BigDecimal primaryCompensationBasisPercentChange;
    @XmlElement(name = "Guidelines_Data")
    protected CompensatableDefaultGuidelinesDataType guidelinesData;
    @XmlElement(name = "Pay_Plan_Data")
    protected ProposedBasePayPlanAssignmentContainerDataType payPlanData;
    @XmlElement(name = "Unit_Salary_Plan_Data")
    protected ProposedSalaryUnitPlanAssignmentContainerDataType unitSalaryPlanData;
    @XmlElement(name = "Allowance_Plan_Non-Unit_Based_Data")
    protected ProposedAllowancePlanAssignmentContainerDataType allowancePlanNonUnitBasedData;
    @XmlElement(name = "Allowance_Plan_Unit_Based_Data")
    protected ProposedAllowanceUnitPlanAssignmentContainerDataType allowancePlanUnitBasedData;
    @XmlElement(name = "Bonus_Plan_Data")
    protected ProposedBonusPlanAssignmentContainerDataType bonusPlanData;
    @XmlElement(name = "Merit_Plan_Data")
    protected ProposedMeritPlanAssignmentContainerDataType meritPlanData;
    @XmlElement(name = "Commission_Plan_Data")
    protected ProposedCommissionPlanAssignmentContainerDataType commissionPlanData;
    @XmlElement(name = "Stock_Plan_Data")
    protected ProposedStockPlanAssignmentContainerDataType stockPlanData;
    @XmlElement(name = "Period_Salary_Plan_Data")
    protected ProposedPeriodSalaryPlanAssignmentContainerDataType periodSalaryPlanData;
    @XmlElement(name = "Calculated_Plan_Data")
    protected ProposedCalculatedPlanAssignmentContainerDataType calculatedPlanData;

    /**
     * Gets the value of the primaryCompensationBasis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrimaryCompensationBasis() {
        return primaryCompensationBasis;
    }

    /**
     * Sets the value of the primaryCompensationBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrimaryCompensationBasis(BigDecimal value) {
        this.primaryCompensationBasis = value;
    }

    /**
     * Gets the value of the primaryCompensationBasisAmountChange property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrimaryCompensationBasisAmountChange() {
        return primaryCompensationBasisAmountChange;
    }

    /**
     * Sets the value of the primaryCompensationBasisAmountChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrimaryCompensationBasisAmountChange(BigDecimal value) {
        this.primaryCompensationBasisAmountChange = value;
    }

    /**
     * Gets the value of the primaryCompensationBasisPercentChange property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPrimaryCompensationBasisPercentChange() {
        return primaryCompensationBasisPercentChange;
    }

    /**
     * Sets the value of the primaryCompensationBasisPercentChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPrimaryCompensationBasisPercentChange(BigDecimal value) {
        this.primaryCompensationBasisPercentChange = value;
    }

    /**
     * Gets the value of the guidelinesData property.
     * 
     * @return
     *     possible object is
     *     {@link CompensatableDefaultGuidelinesDataType }
     *     
     */
    public CompensatableDefaultGuidelinesDataType getGuidelinesData() {
        return guidelinesData;
    }

    /**
     * Sets the value of the guidelinesData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensatableDefaultGuidelinesDataType }
     *     
     */
    public void setGuidelinesData(CompensatableDefaultGuidelinesDataType value) {
        this.guidelinesData = value;
    }

    /**
     * Gets the value of the payPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedBasePayPlanAssignmentContainerDataType }
     *     
     */
    public ProposedBasePayPlanAssignmentContainerDataType getPayPlanData() {
        return payPlanData;
    }

    /**
     * Sets the value of the payPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedBasePayPlanAssignmentContainerDataType }
     *     
     */
    public void setPayPlanData(ProposedBasePayPlanAssignmentContainerDataType value) {
        this.payPlanData = value;
    }

    /**
     * Gets the value of the unitSalaryPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedSalaryUnitPlanAssignmentContainerDataType }
     *     
     */
    public ProposedSalaryUnitPlanAssignmentContainerDataType getUnitSalaryPlanData() {
        return unitSalaryPlanData;
    }

    /**
     * Sets the value of the unitSalaryPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedSalaryUnitPlanAssignmentContainerDataType }
     *     
     */
    public void setUnitSalaryPlanData(ProposedSalaryUnitPlanAssignmentContainerDataType value) {
        this.unitSalaryPlanData = value;
    }

    /**
     * Gets the value of the allowancePlanNonUnitBasedData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedAllowancePlanAssignmentContainerDataType }
     *     
     */
    public ProposedAllowancePlanAssignmentContainerDataType getAllowancePlanNonUnitBasedData() {
        return allowancePlanNonUnitBasedData;
    }

    /**
     * Sets the value of the allowancePlanNonUnitBasedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedAllowancePlanAssignmentContainerDataType }
     *     
     */
    public void setAllowancePlanNonUnitBasedData(ProposedAllowancePlanAssignmentContainerDataType value) {
        this.allowancePlanNonUnitBasedData = value;
    }

    /**
     * Gets the value of the allowancePlanUnitBasedData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedAllowanceUnitPlanAssignmentContainerDataType }
     *     
     */
    public ProposedAllowanceUnitPlanAssignmentContainerDataType getAllowancePlanUnitBasedData() {
        return allowancePlanUnitBasedData;
    }

    /**
     * Sets the value of the allowancePlanUnitBasedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedAllowanceUnitPlanAssignmentContainerDataType }
     *     
     */
    public void setAllowancePlanUnitBasedData(ProposedAllowanceUnitPlanAssignmentContainerDataType value) {
        this.allowancePlanUnitBasedData = value;
    }

    /**
     * Gets the value of the bonusPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedBonusPlanAssignmentContainerDataType }
     *     
     */
    public ProposedBonusPlanAssignmentContainerDataType getBonusPlanData() {
        return bonusPlanData;
    }

    /**
     * Sets the value of the bonusPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedBonusPlanAssignmentContainerDataType }
     *     
     */
    public void setBonusPlanData(ProposedBonusPlanAssignmentContainerDataType value) {
        this.bonusPlanData = value;
    }

    /**
     * Gets the value of the meritPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedMeritPlanAssignmentContainerDataType }
     *     
     */
    public ProposedMeritPlanAssignmentContainerDataType getMeritPlanData() {
        return meritPlanData;
    }

    /**
     * Sets the value of the meritPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedMeritPlanAssignmentContainerDataType }
     *     
     */
    public void setMeritPlanData(ProposedMeritPlanAssignmentContainerDataType value) {
        this.meritPlanData = value;
    }

    /**
     * Gets the value of the commissionPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedCommissionPlanAssignmentContainerDataType }
     *     
     */
    public ProposedCommissionPlanAssignmentContainerDataType getCommissionPlanData() {
        return commissionPlanData;
    }

    /**
     * Sets the value of the commissionPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedCommissionPlanAssignmentContainerDataType }
     *     
     */
    public void setCommissionPlanData(ProposedCommissionPlanAssignmentContainerDataType value) {
        this.commissionPlanData = value;
    }

    /**
     * Gets the value of the stockPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedStockPlanAssignmentContainerDataType }
     *     
     */
    public ProposedStockPlanAssignmentContainerDataType getStockPlanData() {
        return stockPlanData;
    }

    /**
     * Sets the value of the stockPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedStockPlanAssignmentContainerDataType }
     *     
     */
    public void setStockPlanData(ProposedStockPlanAssignmentContainerDataType value) {
        this.stockPlanData = value;
    }

    /**
     * Gets the value of the periodSalaryPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedPeriodSalaryPlanAssignmentContainerDataType }
     *     
     */
    public ProposedPeriodSalaryPlanAssignmentContainerDataType getPeriodSalaryPlanData() {
        return periodSalaryPlanData;
    }

    /**
     * Sets the value of the periodSalaryPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedPeriodSalaryPlanAssignmentContainerDataType }
     *     
     */
    public void setPeriodSalaryPlanData(ProposedPeriodSalaryPlanAssignmentContainerDataType value) {
        this.periodSalaryPlanData = value;
    }

    /**
     * Gets the value of the calculatedPlanData property.
     * 
     * @return
     *     possible object is
     *     {@link ProposedCalculatedPlanAssignmentContainerDataType }
     *     
     */
    public ProposedCalculatedPlanAssignmentContainerDataType getCalculatedPlanData() {
        return calculatedPlanData;
    }

    /**
     * Sets the value of the calculatedPlanData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProposedCalculatedPlanAssignmentContainerDataType }
     *     
     */
    public void setCalculatedPlanData(ProposedCalculatedPlanAssignmentContainerDataType value) {
        this.calculatedPlanData = value;
    }

}
