//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Allows user to add new or delete existing custom organizations. 
 * If a new Unique custom organization is added - the prior org of that type will be deleted. (The old organization does not have to be submitted with delete flag true). 
 * If a new non-Unique custom organization is added - the existing org(s) of that type will be retained (unless they are sent with the delete flag true). 
 * Custom Organizations that are not being modified do not need to be submitted.
 * 
 * <p>Java class for Custom_Organization_Assignment_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Custom_Organization_Assignment_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Custom_Organization_Assignment_Reference" type="{urn:com.workday/bsvc}Custom_OrganizationObjectType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Delete" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Custom_Organization_Assignment_DataType", propOrder = {
    "customOrganizationAssignmentReference"
})
public class CustomOrganizationAssignmentDataType {

    @XmlElement(name = "Custom_Organization_Assignment_Reference", required = true)
    protected CustomOrganizationObjectType customOrganizationAssignmentReference;
    @XmlAttribute(name = "Delete", namespace = "urn:com.workday/bsvc")
    protected Boolean delete;

    /**
     * Gets the value of the customOrganizationAssignmentReference property.
     * 
     * @return
     *     possible object is
     *     {@link CustomOrganizationObjectType }
     *     
     */
    public CustomOrganizationObjectType getCustomOrganizationAssignmentReference() {
        return customOrganizationAssignmentReference;
    }

    /**
     * Sets the value of the customOrganizationAssignmentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomOrganizationObjectType }
     *     
     */
    public void setCustomOrganizationAssignmentReference(CustomOrganizationObjectType value) {
        this.customOrganizationAssignmentReference = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDelete(Boolean value) {
        this.delete = value;
    }

}
