//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Wrapper element for the Assign Organizations to Position sub business process.
 * If this element is submitted (Auto or Manual) as part of a Staffing event and the Position_Organization_Assignment  wrapper is not submitted, then the position's organization assignments will default from the supervisory organization.
 * 
 * <p>Java class for Edit_Assign_Position_Organization_Sub_Business_ProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Edit_Assign_Position_Organization_Sub_Business_ProcessType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Business_Sub_Process_Parameters" type="{urn:com.workday/bsvc}Business_Sub_Process_ParametersType" minOccurs="0"/&gt;
 *         &lt;element name="Position_Organization_Assignments_Data" type="{urn:com.workday/bsvc}Assign_Position_Organization_Event_DataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Edit_Assign_Position_Organization_Sub_Business_ProcessType", propOrder = {
    "businessSubProcessParameters",
    "positionOrganizationAssignmentsData"
})
public class EditAssignPositionOrganizationSubBusinessProcessType {

    @XmlElement(name = "Business_Sub_Process_Parameters")
    protected BusinessSubProcessParametersType businessSubProcessParameters;
    @XmlElement(name = "Position_Organization_Assignments_Data")
    protected AssignPositionOrganizationEventDataType positionOrganizationAssignmentsData;

    /**
     * Gets the value of the businessSubProcessParameters property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessSubProcessParametersType }
     *     
     */
    public BusinessSubProcessParametersType getBusinessSubProcessParameters() {
        return businessSubProcessParameters;
    }

    /**
     * Sets the value of the businessSubProcessParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessSubProcessParametersType }
     *     
     */
    public void setBusinessSubProcessParameters(BusinessSubProcessParametersType value) {
        this.businessSubProcessParameters = value;
    }

    /**
     * Gets the value of the positionOrganizationAssignmentsData property.
     * 
     * @return
     *     possible object is
     *     {@link AssignPositionOrganizationEventDataType }
     *     
     */
    public AssignPositionOrganizationEventDataType getPositionOrganizationAssignmentsData() {
        return positionOrganizationAssignmentsData;
    }

    /**
     * Sets the value of the positionOrganizationAssignmentsData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignPositionOrganizationEventDataType }
     *     
     */
    public void setPositionOrganizationAssignmentsData(AssignPositionOrganizationEventDataType value) {
        this.positionOrganizationAssignmentsData = value;
    }

}
