//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Element containing the language ability type and proficiency for a Job Profile Language Qualfication language.
 * 
 * <p>Java class for Language_Ability_Profile_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Language_Ability_Profile_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Language_Ability_Type_Reference" type="{urn:com.workday/bsvc}Language_Ability_TypeObjectType"/&gt;
 *         &lt;element name="Language_Proficiency_Reference" type="{urn:com.workday/bsvc}Language_ProficiencyObjectType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Language_Ability_Profile_DataType", propOrder = {
    "languageAbilityTypeReference",
    "languageProficiencyReference"
})
public class LanguageAbilityProfileDataType {

    @XmlElement(name = "Language_Ability_Type_Reference", required = true)
    protected LanguageAbilityTypeObjectType languageAbilityTypeReference;
    @XmlElement(name = "Language_Proficiency_Reference")
    protected LanguageProficiencyObjectType languageProficiencyReference;

    /**
     * Gets the value of the languageAbilityTypeReference property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageAbilityTypeObjectType }
     *     
     */
    public LanguageAbilityTypeObjectType getLanguageAbilityTypeReference() {
        return languageAbilityTypeReference;
    }

    /**
     * Sets the value of the languageAbilityTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageAbilityTypeObjectType }
     *     
     */
    public void setLanguageAbilityTypeReference(LanguageAbilityTypeObjectType value) {
        this.languageAbilityTypeReference = value;
    }

    /**
     * Gets the value of the languageProficiencyReference property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageProficiencyObjectType }
     *     
     */
    public LanguageProficiencyObjectType getLanguageProficiencyReference() {
        return languageProficiencyReference;
    }

    /**
     * Sets the value of the languageProficiencyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageProficiencyObjectType }
     *     
     */
    public void setLanguageProficiencyReference(LanguageProficiencyObjectType value) {
        this.languageProficiencyReference = value;
    }

}
