//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:com.workday/bsvc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, 
xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "bsvc", namespaceURI = "urn:com.workday/bsvc")})
package com.polus.fibicomp.manpowerintegration.dto.recruiting;
