//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 01:02:19 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.recruiting;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Wrapper for restriction data for openings for all staffing models.
 * 
 * <p>Java class for Position_Group_Restriction_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Position_Group_Restriction_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Availability_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Earliest_Hire_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Job_Family_Reference" type="{urn:com.workday/bsvc}Job_Family_BaseObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Job_Profile_Reference" type="{urn:com.workday/bsvc}Job_ProfileObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Location_Reference" type="{urn:com.workday/bsvc}LocationObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Worker_Type_Reference" type="{urn:com.workday/bsvc}Worker_TypeObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Time_Type_Reference" type="{urn:com.workday/bsvc}Position_Time_TypeObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Position_Worker_Type_Reference" type="{urn:com.workday/bsvc}Position_Worker_TypeObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position_Group_Restriction_DataType", propOrder = {
    "availabilityDate",
    "earliestHireDate",
    "jobFamilyReference",
    "jobProfileReference",
    "locationReference",
    "workerTypeReference",
    "timeTypeReference",
    "positionWorkerTypeReference"
})
public class PositionGroupRestrictionDataType {

    @XmlElement(name = "Availability_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar availabilityDate;
    @XmlElement(name = "Earliest_Hire_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar earliestHireDate;
    @XmlElement(name = "Job_Family_Reference")
    protected List<JobFamilyBaseObjectType> jobFamilyReference;
    @XmlElement(name = "Job_Profile_Reference")
    protected List<JobProfileObjectType> jobProfileReference;
    @XmlElement(name = "Location_Reference")
    protected List<LocationObjectType> locationReference;
    @XmlElement(name = "Worker_Type_Reference")
    protected WorkerTypeObjectType workerTypeReference;
    @XmlElement(name = "Time_Type_Reference")
    protected PositionTimeTypeObjectType timeTypeReference;
    @XmlElement(name = "Position_Worker_Type_Reference")
    protected List<PositionWorkerTypeObjectType> positionWorkerTypeReference;

    /**
     * Gets the value of the availabilityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvailabilityDate() {
        return availabilityDate;
    }

    /**
     * Sets the value of the availabilityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailabilityDate(XMLGregorianCalendar value) {
        this.availabilityDate = value;
    }

    /**
     * Gets the value of the earliestHireDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEarliestHireDate() {
        return earliestHireDate;
    }

    /**
     * Sets the value of the earliestHireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEarliestHireDate(XMLGregorianCalendar value) {
        this.earliestHireDate = value;
    }

    /**
     * Gets the value of the jobFamilyReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobFamilyReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobFamilyReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobFamilyBaseObjectType }
     * 
     * 
     */
    public List<JobFamilyBaseObjectType> getJobFamilyReference() {
        if (jobFamilyReference == null) {
            jobFamilyReference = new ArrayList<JobFamilyBaseObjectType>();
        }
        return this.jobFamilyReference;
    }

    /**
     * Gets the value of the jobProfileReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobProfileReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobProfileReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobProfileObjectType }
     * 
     * 
     */
    public List<JobProfileObjectType> getJobProfileReference() {
        if (jobProfileReference == null) {
            jobProfileReference = new ArrayList<JobProfileObjectType>();
        }
        return this.jobProfileReference;
    }

    /**
     * Gets the value of the locationReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationObjectType }
     * 
     * 
     */
    public List<LocationObjectType> getLocationReference() {
        if (locationReference == null) {
            locationReference = new ArrayList<LocationObjectType>();
        }
        return this.locationReference;
    }

    /**
     * Gets the value of the workerTypeReference property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerTypeObjectType }
     *     
     */
    public WorkerTypeObjectType getWorkerTypeReference() {
        return workerTypeReference;
    }

    /**
     * Sets the value of the workerTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerTypeObjectType }
     *     
     */
    public void setWorkerTypeReference(WorkerTypeObjectType value) {
        this.workerTypeReference = value;
    }

    /**
     * Gets the value of the timeTypeReference property.
     * 
     * @return
     *     possible object is
     *     {@link PositionTimeTypeObjectType }
     *     
     */
    public PositionTimeTypeObjectType getTimeTypeReference() {
        return timeTypeReference;
    }

    /**
     * Sets the value of the timeTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionTimeTypeObjectType }
     *     
     */
    public void setTimeTypeReference(PositionTimeTypeObjectType value) {
        this.timeTypeReference = value;
    }

    /**
     * Gets the value of the positionWorkerTypeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionWorkerTypeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionWorkerTypeReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PositionWorkerTypeObjectType }
     * 
     * 
     */
    public List<PositionWorkerTypeObjectType> getPositionWorkerTypeReference() {
        if (positionWorkerTypeReference == null) {
            positionWorkerTypeReference = new ArrayList<PositionWorkerTypeObjectType>();
        }
        return this.positionWorkerTypeReference;
    }

}
