
DROP PROCEDURE IF EXISTS GET_COI_DISCL_REVIEW_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_GENERAL_DETAILS;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;

DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_RELATIONS;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE.sql;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP FUNCTION IF EXISTS FN_INT_CAN_CREATE_PROP_DISCL;

\. ./Procedures/GET_COI_DISCL_REVIEW_DETAILS.sql
\. ./Procedures/GET_COI_DISCL_GENERAL_DETAILS.sql
\. ./Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql


\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_DISCLOSURE_PROJECTS.sql
\. ./Procedures/GET_DISCLOSURE_RELATIONS.sql
\. ./Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Procedures/FN_INT_CAN_CREATE_PROP_DISCL.sql
