

DROP PROCEDURE IF EXISTS CLENSEMATCH_ENT_INFO_BY_DUNS;
DROP PROCEDURE IF EXISTS COI_DISCL_GENERATE_JSON_PROJECT_DETAILS;
DROP PROCEDURE IF EXISTS COI_DISCL_VOID_DEACTIVATED_PROJECT;
DROP PROCEDURE IF EXISTS COI_INT_KC_SPON_ORG_RESPONSE;
DROP PROCEDURE IF EXISTS GENERATE_ATTACHMENT_NUMBER;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_ENTITY_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_OPA_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_COUNT;
DROP PROCEDURE IF EXISTS GET_ENTITY_DASHBOARD_DYNAMIC_DATA;
DROP PROCEDURE IF EXISTS GET_OPA_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_INFO;
DROP PROCEDURE IF EXISTS GET_ENTITY_TAB_STATUS;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP PROCEDURE IF EXISTS UPD_DOCS_WITH_ORG_ENTITY;


\. ./Procedures/CLENSEMATCH_ENT_INFO_BY_DUNS.sql
\. ./Procedures/COI_DISCL_GENERATE_JSON_PROJECT_DETAILS.sql
\. ./Procedures/COI_DISCL_VOID_DEACTIVATED_PROJECT.sql
\. ./Procedures/COI_INT_KC_SPON_ORG_RESPONSE.sql
\. ./Procedures/GENERATE_ATTACHMENT_NUMBER.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_ENTITY_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_COI_OPA_DASHBOARD.sql
\. ./Procedures/GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_COUNT.sql
\. ./Procedures/GET_ENTITY_DASHBOARD_DYNAMIC_DATA.sql
\. ./Procedures/GET_OPA_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_PERSON_ENTITY_INFO.sql
\. ./Procedures/GET_ENTITY_TAB_STATUS.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Procedures/UPD_DOCS_WITH_ORG_ENTITY.sql

