
ALTER TABLE entity 
ADD COLUMN ORIGINAL_ENTITY_ID INT NULL AFTER IS_DUNS_MATCHED;

ALTER TABLE entity 
ADD COLUMN DOCUMENT_STATUS_TYPE_CODE VARCHAR(3) NULL AFTER OPERATING_STATUS_TYPE_CODE;

ALTER TABLE entity 
ADD INDEX ENTITY_FK7_idx (DOCUMENT_STATUS_TYPE_CODE ASC) VISIBLE;
ALTER TABLE entity 
ADD CONSTRAINT ENTITY_FK7
  FOREIGN KEY (DOCUMENT_STATUS_TYPE_CODE)
  REFERENCES entity_document_status_type (DOCUMENT_STATUS_TYPE_CODE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

truncate entity_action_log;
set foreign_key_checks = 0;
truncate entity_action_type;
set foreign_key_checks = 1;
