
ALTER TABLE entity 
ADD COLUMN ORIGINAL_ENTITY_ID INT NULL AFTER IS_DUNS_MATCHED;

ALTER TABLE entity 
ADD COLUMN DOCUMENT_STATUS_TYPE_CODE VARCHAR(3) NULL AFTER OPERATING_STATUS_TYPE_CODE;

ALTER TABLE entity 
ADD INDEX ENTITY_FK7_idx (DOCUMENT_STATUS_TYPE_CODE ASC) VISIBLE;
ALTER TABLE entity 
ADD CONSTRAINT ENTITY_FK7
  FOREIGN KEY (DOCUMENT_STATUS_TYPE_CODE)
  REFERENCES entity_document_status_type (DOCUMENT_STATUS_TYPE_CODE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

truncate entity_action_log;
set foreign_key_checks = 0;
truncate entity_action_type;
set foreign_key_checks = 1;

ALTER TABLE `coi_disclosure`
ADD COLUMN `REMARK` VARCHAR(225) NULL;

ALTER TABLE `coi_discl_projects`
ADD COLUMN `PROJECT_SNAPSHOT` JSON NULL;


ALTER TABLE attachments
ADD COLUMN VERSION_NUMBER INT;

ALTER TABLE attachments
ADD COLUMN ATTACHMENT_NUMBER INT;

DROP INDEX `ENTITY_SPONSOR_INFO_FK3_idx` ON `ENTITY_SPONSOR_INFO`;

ALTER TABLE `ENTITY_SPONSOR_INFO` 
ADD INDEX `ENTITY_SPONSOR_INFO_FK3_idx` (`SPONSOR_TYPE_CODE` ASC) VISIBLE;

ALTER TABLE `ENTITY_SPONSOR_INFO` 
	ADD CONSTRAINT `ENTITY_SPONSOR_INFO_FK3`
	FOREIGN KEY (`SPONSOR_TYPE_CODE`)
	REFERENCES `SPONSOR_TYPE` (`SPONSOR_TYPE_CODE`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION;
