DELIMITER //
CREATE PROCEDURE `COI_SYNC_REMOVE_DEACTIVATED_PROJECTS`(
	AV_MODULE_CODE          INT,
	AV_MODULE_ITEM_KEY		VARCHAR(100)
)
BEGIN

	/* UPDATE COI_DISCLOSURE T1
	INNER JOIN COI_DISCL_PROJECTS T2 ON T2.DISCLOSURE_ID = T1.DISCLOSURE_ID
	SET T1.DISPOSITION_STATUS_CODE = 2
	WHERE T1.FCOI_TYPE_CODE = 2
	AND T2.MODULE_CODE = AV_MODULE_CODE
	AND T2.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY;

	*/

	DELETE T4, T3, T2, T1
        FROM COI_DISCL_PROJECTS T1
        LEFT JOIN COI_DISCL_PROJECT_ENTITY_REL T2 ON T2.COI_DISCL_PROJECTS_ID = T1.COI_DISCL_PROJECTS_ID
        LEFT JOIN DISCL_COMMENT T3 ON T3.SUB_MODULE_ITEM_KEY = T2.COI_DISCL_PROJECT_ENTITY_REL_ID
            AND (T3.COMPONENT_TYPE_CODE = '1' OR T3.COMPONENT_TYPE_CODE = '6')
        LEFT JOIN COI_CONFLICT_HISTORY T4 on T4.COI_DISCL_PROJECT_ENTITY_REL_ID = T2.COI_DISCL_PROJECT_ENTITY_REL_ID
        WHERE T1.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY AND T1.MODULE_CODE = AV_MODULE_CODE;

END
//