#server:
#  port: 9090
#
#spring:
# cloud:
#   gateway:
#     routes:
#       - id: fcoi
#         uri: lb://fcoi
#         predicates:
#           - Path=/fcoi/**
#         filters:
#           - AuthenticationFilter
#
#       - id: auth-service
#         uri: lb://auth-service
#         predicates:
#           - Path=/auth/**
#           
#       - id: fcoiv1
#         uri: lb://fcoi
#         predicates:
#           - Path=/**
#         filters:
#           - AuthenticationFilter           
#
# application:
#   name: API-GATEWAY
#
#eureka:
#  client:
#    service-url:
#      defaultZone : ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
