DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_REVIEWER_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST_COUNT;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_SFI_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GENERATE_ATTACHMENT_NUMBER;
DROP PROCEDURE IF EXISTS COI_SYNC_DISCLOSURE_RISK;
DROP PROCEDURE IF EXISTS PROC_SYNC_OPA_PER_ENTITY;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS GET_RULE_EVALUATE_VALIDATION;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS GET_OPA_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_INFO;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_OPA_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_SFI_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_RULE_EVALUATE_NOTIFICATION;
DROP PROCEDURE IF EXISTS INSERT_OPA_DISCLOSURE_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_FUNCTION;
DROP PROCEDURE IF EXISTS GENERATE_OPA_DISCLOSURE_NUMBER;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_VARIABLE;
DROP PROCEDURE IF EXISTS INSERT_QUESTIONNAIRE_ANSWERS;
DROP PROCEDURE IF EXISTS SYNC_SFIS_AND_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_RELATIONS;
DROP PROCEDURE IF EXISTS GET_COI_ENTITY_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_EXPRESSION;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION;
DROP PROCEDURE IF EXISTS COI_UPD_ANS_TO_NEW_QUEST_VERSN;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURES_FOR_BANNER;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_REVIEWER_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_HISTORY;
DROP PROCEDURE IF EXISTS RULE_EVALUATE_QUESTION;
DROP PROCEDURE IF EXISTS COI_DELETE_TRAVEL_DISCLOSURES_BY_ID;
DROP PROCEDURE IF EXISTS COI_DELETE_SFI_BY_ID;
DROP PROCEDURE IF EXISTS COI_DELETE_RECORDS_BY_PERSON_ID;
DROP PROCEDURE IF EXISTS COI_DELETE_OPA_DISCLOSURES_BY_ID;
DROP PROCEDURE IF EXISTS COI_DELETE_COI_DISCLOSURES_BY_ID;
DROP FUNCTION IF EXISTS FN_CHK_OPA_PERSON_IS_FACULTY;
DROP FUNCTION IF EXISTS FN_EVAL_DISCLOSURE_QUESTIONNAIRE;
DROP FUNCTION IF EXISTS FN_CAN_CREATE_OPA_DISCLOSURE;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP FUNCTION IF EXISTS FN_EVALUATE_RULE;
DROP FUNCTION IF EXISTS RULE_EVALUATION_FOR_FN;

\. ./Procedures/GET_COI_DISCLOSURE_REVIEWER_DASHBOARD_COUNT.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST_COUNT.sql
\. ./Procedures/GET_PERSON_ENTITY_DASHBOARD_COUNT.sql
\. ./Procedures/GET_SFI_DASHBOARD_COUNT.sql
\. ./Procedures/GENERATE_ATTACHMENT_NUMBER.sql
\. ./Procedures/COI_SYNC_DISCLOSURE_RISK.sql
\. ./Procedures/PROC_SYNC_OPA_PER_ENTITY.sql
\. ./Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./Procedures/GET_RULE_EVALUATE_VALIDATION.sql
\. ./Procedures/COI_VALIDATE_DISCLOSURE_CONFLICTS.sql
\. ./Procedures/GET_OPA_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_PERSON_ENTITY_INFO.sql
\. ./Procedures/GET_COI_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_PERSON_ENTITIES.sql
\. ./Procedures/GET_PERSON_ENTITY_DASHBOARD.sql
\. ./Procedures/GET_COI_OPA_DASHBOARD.sql
\. ./Procedures/GET_SFI_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_RULE_EVALUATE_NOTIFICATION.sql
\. ./Procedures/INSERT_OPA_DISCLOSURE_DETAILS.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/RULE_EVALUATE_FUNCTION.sql
\. ./Procedures/GENERATE_OPA_DISCLOSURE_NUMBER.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST.sql
\. ./Procedures/RULE_EVALUATE_VARIABLE.sql
\. ./Procedures/INSERT_QUESTIONNAIRE_ANSWERS.sql
\. ./Procedures/SYNC_SFIS_AND_DISCLOSURE.sql
\. ./Procedures/GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_DISCLOSURE_RELATIONS.sql
\. ./Procedures/GET_COI_ENTITY_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/RULE_EVALUATE_EXPRESSION.sql
\. ./Procedures/COI_EVALUATE_VALIDATION.sql
\. ./Procedures/COI_UPD_ANS_TO_NEW_QUEST_VERSN.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Procedures/VALIDATE_PROJECT_DISCLOSURE.sql
\. ./Procedures/GET_COI_DISCLOSURES_FOR_BANNER.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_REVIEWER_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./Procedures/RULE_EVALUATE_QUESTION.sql
\. ./Procedures/COI_DELETE_TRAVEL_DISCLOSURES_BY_ID.sql
\. ./Procedures/COI_DELETE_SFI_BY_ID.sql
\. ./Procedures/COI_DELETE_RECORDS_BY_PERSON_ID.sql
\. ./Procedures/COI_DELETE_OPA_DISCLOSURES_BY_ID.sql
\. ./Procedures/COI_DELETE_COI_DISCLOSURES_BY_ID.sql
\. ./Functions/FN_CHK_OPA_PERSON_IS_FACULTY.sql
\. ./Functions/FN_EVAL_DISCLOSURE_QUESTIONNAIRE.sql
\. ./Functions/FN_CAN_CREATE_OPA_DISCLOSURE.sql
\. ./Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./Functions/FN_EVALUATE_RULE.sql
\. ./Functions/RULE_EVALUATION_FOR_FN.sql
