ALTER TABLE `quest_question` ADD COLUMN `FOOTER_DESCRIPTION` TEXT NULL;

ALTER TABLE `INBOX` ADD COLUMN `ALERT_TYPE` VARCHAR(45) NULL;
ALTER TABLE `INBOX` ADD COLUMN `EXPIRATION_DATE` DATETIME NULL;

ALTER TABLE `REMINDER_NOTIFICATION` ADD COLUMN `REMINDER_TYPE_FLAG` VARCHAR(3) NULL AFTER `PLACEHOLDER_VALUES`;


ALTER TABLE `discl_attachment` CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(500) NULL DEFAULT NULL ;

ALTER TABLE `entity` CHANGE COLUMN `REVISION_REASON` `REVISION_REASON` VARCHAR(500) NULL DEFAULT NULL ;