//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 06:30:11 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.payroll;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the options for the business process, as well as the data for the Costing Allocation
 * 
 * <p>Java class for Assign_Costing_Allocation_RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Costing_Allocation_RequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Business_Process_Parameters" type="{urn:com.workday/bsvc}Business_Process_ParametersType" minOccurs="0"/&gt;
 *         &lt;element name="Costing_Allocation_Data" type="{urn:com.workday/bsvc}Costing_Allocation_DataType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{urn:com.workday/bsvc}version"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Costing_Allocation_RequestType", propOrder = {
    "businessProcessParameters",
    "costingAllocationData"
})
public class AssignCostingAllocationRequestType {

    @XmlElement(name = "Business_Process_Parameters")
    protected BusinessProcessParametersType businessProcessParameters;
    @XmlElement(name = "Costing_Allocation_Data", required = true)
    protected CostingAllocationDataType costingAllocationData;
    @XmlAttribute(name = "version", namespace = "urn:com.workday/bsvc")
    protected String version;

    /**
     * Gets the value of the businessProcessParameters property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessProcessParametersType }
     *     
     */
    public BusinessProcessParametersType getBusinessProcessParameters() {
        return businessProcessParameters;
    }

    /**
     * Sets the value of the businessProcessParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessProcessParametersType }
     *     
     */
    public void setBusinessProcessParameters(BusinessProcessParametersType value) {
        this.businessProcessParameters = value;
    }

    /**
     * Gets the value of the costingAllocationData property.
     * 
     * @return
     *     possible object is
     *     {@link CostingAllocationDataType }
     *     
     */
    public CostingAllocationDataType getCostingAllocationData() {
        return costingAllocationData;
    }

    /**
     * Sets the value of the costingAllocationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostingAllocationDataType }
     *     
     */
    public void setCostingAllocationData(CostingAllocationDataType value) {
        this.costingAllocationData = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
