//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.21 at 06:30:11 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.payroll;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Specifies an allocation for a given date range
 * 
 * <p>Java class for Costing_Allocation_Interval_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Costing_Allocation_Interval_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Costing_Interval_Update_Key" type="{urn:com.workday/bsvc}Costing_Interval_Update_KeyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Costing_Override_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Start_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="End_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Costing_Allocation_Detail_Data" type="{urn:com.workday/bsvc}Costing_Allocation_Detail_Replacement_DataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Costing_Allocation_Interval_DataType", propOrder = {
    "costingIntervalUpdateKey",
    "costingOverrideID",
    "startDate",
    "endDate",
    "costingAllocationDetailData"
})
public class CostingAllocationIntervalDataType {

    @XmlElement(name = "Costing_Interval_Update_Key")
    protected List<CostingIntervalUpdateKeyType> costingIntervalUpdateKey;
    @XmlElement(name = "Costing_Override_ID")
    protected String costingOverrideID;
    @XmlElement(name = "Start_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "End_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "Costing_Allocation_Detail_Data")
    protected List<CostingAllocationDetailReplacementDataType> costingAllocationDetailData;

    /**
     * Gets the value of the costingIntervalUpdateKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costingIntervalUpdateKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostingIntervalUpdateKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CostingIntervalUpdateKeyType }
     * 
     * 
     */
    public List<CostingIntervalUpdateKeyType> getCostingIntervalUpdateKey() {
        if (costingIntervalUpdateKey == null) {
            costingIntervalUpdateKey = new ArrayList<CostingIntervalUpdateKeyType>();
        }
        return this.costingIntervalUpdateKey;
    }

    /**
     * Gets the value of the costingOverrideID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostingOverrideID() {
        return costingOverrideID;
    }

    /**
     * Sets the value of the costingOverrideID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostingOverrideID(String value) {
        this.costingOverrideID = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the costingAllocationDetailData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costingAllocationDetailData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostingAllocationDetailData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CostingAllocationDetailReplacementDataType }
     * 
     * 
     */
    public List<CostingAllocationDetailReplacementDataType> getCostingAllocationDetailData() {
        if (costingAllocationDetailData == null) {
            costingAllocationDetailData = new ArrayList<CostingAllocationDetailReplacementDataType>();
        }
        return this.costingAllocationDetailData;
    }

}
