/*
-- Sprint : Fibi-COI
1) Exclude the database name from the script.
2) Order of the script needs to be correct.
3) If there is any timestamp in script use 'now()'.
4) If there is an update script. Check if there is an insert script also in the bundle.
5) If there is a create table and alter script for a table. Remove the alter script and update the create table script.
6) Check if the syntax is correct for all scripts. Add semicolon at the end of scripts. If there is any string data put it in quotes.
*/

/*
NB: Letter templates google drive link
*/

CREATE TABLE `ENTITY_TYPE` (
  `ENTITY_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_TYPE_CODE`)
);

CREATE TABLE `ENTITY_STATUS` (
  `ENTITY_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_STATUS_CODE`)
);

CREATE TABLE `COI_ENTITY` (
  `COI_ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_ENTITY_NAME` varchar(200) DEFAULT NULL,
  `ENTITY_NAME_GIVEN_BY_CREATOR` varchar(200) DEFAULT NULL,
  `ORIGINAL_ENTITY_ID` int(11) DEFAULT NULL,
  `ENTITY_STATUS_CODE` varchar(3) DEFAULT NULL,
  `ENTITY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COUNTRY_CODE` varchar(3) DEFAULT NULL,
  `STATE_CODE` varchar(3) DEFAULT NULL,
  `ADDRESS_LINE_1` varchar(200) DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(200) DEFAULT NULL,
  `ADDRESS_LINE_3` varchar(200) DEFAULT NULL,
  `PINCODE` varchar(15) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `WEB_URL` varchar(2000) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `APPROVED_TIMESTAMP` date DEFAULT NULL,
  `APPROVED_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_ENTITY_ID`),
  KEY `ENTITY_FK1` (`ENTITY_STATUS_CODE`),
  KEY `ENTITY_FK2` (`ENTITY_TYPE_CODE`),
  KEY `ENTITY_FK3` (`COUNTRY_CODE`),
  KEY `ENTITY_FK4` (`STATE_CODE`),
  CONSTRAINT `ENTITY_FK1` FOREIGN KEY (`ENTITY_STATUS_CODE`) REFERENCES `ENTITY_STATUS` (`ENTITY_STATUS_CODE`),
  CONSTRAINT `ENTITY_FK2` FOREIGN KEY (`ENTITY_TYPE_CODE`) REFERENCES `ENTITY_TYPE` (`ENTITY_TYPE_CODE`),
  CONSTRAINT `ENTITY_FK3` FOREIGN KEY (`COUNTRY_CODE`) REFERENCES `COUNTRY` (`COUNTRY_CODE`),
  CONSTRAINT `ENTITY_FK4` FOREIGN KEY (`STATE_CODE`) REFERENCES `STATES` (`STATE_CODE`)
);

CREATE TABLE `ENTITY_SPONSOR_RELATIONSHIP` (
  `ENTITY_SPONSOR_RELATIONSHIP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_ENTITY_ID` int(11) NOT NULL,
  `SPONSOR_CODE` varchar(6) NOT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_SPONSOR_RELATIONSHIP_ID`),
  KEY `ENTITY_SPONSOR_RELATIONSHIP_FK1` (`COI_ENTITY_ID`),
  KEY `ENTITY_SPONSOR_RELATIONSHIP_FK2` (`SPONSOR_CODE`),
  CONSTRAINT `ENTITY_SPONSOR_RELATIONSHIP_FK1` FOREIGN KEY (`COI_ENTITY_ID`) REFERENCES `COI_ENTITY` (`COI_ENTITY_ID`),
  CONSTRAINT `ENTITY_SPONSOR_RELATIONSHIP_FK2` FOREIGN KEY (`SPONSOR_CODE`) REFERENCES `SPONSOR` (`SPONSOR_CODE`)
);

CREATE TABLE `ENTITY_ORG_RELATIONSHIP` (
  `ENTITY_ORG_RELATIONSHIP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_ENTITY_ID` int(11) NOT NULL,
  `ORGANIZATION_ID` varchar(20) NOT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_ORG_RELATIONSHIP_ID`),
  KEY `ENTITY_ORG_RELATIONSHIP_FK1` (`COI_ENTITY_ID`),
  KEY `ENTITY_ORG_RELATIONSHIP_FK2` (`ORGANIZATION_ID`),
  CONSTRAINT `ENTITY_ORG_RELATIONSHIP_FK1` FOREIGN KEY (`COI_ENTITY_ID`) REFERENCES `COI_ENTITY` (`COI_ENTITY_ID`),
  CONSTRAINT `ENTITY_ORG_RELATIONSHIP_FK2` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `ORGANIZATION` (`ORGANIZATION_ID`)
);

CREATE TABLE `COI_FIN_ENTITY_REL_TYPE` (
  `COI_FIN_ENTITY_REL_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `QUESTIONNAIRE_NUMBER` int(11) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_FIN_ENTITY_REL_TYPE_CODE`)
);

CREATE TABLE `COI_FINANCIAL_ENTITY` (
  `COI_FINANCIAL_ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_ENTITY_ID` int(11) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `ENTITY_VERSION_NUMBER` int(5) DEFAULT NULL, 
  `INVOLVEMENT_START_DATE` date DEFAULT NULL, 
  `INVOLVEMENT_END_DATE` date DEFAULT NULL, 
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `STUDENT_INVOLVEMENT` varchar(2000) DEFAULT NULL,
  `STAFF_INVOLVEMENT` varchar(2000) DEFAULT NULL,
  `INSTITUTE_RESOURCE_INVOLVEMENT` varchar(2000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_FINANCIAL_ENTITY_ID`),
  KEY `COI_FINANCIAL_ENTITY_FK1` (`COI_ENTITY_ID`),
  CONSTRAINT `COI_FINANCIAL_ENTITY_FK1` FOREIGN KEY (`COI_ENTITY_ID`) REFERENCES `COI_ENTITY` (`COI_ENTITY_ID`)
);

CREATE TABLE `COI_FIN_ENTITY_DETAILS` (
  `COI_FIN_ENTITY_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUESTIONNAIRE_ANS_HEADER_ID` int(11) DEFAULT NULL,
  `COI_FINANCIAL_ENTITY_ID` int(11) DEFAULT NULL,
  `COI_FIN_ENTITY_REL_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_FIN_ENTITY_DETAILS_ID`),
  KEY `COI_FIN_ENTITY_DETAILS_FK1` (`QUESTIONNAIRE_ANS_HEADER_ID`),
  KEY `COI_FIN_ENTITY_DETAILS_FK2` (`COI_FINANCIAL_ENTITY_ID`),
  KEY `COI_FIN_ENTITY_DETAILS_FK3` (`COI_FIN_ENTITY_REL_TYPE_CODE`),
  CONSTRAINT `COI_FIN_ENTITY_DETAILS_FK1` FOREIGN KEY (`QUESTIONNAIRE_ANS_HEADER_ID`) REFERENCES `QUEST_ANSWER_HEADER` (`QUESTIONNAIRE_ANS_HEADER_ID`),
  CONSTRAINT `COI_FIN_ENTITY_DETAILS_FK2` FOREIGN KEY (`COI_FINANCIAL_ENTITY_ID`) REFERENCES `COI_FINANCIAL_ENTITY` (`COI_FINANCIAL_ENTITY_ID`),
  CONSTRAINT `COI_FIN_ENTITY_DETAILS_FK3` FOREIGN KEY (`COI_FIN_ENTITY_REL_TYPE_CODE`) REFERENCES `COI_FIN_ENTITY_REL_TYPE` (`COI_FIN_ENTITY_REL_TYPE_CODE`)
);

CREATE TABLE `COI_DISCLOSURE_CATEGORY_TYPE` (
  `DISCLOSURE_CATEGORY_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_CATEGORY_TYPE_CODE`)
);

CREATE TABLE `COI_DISCLOSURE_STATUS` (
  `DISCLOSURE_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_STATUS_CODE`)
);

CREATE TABLE `COI_DISPOSITION_STATUS` (
  `DISPOSITION_STATUS_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISPOSITION_STATUS_TYPE_CODE`)
);

CREATE TABLE `COI_REVIEW_STATUS` (
  `REVIEW_STATUS_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`REVIEW_STATUS_TYPE_CODE`)
);

CREATE TABLE `COI_DISCLOSURE_SEQUENCE_STATUS` (
  `DISCLOSURE_SEQUENCE_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_SEQUENCE_STATUS_CODE`)
);

CREATE TABLE `COI_DISCLOSURE` (
  `DISCLOSURE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_NUMBER` varchar(20) DEFAULT NULL,
  `DISCLOSURE_VERSION_NUMBER` int(5) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `DISCLOSURE_STATUS_CODE` varchar(3) DEFAULT NULL,
  `DISPOSITION_STATUS_TYPE_CODE` varchar(3) DEFAULT NULL,
  `REVIEW_STATUS_TYPE_CODE` varchar(3) DEFAULT NULL, 
  `DISCLOSURE_CATEGORY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DISCLOSURE_SEQUENCE_STATUS_CODE` varchar(3) DEFAULT NULL,
  `CERTIFICATION_TEXT` varchar(2000) DEFAULT NULL,
  `CERTIFICATION_TIMESTAMP` date DEFAULT NULL,
  `CERTIFIED_BY` varchar(60) DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `EXPIRATION_DATE` date DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_ID`),
  KEY `COI_DISCLOSURE_FK1` (`DISCLOSURE_STATUS_CODE`),
  KEY `COI_DISCLOSURE_FK2` (`DISPOSITION_STATUS_TYPE_CODE`),
  KEY `COI_DISCLOSURE_FK3` (`REVIEW_STATUS_TYPE_CODE`),
  KEY `COI_DISCLOSURE_FK4` (`DISCLOSURE_CATEGORY_TYPE_CODE`),
  KEY `COI_DISCLOSURE_FK5` (`DISCLOSURE_SEQUENCE_STATUS_CODE`),
  CONSTRAINT `COI_DISCLOSURE_FK1` FOREIGN KEY (`DISCLOSURE_STATUS_CODE`) REFERENCES `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`),
  CONSTRAINT `COI_DISCLOSURE_FK2` FOREIGN KEY (`DISPOSITION_STATUS_TYPE_CODE`) REFERENCES `COI_DISPOSITION_STATUS` (`DISPOSITION_STATUS_TYPE_CODE`),
  CONSTRAINT `COI_DISCLOSURE_FK3` FOREIGN KEY (`REVIEW_STATUS_TYPE_CODE`) REFERENCES `COI_REVIEW_STATUS` (`REVIEW_STATUS_TYPE_CODE`),
  CONSTRAINT `COI_DISCLOSURE_FK4` FOREIGN KEY (`DISCLOSURE_CATEGORY_TYPE_CODE`) REFERENCES `COI_DISCLOSURE_CATEGORY_TYPE` (`DISCLOSURE_CATEGORY_TYPE_CODE`),
  CONSTRAINT `COI_DISCLOSURE_FK5` FOREIGN KEY (`DISCLOSURE_SEQUENCE_STATUS_CODE`) REFERENCES `COI_DISCLOSURE_SEQUENCE_STATUS` (`DISCLOSURE_SEQUENCE_STATUS_CODE`)
);

CREATE TABLE `COI_DISC_COMMENT_TYPE` (
  `COMMENT_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COMMENT_TYPE_CODE`)
);


CREATE TABLE `COI_DISC_DET_STATUS` (
  `DISC_DET_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISC_DET_STATUS_CODE`)
);

CREATE TABLE `COI_DISCLOSURE_DETAILS` (
  `DISCLOSURE_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_ID` int(11) DEFAULT NULL,
  `DISCLOSURE_NUMBER` varchar(20) DEFAULT NULL,
  `COI_FINANCIAL_ENTITY_ID` int(11) DEFAULT NULL,
  `MODULE_CODE` int(4) DEFAULT NULL, 
  `MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `DISC_DET_STATUS_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_DETAILS_ID`),
  KEY `COI_DISCLOSURE_DETAILS_FK1` (`DISCLOSURE_ID`),
  KEY `COI_DISCLOSURE_DETAILS_FK2` (`DISC_DET_STATUS_CODE`),
  KEY `COI_DISCLOSURE_DETAILS_FK3` (`COI_FINANCIAL_ENTITY_ID`),
  CONSTRAINT `COI_DISCLOSURE_DETAILS_FK1` FOREIGN KEY (`DISCLOSURE_ID`) REFERENCES `COI_DISCLOSURE` (`DISCLOSURE_ID`),
  CONSTRAINT `COI_DISCLOSURE_DETAILS_FK2` FOREIGN KEY (`DISC_DET_STATUS_CODE`) REFERENCES `COI_DISC_DET_STATUS` (`DISC_DET_STATUS_CODE`),
  CONSTRAINT `COI_DISCLOSURE_DETAILS_FK3` FOREIGN KEY (`COI_FINANCIAL_ENTITY_ID`) REFERENCES `COI_FINANCIAL_ENTITY` (`COI_FINANCIAL_ENTITY_ID`)
);

CREATE TABLE `COI_DISC_DETAILS_COMMENTS` (
  `DISCLOSURE_DETAILS_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_DETAILS_ID` int(11) DEFAULT NULL,
  `DISCLOSURE_NUMBER` varchar(20) DEFAULT NULL,
  `COMMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COMMENT` longtext,
  `IS_PRIVATE` varchar(1) DEFAULT NULL,
  `PARENT_DISC_DET_COMMENT_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DISCLOSURE_DETAILS_COMMENT_ID`),
  KEY `COI_DISC_DETAILS_COMMENTS_FK1` (`DISCLOSURE_DETAILS_ID`),
  KEY `COI_DISC_DETAILS_COMMENTS_FK2` (`COMMENT_TYPE_CODE`),
  CONSTRAINT `COI_DISC_DETAILS_COMMENTS_FK1` FOREIGN KEY (`DISCLOSURE_DETAILS_ID`) REFERENCES `COI_DISCLOSURE_DETAILS` (`DISCLOSURE_DETAILS_ID`),
  CONSTRAINT `COI_DISC_DETAILS_COMMENTS_FK2` FOREIGN KEY (`COMMENT_TYPE_CODE`) REFERENCES `COI_DISC_COMMENT_TYPE` (`COMMENT_TYPE_CODE`)
);

CREATE TABLE `COI_AUDIT_ACTION_TYPE` (
  `COI_AUDIT_ACTION_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_AUDIT_ACTION_TYPE_CODE`)
);

CREATE TABLE `COI_DISCLOSURE_AUDIT_TRAIL` (
  `COI_DISCLOSURE_AUDIT_TRAIL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_ID` int(11) DEFAULT NULL,
  `COI_AUDIT_ACTION_TYPE_CODE` varchar(3) DEFAULT NULL,
  `SYSTEM_REMARK` varchar(2000) DEFAULT NULL, 
  `ADDITIONAL_REMARK` varchar(2000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_DISCLOSURE_AUDIT_TRAIL_ID`),
  KEY `COI_DISCLOSURE_AUDIT_TRAIL_FK1` (`COI_AUDIT_ACTION_TYPE_CODE`),
  CONSTRAINT `COI_DISCLOSURE_AUDIT_TRAIL_FK1` FOREIGN KEY (`COI_AUDIT_ACTION_TYPE_CODE`) REFERENCES `COI_AUDIT_ACTION_TYPE` (`COI_AUDIT_ACTION_TYPE_CODE`)
);

CREATE TABLE `COI_ATTACHMENT_TYPE` (
  `COI_ATTA_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_ATTA_TYPE_CODE`)
);

CREATE TABLE `COI_ATTACHMENT_CATEGORY_TYPE` (
  `COI_ATTA_CATEGORY_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_ATTA_CATEGORY_TYPE_CODE`)
);

CREATE TABLE `COI_ATTA_CATE_TYPE_MAPPING` (
  `COI_ATTA_CATE_TYPE_MAPPING_ID` int(6) NOT NULL AUTO_INCREMENT, 
  `COI_ATTA_CATEGORY_TYPE_CODE` varchar(3) NOT NULL,
  `COI_ATTA_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_ATTA_CATE_TYPE_MAPPING_ID`),
  KEY `COI_ATTA_CATE_TYPE_MAPPING_FK1` (`COI_ATTA_CATEGORY_TYPE_CODE`),
  KEY `COI_ATTA_CATE_TYPE_MAPPING_FK2` (`COI_ATTA_TYPE_CODE`),
  CONSTRAINT `COI_ATTA_CATE_TYPE_MAPPING_FK1` FOREIGN KEY (`COI_ATTA_CATEGORY_TYPE_CODE`) REFERENCES `COI_ATTACHMENT_CATEGORY_TYPE` (`COI_ATTA_CATEGORY_TYPE_CODE`),
  CONSTRAINT `COI_ATTA_CATE_TYPE_MAPPING_FK2` FOREIGN KEY (`COI_ATTA_TYPE_CODE`) REFERENCES `COI_ATTACHMENT_TYPE` (`COI_ATTA_TYPE_CODE`)
);

CREATE TABLE `COI_FILE_DATA` (
  `FILE_DATA_ID` varchar(40) NOT NULL,
  `DATA` longblob,
  PRIMARY KEY (`FILE_DATA_ID`)
);

CREATE TABLE `COI_DISCLOSURE_ATTACHMENTS` (
  `COI_DISCLOSURE_ATTACHMENTS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `FILE_NAME` varchar(255) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `FILE_DATA_ID` varchar(40) NOT NULL,
  `ATTACHMENT_VERSION_NUMBER` int(5) DEFAULT NULL, 
  `ATTACHMENT_VERSION_STATUS` varchar(3) DEFAULT NULL, 
  `COI_ATTA_CATEGORY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COI_ATTA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COI_ATTA_CATEGORY_VALUE` varchar(20) DEFAULT NULL, 
  `COI_ATTA_STATUS_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_DISCLOSURE_ATTACHMENTS_ID`),
  KEY `COI_DISCLOSURE_ATTACHMENTS_FK1` (`COI_ATTA_CATEGORY_TYPE_CODE`),
  KEY `COI_DISCLOSURE_ATTACHMENTS_FK2` (`COI_ATTA_TYPE_CODE`),
  KEY `COI_DISCLOSURE_ATTACHMENTS_FK3` (`FILE_DATA_ID`),
  CONSTRAINT `COI_DISCLOSURE_ATTACHMENTS_FK1` FOREIGN KEY (`COI_ATTA_CATEGORY_TYPE_CODE`) REFERENCES `COI_ATTACHMENT_CATEGORY_TYPE` (`COI_ATTA_CATEGORY_TYPE_CODE`),
  CONSTRAINT `COI_DISCLOSURE_ATTACHMENTS_FK2` FOREIGN KEY (`COI_ATTA_TYPE_CODE`) REFERENCES `COI_ATTACHMENT_TYPE` (`COI_ATTA_TYPE_CODE`),
  CONSTRAINT `COI_DISCLOSURE_ATTACHMENTS_FK3` FOREIGN KEY (`FILE_DATA_ID`) REFERENCES `COI_FILE_DATA` (`FILE_DATA_ID`)
);

INSERT INTO `entity_type` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'Publicly owned', 'Y', now(), 'quickstart');
INSERT INTO `entity_type` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'Private', 'Y', now(), 'quickstart');
INSERT INTO `entity_type` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Non-profit', 'Y', now(), 'quickstart');
INSERT INTO `entity_type` (`ENTITY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'For-profit', 'Y', now(), 'quickstart');

INSERT INTO `entity_status` (`ENTITY_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'ACTIVE', 'Y', now(), 'quickstart');
INSERT INTO `entity_status` (`ENTITY_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'INACTIVE', 'Y', now(), 'quickstart');

INSERT INTO `COI_FIN_ENTITY_REL_TYPE` (`COI_FIN_ENTITY_REL_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'SELF', 'Y', now(), 'quickstart');
INSERT INTO `COI_FIN_ENTITY_REL_TYPE` (`COI_FIN_ENTITY_REL_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'SPOUSE', 'Y', now(), 'quickstart');
INSERT INTO `COI_FIN_ENTITY_REL_TYPE` (`COI_FIN_ENTITY_REL_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'DEPENDANT', 'Y', now(), 'quickstart');

INSERT INTO `COI_DISCLOSURE_CATEGORY_TYPE` (`DISCLOSURE_CATEGORY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'Financial Conflict of Interest', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_CATEGORY_TYPE` (`DISCLOSURE_CATEGORY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'Other professional Activities', 'N', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_CATEGORY_TYPE` (`DISCLOSURE_CATEGORY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Proposal Disclosures', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_CATEGORY_TYPE` (`DISCLOSURE_CATEGORY_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'Travel Disclosures', 'N', now(), 'quickstart');

INSERT INTO `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'Pending', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'Review in progress', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Active', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'Conflict identified during Review', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('5', 'Conflict Management in progress', 'Y', now(), 'quickstart');
INSERT INTO `COI_DISCLOSURE_STATUS` (`DISCLOSURE_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('6', 'Conflict Managed', 'Y', now(), 'quickstart');

INSERT INTO `coi_disposition_status` (`DISPOSITION_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'Pending', 'Y', now(), 'quickstart');
INSERT INTO `coi_disposition_status` (`DISPOSITION_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Disapproved', 'Y', now(), 'quickstart');
INSERT INTO `coi_disposition_status` (`DISPOSITION_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'Approved', 'Y', now(), 'quickstart');
INSERT INTO `coi_disposition_status` (`DISPOSITION_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', 'Voided', 'Y', now(), 'quickstart');

INSERT INTO `coi_review_status` (`REVIEW_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'InProgress', 'Y', now(), 'quickstart');
INSERT INTO `coi_review_status` (`REVIEW_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'Submitted For Review', 'Y', now(), 'quickstart');
INSERT INTO `coi_review_status` (`REVIEW_STATUS_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Review Complete', 'Y', now(), 'quickstart');

INSERT INTO `coi_disc_det_status` (`DISC_DET_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'Conflict', 'Y', now(), 'quickstart');
INSERT INTO `coi_disc_det_status` (`DISC_DET_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', 'No-Conflict', 'Y', now(), 'quickstart');
INSERT INTO `coi_disc_det_status` (`DISC_DET_STATUS_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', 'Potential Conflict', 'Y', now(), 'quickstart');

INSERT INTO `COI_DISCLOSURE_SEQUENCE_STATUS` (`DISCLOSURE_SEQUENCE_STATUS_CODE`,`DESCRIPTION`,`IS_ACTIVE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('1','PENDING','Y',now(),'quickstart');
INSERT INTO `COI_DISCLOSURE_SEQUENCE_STATUS` (`DISCLOSURE_SEQUENCE_STATUS_CODE`,`DESCRIPTION`,`IS_ACTIVE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('2','ACTIVE','Y',now(),'quickstart');
INSERT INTO `COI_DISCLOSURE_SEQUENCE_STATUS` (`DISCLOSURE_SEQUENCE_STATUS_CODE`,`DESCRIPTION`,`IS_ACTIVE`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ('3','ARCHIVE','Y',now(),'quickstart');

INSERT INTO `coeus_module` (`MODULE_CODE`,`DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`,`IS_ACTIVE`) VALUES ('8', 'COI Disclosure', now(), 'quickstart', 'Y');

INSERT INTO `coeus_sub_module` (`COEUS_SUB_MODULE_ID`, `MODULE_CODE`, `SUB_MODULE_CODE`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `REQUIRE_UNIQUE_QUESTIONNAIRE`, `IS_ACTIVE`) VALUES ('801', '8', '801', 'SFI', Date(now()), 'quickstart', 'N', 'Y');

INSERT INTO `quest_header` (`QUESTIONNAIRE_ID`, `IS_FINAL`, `QUESTIONNAIRE_NUMBER`, `VERSION_NUMBER`, `QUESTIONNAIRE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`,`DESCRIPTION`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID) + 1,1) AS ID FROM QUEST_COLUMN_NEXTVALUE) AS T), 'Y',(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_NUMBER) + 1,1) AS ID FROM QUEST_COLUMN_NEXTVALUE) AS T), '1', 'Screening Questionnaire', now(), 'quickstart','Screening Questionnaire');
UPDATE `quest_column_nextvalue` SET `QUESTIONNAIRE_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T), `QUESTIONNAIRE_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_NUMBER),1) AS ID FROM QUEST_HEADER) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),1,'Over the last 12 months, or do you expect to receive over the next 12 months: Honoraria or other payments or reimbursements for seminars, lectures, or teaching engagements from any foreign institution?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),2,'Over the last 12 months, or do you expect to receive over the next 12 months: Honoraria or other payments or reimbursements for seminars, lectures, or teaching engagements from any for-profit entity?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),3,'Over the last 12 months, or do you expect to receive over the next 12 months: Payments for intellectual property such as copyrights or royalties from any source other than MIT (excludes scholarly works)?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),4,'Over the last 12 months, or do you expect to receive over the next 12 months: Compensation for any board positions, including science advisory boards?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),5,'Over the last 12 months, or do you expect to receive over the next 12 months: Consulting, salary or other income for services work performed or other services provided?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),6,'Do you have Equity interest in a non-publically traded company (any amount)?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),7,'What is the range of publically traded stock in leu of payment for services provided?',NULL,NULL,NULL,'Radio',NULL,1,NULL,NULL,NULL,'G0',NULL,'N',now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Between $500 & $5000',NULL,NULL,'2022-07-18','willsmith');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Between $5000 & $10000',NULL,NULL,'2022-07-18','willsmith');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Greater Than $10000',NULL,NULL,'2022-07-18','willsmith');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),8,'Publically traded stock or stock options in excess of $5,000 must only be disclosed in certain circumstances: when it is held in combination with other relationships described above (Income) when the company sponsors the Investigator’s Research, or when the company’s line of business may reasonably appear to be related to the Investigator’s Research at MIT and the value of the stock exceeds $100,000.',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),9,'Goods or services purchased from an entity in which you have a SFI?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),10,'Subaward issues to an entity in which you have an SFI?',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_usage` (`QUESTIONNAIRE_USAGE_ID`, `MODULE_ITEM_CODE`, `MODULE_SUB_ITEM_CODE`, `QUESTIONNAIRE_ID`, `QUESTIONNAIRE_LABEL`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `SORT_ORDER`,`TRIGGER_POST_EVALUATION`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_USAGE_ID)+1,1) AS ID FROM QUEST_USAGE) AS T), '8', '0', (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T), 'Screening Questionnaire', 'Y', now(), 'quickstart', '1','Y');

UPDATE `quest_column_nextvalue` SET `QUESTIONNAIRE_USAGE_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_USAGE_ID),1) AS ID FROM QUEST_USAGE) AS T);

INSERT INTO `quest_header` (`QUESTIONNAIRE_ID`, `IS_FINAL`, `QUESTIONNAIRE_NUMBER`, `VERSION_NUMBER`, `QUESTIONNAIRE`,`DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID) + 1,1) AS ID FROM QUEST_COLUMN_NEXTVALUE) AS T), 'Y',(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_NUMBER) + 1,1) AS ID FROM QUEST_COLUMN_NEXTVALUE) AS T), '1', 'Self','Self',now(), 'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTIONNAIRE_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T), `QUESTIONNAIRE_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_NUMBER),1) AS ID FROM QUEST_HEADER) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),1,'Income From  :  Royalty Income from intellectual property,including copyrights (excluding from MIT)',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),2,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),3,'Income From  : Member of a Board of Directors or Science Advisory Board',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),4,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),5,'Income From  : Consulting',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),6,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),7,'Income From : Speaking at conferences or seminars(excluding US universities and others *)
* Exclude income from:
> U.S. Federal, State or local government agencies
> U.S. Institutes of higher education
> Research Institutes affiliated with Institutes of higher education, and academic teaching hospitals and medical centers',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),8,'Stock & Equity : Any Equity in a non-public-ally traded company',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),9,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),10,'Stock & Equity : Common Stock Holdings',NULL,NULL,NULL,'Y/N',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),11,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);


INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),12,'Stock & Equity :  Stock Options (no. of shares)',NULL,NULL,NULL,'Textarea',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),13,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),14,'Stock & Equity : Other Ownership Interests',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),15,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),16,'Other : Good purchased for research or other MIT activities',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),17,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),18,'Other : Sub award(s) issued to entity',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),19,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),20,'Other : Gift Recieved',NULL,NULL,NULL,'Y/N/NA',NULL,1,NULL,NULL,NULL,'G0',NULL,NULL,now(),'quickstart',NULL);
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'yes',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'no',NULL,NULL,now(),'quickstart');
INSERT INTO `quest_question_option` (`QUESTION_OPTION_ID`,`QUESTION_ID`,`OPTION_NUMBER`,`OPTION_LABEL`,`REQUIRE_EXPLANATION`,`EXPLANTION_LABEL`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID)+1,1) AS ID FROM QUEST_QUESTION_OPTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'N/A',NULL,NULL,now(),'quickstart');
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T),`QUESTION_OPTION_ID`= (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_OPTION_ID),1) AS ID FROM QUEST_QUESTION_OPTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),21,'Comments',NULL,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T),NULL,'Text',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_question` (`QUESTION_ID`,`QUESTION_NUMBER`,`QUESTION_VERSION_NUMBER`,`QUESTIONNAIRE_ID`,`SORT_ORDER`,`QUESTION`,`DESCRIPTION`,`PARENT_QUESTION_ID`,`HELP_LINK`,`ANSWER_TYPE`,`ANSWER_LENGTH`,`NO_OF_ANSWERS`,`LOOKUP_TYPE`,`LOOKUP_NAME`,`LOOKUP_FIELD`,`GROUP_NAME`,`GROUP_LABEL`,`HAS_CONDITION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`RULE_ID`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID)+1,1) AS ID FROM QUEST_QUESTION) AS T),(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER)+1,1) AS ID FROM QUEST_QUESTION) AS T),1,(SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T),22,'Others',NULL,NULL,NULL,'Textarea',NULL,1,NULL,NULL,NULL,'G15',NULL,NULL,now(),'quickstart',NULL);
UPDATE `quest_column_nextvalue` SET `QUESTION_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_ID),1) AS ID FROM QUEST_QUESTION) AS T), `QUESTION_NUMBER` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTION_NUMBER),1) AS ID FROM QUEST_QUESTION) AS T);

INSERT INTO `quest_usage` (`QUESTIONNAIRE_USAGE_ID`, `MODULE_ITEM_CODE`, `MODULE_SUB_ITEM_CODE`, `QUESTIONNAIRE_ID`, `QUESTIONNAIRE_LABEL`, `IS_MANDATORY`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `SORT_ORDER`,`TRIGGER_POST_EVALUATION`) VALUES ((SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_USAGE_ID)+1,1) AS ID FROM QUEST_USAGE) AS T), '8', '801', (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_ID),1) AS ID FROM QUEST_HEADER) AS T), 'Screening Questionnaire', 'Y', now(), 'quickstart', '1','Y');
UPDATE `quest_column_nextvalue` SET `QUESTIONNAIRE_USAGE_ID` = (SELECT T.ID FROM (SELECT ifnull(MAX(QUESTIONNAIRE_USAGE_ID),1) AS ID FROM QUEST_USAGE) AS T);

INSERT INTO RIGHTS(RIGHT_ID, RIGHT_NAME, DESCRIPTION, UPDATE_USER, UPDATE_TIMESTAMP, RIGHTS_TYPE_CODE)VALUES (800, 'COI_ADMINISTRATOR', 'Coi Administrator', 'ADMIN', UTC_TIMESTAMP(), '1');

INSERT INTO `COI_DISC_COMMENT_TYPE` (`COMMENT_TYPE_CODE`, `DESCRIPTION`, `IS_ACTIVE`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', 'Disclosure Relation', 'Y', now(), 'quickstart');
ALTER TABLE COI_DISCLOSURE ADD COLUMN REVISE_COMMENT VARCHAR(2000) DEFAULT NULL;

Alter table `COI_DISCLOSURE`
add column `IS_DISCLOSURE_QUESTIONNAIRE` varchar(1) DEFAULT 'Y';

update coi_financial_entity SET IS_ACTIVE ='Y';

ALTER TABLE COI_FINANCIAL_ENTITY ADD COLUMN CREATE_TIMESTAMP DATETIME;

CREATE TABLE `coi_review_activity` (
  `COI_REVIEW_ACTIVITY_ID` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`COI_REVIEW_ACTIVITY_ID`)
);

CREATE TABLE `coi_sections_type` (
  `COI_SECTIONS_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`COI_SECTIONS_TYPE_CODE`)
);

CREATE TABLE `coi_assignee_type` (
  `ASSIGNEE_TYPE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ASSIGNEE_TYPE`)
);

CREATE TABLE `coi_review` (
  `COI_REVIEW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ASSIGNEE_PERSON_ID` varchar(40) DEFAULT NULL,
  `DISCLOSURE_ID` int(11) DEFAULT NULL,
  `ADMIN_GROUP_ID` int(11) DEFAULT NULL,
  `REVIEW_STATUS_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_ID`),
  KEY `COI_REVIEW_FK1` (`ASSIGNEE_PERSON_ID`),
  KEY `COI_REVIEW_FK2` (`DISCLOSURE_ID`),
  KEY `COI_REVIEW_FK3` (`ADMIN_GROUP_ID`),
  KEY `COI_REVIEW_FK4` (`REVIEW_STATUS_TYPE_CODE`),
  CONSTRAINT `COI_REVIEW_FK1` FOREIGN KEY (`ASSIGNEE_PERSON_ID`) REFERENCES `person` (`PERSON_ID`),
  CONSTRAINT `COI_REVIEW_FK2` FOREIGN KEY (`DISCLOSURE_ID`) REFERENCES `coi_disclosure` (`DISCLOSURE_ID`),
  CONSTRAINT `COI_REVIEW_FK3` FOREIGN KEY (`ADMIN_GROUP_ID`) REFERENCES `admin_group` (`ADMIN_GROUP_ID`),
  CONSTRAINT `COI_REVIEW_FK4` FOREIGN KEY (`REVIEW_STATUS_TYPE_CODE`) REFERENCES `coi_review_status` (`REVIEW_STATUS_TYPE_CODE`)
);

CREATE TABLE `coi_review_assignee_history` (
  `COI_REVIEW_ASSIGNEE_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_REVIEW_ID` int(11) NOT NULL,
  `ASSIGNEE_TYPE` varchar(1) NOT NULL,
  `ASSIGNEE_PERSON_ID` varchar(40) DEFAULT NULL,
  `ADMIN_GROUP_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `COI_REVIEW_ACTIVITY_ID` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_ASSIGNEE_HISTORY_ID`),
  KEY `COI_REVIEW_ASSIGNEE_HST_FK1` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_ASSIGNEE_HST_FK1` FOREIGN KEY (`COI_REVIEW_ID`) REFERENCES `coi_review` (`COI_REVIEW_ID`)
);


CREATE TABLE `coi_review_status_history` (
  `COI_REVIEW_STATUS_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_REVIEW_ID` int(11) NOT NULL,
  `COI_REVIEW_STATUS_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_STATUS_HISTORY_ID`),
  KEY `COI_REVIEW_STATUS_HISTORY_FK1` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_STATUS_HISTORY_FK1` FOREIGN KEY (`COI_REVIEW_ID`) REFERENCES `coi_review` (`COI_REVIEW_ID`)
);

INSERT INTO `coi_review_activity` (`COI_REVIEW_ACTIVITY_ID`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('1','Comment',now(),'quickstart','Y');
INSERT INTO `coi_review_activity` (`COI_REVIEW_ACTIVITY_ID`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('2','Create',now(),'quickstart','Y');
INSERT INTO `coi_review_activity` (`COI_REVIEW_ACTIVITY_ID`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('3','Start',now(),'quickstart','Y');
INSERT INTO `coi_review_activity` (`COI_REVIEW_ACTIVITY_ID`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('4','Complete',now(),'quickstart','Y');


UPDATE `coi_review_status` SET `DESCRIPTION` = 'Pending' WHERE (`REVIEW_STATUS_TYPE_CODE` = '1');
UPDATE `coi_review_status` SET `DESCRIPTION` = 'In Progress' WHERE (`REVIEW_STATUS_TYPE_CODE` = '2');
UPDATE `coi_review_status` SET `DESCRIPTION` = 'Complete' WHERE (`REVIEW_STATUS_TYPE_CODE` = '3');



INSERT INTO `coi_sections_type` (`COI_SECTIONS_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('1','Questionnaire',now(),'quickstart','Y');
INSERT INTO `coi_sections_type` (`COI_SECTIONS_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('2','SFIs',now(),'quickstart','Y');
INSERT INTO `coi_sections_type` (`COI_SECTIONS_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('3','Project relationships',now(),'quickstart','Y');
INSERT INTO `coi_sections_type` (`COI_SECTIONS_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`IS_ACTIVE`) VALUES ('4','Certification',now(),'quickstart','Y');

CREATE TABLE `coi_review_comment` (
  `COI_REVIEW_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_REVIEW_ID` int(11) DEFAULT NULL,
  `COI_SECTIONS_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COMMENT` varchar(2000) DEFAULT NULL,
  `COI_REVIEW_ACTIVITY_ID` varchar(3) DEFAULT NULL,
  `COI_PARENT_COMMENT_ID` int(11) DEFAULT NULL,
  `COI_SUB_SECTIONS_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `COMMENTED_BY_PERSON_ID` varchar(40) DEFAULT NULL,
  `IS_PRIVATE` varchar(1) DEFAULT NULL,
  `DISCLOSURE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_COMMENT_ID`),
  KEY `COI_REVIEW_COMMENT_FK1` (`COI_REVIEW_ID`),
  KEY `COI_REVIEW_COMMENT_FK2` (`COI_SECTIONS_TYPE_CODE`),
  KEY `COI_REVIEW_COMMENT_FK5` (`COI_REVIEW_ACTIVITY_ID`),
  KEY `COI_REVIEW_COMMENT_FK6` (`DISCLOSURE_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK1` FOREIGN KEY (`COI_REVIEW_ID`) REFERENCES `coi_review` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK2` FOREIGN KEY (`COI_SECTIONS_TYPE_CODE`) REFERENCES `coi_sections_type` (`COI_SECTIONS_TYPE_CODE`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK5` FOREIGN KEY (`COI_REVIEW_ACTIVITY_ID`) REFERENCES `coi_review_activity` (`COI_REVIEW_ACTIVITY_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK6` FOREIGN KEY (`DISCLOSURE_ID`) REFERENCES `coi_disclosure` (`DISCLOSURE_ID`)
);

CREATE TABLE `coi_review_comment_tags` (
  `COI_REVIEW_COMMENT_TAGS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_REVIEW_COMMENT_ID` int(11) DEFAULT NULL,
  `COI_REVIEW_ID` int(11) DEFAULT NULL,
  `TAG_REF` varchar(20) DEFAULT NULL,
  `TAGGED_PERSON_ID` varchar(40) DEFAULT NULL,
  `TAGGED_GROUP_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_COMMENT_TAGS_ID`),
  KEY `COI_REVIEW_CMT_TAGS_FK2` (`COI_REVIEW_COMMENT_ID`),
  KEY `COI_REVIEW_CMT_TAGS_FK1` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_CMT_TAGS_FK1` FOREIGN KEY (`COI_REVIEW_ID`) REFERENCES `coi_review` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_CMT_TAGS_FK2` FOREIGN KEY (`COI_REVIEW_COMMENT_ID`) REFERENCES `coi_review_comment` (`COI_REVIEW_COMMENT_ID`)
);
CREATE TABLE `coi_review_comment_attachment` (
  `COI_REVIEW_COMMENT_ATT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_REVIEW_COMMENT_ID` int(11) NOT NULL,
  `COI_REVIEW_ID` int(11) DEFAULT NULL,
  `FILE_NAME` varchar(255) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `FILE_DATA_ID` varchar(40) NOT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_COMMENT_ATT_ID`),
  KEY `COI_REVIEW_COMMENT_ATTACHMENT_FK1` (`COI_REVIEW_ID`),
  KEY `COI_REVIEW_COMMENT_ATTACHMENT_FK2` (`COI_REVIEW_COMMENT_ID`),
  KEY `COI_REVIEW_COMMENT_ATTACHMENT_FK3` (`FILE_DATA_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_ATTACHMENT_FK1` FOREIGN KEY (`COI_REVIEW_ID`) REFERENCES `coi_review` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_ATTACHMENT_FK2` FOREIGN KEY (`COI_REVIEW_COMMENT_ID`) REFERENCES `coi_review_comment` (`COI_REVIEW_COMMENT_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_ATTACHMENT_FK3` FOREIGN KEY (`FILE_DATA_ID`) REFERENCES `coi_file_data` (`FILE_DATA_ID`)
);

alter table COI_REVIEW_COMMENT_TAGS
modify column  `TAGGED_GROUP_ID` int(11) DEFAULT NULL;

alter table coi_disclosure_details
add column `COI_REVIEWER_STATUS_CODE` varchar(3) DEFAULT NULL;

alter table coi_disclosure_details
add  CONSTRAINT `COI_DISCLOSURE_DETAILS_FK4` FOREIGN KEY (`COI_REVIEWER_STATUS_CODE`) REFERENCES `COI_DISC_DET_STATUS` (`DISC_DET_STATUS_CODE`);

CREATE TABLE `COI_CONFLICT_HISTORY` (
  `COI_CONFLICT_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DISCLOSURE_DETAILS_ID` int(11) NOT NULL, 
  `COMMENT` varchar(2000) DEFAULT NULL,
  `DISC_DET_STATUS_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_CONFLICT_HISTORY_ID`),
  KEY `COI_CONFLICT_HISTORY_FK1` (`DISC_DET_STATUS_CODE`),
  CONSTRAINT `COI_CONFLICT_HISTORY_FK1` FOREIGN KEY (`DISC_DET_STATUS_CODE`) REFERENCES `COI_DISC_DET_STATUS` (`DISC_DET_STATUS_CODE`)
);

INSERT INTO `role` (`ROLE_ID`, `ROLE_NAME`, `DESCRIPTION`, `ROLE_TYPE_CODE`, `STATUS_FLAG`, `CREATE_TIMESTAMP`, `CREATE_USER`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1334', 'Coi Reviewer', 'Coi Reviewer', '2', 'Y', now(), 'quickstart', now(), 'quickstart');

INSERT INTO `rights` (`RIGHT_ID`, `RIGHT_NAME`, `DESCRIPTION`, `UPDATE_USER`, `UPDATE_TIMESTAMP`, `RIGHTS_TYPE_CODE`) VALUES ((select c.id from (select max(right_id)+1 as id from rights) as c), 'VIEW_COI_REVIEW', 'View Coi Review', 'quickstart',now(), '2');

DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_SFI_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_SFI_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP FUNCTION IF EXISTS FN_EVAL_DISCLOSURE_QUESTIONNAIRE;

\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_SFI_DASHBOARD.sql
\. ./Procedures/GET_SFI_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Functions/FN_EVAL_DISCLOSURE_QUESTIONNAIRE.sql
