
/*
-- Sprint : Fibi-COI
1) Exclude the database name from the script.
2) Order of the script needs to be correct.
3) If there is any timestamp in script use 'now()'.
4) If there is an update script. Check if there is an insert script also in the bundle.
5) If there is a create table and alter script for a table. Remove the alter script and update the create table script.
6) Check if the syntax is correct for all scripts. Add semicolon at the end of scripts. If there is any string data put it in quotes.
*/


DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITY_DASHBOARD_COUNT;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_REVIEWER_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_REVIEWER_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_SFI_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_SFI_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS SYNC_SFIS_AND_DISCLOSURE;
DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;


\. ./Procedures/GET_PERSON_ENTITY_DASHBOARD.sql
\. ./Procedures/GET_PERSON_ENTITY_DASHBOARD_COUNT.sql
\. ./Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
\. ./Procedures/COI_VALIDATE_DISCLOSURE_CONFLICTS.sql
\. ./Procedures/GET_PERSON_ENTITIES.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_REVIEWER_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_REVIEWER_DASHBOARD_COUNT.sql
\. ./Procedures/GET_SFI_DASHBOARD.sql
\. ./Procedures/GET_SFI_DASHBOARD_COUNT.sql
\. ./Procedures/SYNC_SFIS_AND_DISCLOSURE.sql
\. ./Procedures/VALIDATE_PROJECT_DISCLOSURE.sql

