//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 05:00:45 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.staffing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Wrapper element for the Close Position business process data including the position to close and the event data.
 * 
 * <p>Java class for Close_Position_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Close_Position_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Position_Reference" type="{urn:com.workday/bsvc}Position_RestrictionsObjectType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Close_Event_Data" type="{urn:com.workday/bsvc}Close_Position_Event_DataType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Close_Position_DataType", propOrder = {
    "positionReference",
    "closeEventData"
})
public class ClosePositionDataType {

    @XmlElement(name = "Position_Reference")
    protected PositionRestrictionsObjectType positionReference;
    @XmlElement(name = "Close_Event_Data", required = true)
    protected List<ClosePositionEventDataType> closeEventData;

    /**
     * Gets the value of the positionReference property.
     * 
     * @return
     *     possible object is
     *     {@link PositionRestrictionsObjectType }
     *     
     */
    public PositionRestrictionsObjectType getPositionReference() {
        return positionReference;
    }

    /**
     * Sets the value of the positionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionRestrictionsObjectType }
     *     
     */
    public void setPositionReference(PositionRestrictionsObjectType value) {
        this.positionReference = value;
    }

    /**
     * Gets the value of the closeEventData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the closeEventData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloseEventData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClosePositionEventDataType }
     * 
     * 
     */
    public List<ClosePositionEventDataType> getCloseEventData() {
        if (closeEventData == null) {
            closeEventData = new ArrayList<ClosePositionEventDataType>();
        }
        return this.closeEventData;
    }

}
