//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 05:00:45 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.staffing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains the Move Workers (By Organization) position and worker reference.
 * 
 * <p>Java class for Move_Workers_By_Organization_Position_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Move_Workers_By_Organization_Position_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Position_to_Move_Reference" type="{urn:com.workday/bsvc}Staffing_InterfaceObjectType"/&gt;
 *         &lt;element name="Worker_for_Position_Reference" type="{urn:com.workday/bsvc}WorkerObjectType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Move_Workers_By_Organization_Position_DataType", propOrder = {
    "positionToMoveReference",
    "workerForPositionReference"
})
public class MoveWorkersByOrganizationPositionDataType {

    @XmlElement(name = "Position_to_Move_Reference", required = true)
    protected StaffingInterfaceObjectType positionToMoveReference;
    @XmlElement(name = "Worker_for_Position_Reference")
    protected WorkerObjectType workerForPositionReference;

    /**
     * Gets the value of the positionToMoveReference property.
     * 
     * @return
     *     possible object is
     *     {@link StaffingInterfaceObjectType }
     *     
     */
    public StaffingInterfaceObjectType getPositionToMoveReference() {
        return positionToMoveReference;
    }

    /**
     * Sets the value of the positionToMoveReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffingInterfaceObjectType }
     *     
     */
    public void setPositionToMoveReference(StaffingInterfaceObjectType value) {
        this.positionToMoveReference = value;
    }

    /**
     * Gets the value of the workerForPositionReference property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerObjectType }
     *     
     */
    public WorkerObjectType getWorkerForPositionReference() {
        return workerForPositionReference;
    }

    /**
     * Sets the value of the workerForPositionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerObjectType }
     *     
     */
    public void setWorkerForPositionReference(WorkerObjectType value) {
        this.workerForPositionReference = value;
    }

}
