//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 05:00:45 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.staffing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Contains the Move Workers (By Organization) web service.
 * 
 * <p>Java class for Move_Workers_By_Organization_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Move_Workers_By_Organization_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Effective_Date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="From_Organization_Reference" type="{urn:com.workday/bsvc}StaffObjectType"/&gt;
 *         &lt;element name="Move_Workers_By_Organization_Position_Data" type="{urn:com.workday/bsvc}Move_Workers_By_Organization_Position_DataType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="To_Organization_Reference" type="{urn:com.workday/bsvc}StaffObjectType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Move_Workers_By_Organization_DataType", propOrder = {
    "effectiveDate",
    "fromOrganizationReference",
    "moveWorkersByOrganizationPositionData",
    "toOrganizationReference"
})
public class MoveWorkersByOrganizationDataType {

    @XmlElement(name = "Effective_Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "From_Organization_Reference", required = true)
    protected StaffObjectType fromOrganizationReference;
    @XmlElement(name = "Move_Workers_By_Organization_Position_Data", required = true)
    protected List<MoveWorkersByOrganizationPositionDataType> moveWorkersByOrganizationPositionData;
    @XmlElement(name = "To_Organization_Reference", required = true)
    protected StaffObjectType toOrganizationReference;

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the fromOrganizationReference property.
     * 
     * @return
     *     possible object is
     *     {@link StaffObjectType }
     *     
     */
    public StaffObjectType getFromOrganizationReference() {
        return fromOrganizationReference;
    }

    /**
     * Sets the value of the fromOrganizationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffObjectType }
     *     
     */
    public void setFromOrganizationReference(StaffObjectType value) {
        this.fromOrganizationReference = value;
    }

    /**
     * Gets the value of the moveWorkersByOrganizationPositionData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moveWorkersByOrganizationPositionData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoveWorkersByOrganizationPositionData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MoveWorkersByOrganizationPositionDataType }
     * 
     * 
     */
    public List<MoveWorkersByOrganizationPositionDataType> getMoveWorkersByOrganizationPositionData() {
        if (moveWorkersByOrganizationPositionData == null) {
            moveWorkersByOrganizationPositionData = new ArrayList<MoveWorkersByOrganizationPositionDataType>();
        }
        return this.moveWorkersByOrganizationPositionData;
    }

    /**
     * Gets the value of the toOrganizationReference property.
     * 
     * @return
     *     possible object is
     *     {@link StaffObjectType }
     *     
     */
    public StaffObjectType getToOrganizationReference() {
        return toOrganizationReference;
    }

    /**
     * Sets the value of the toOrganizationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaffObjectType }
     *     
     */
    public void setToOrganizationReference(StaffObjectType value) {
        this.toOrganizationReference = value;
    }

}
