//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 05:00:45 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.staffing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Wrapper element for the Freeze Position business process data including the position to close and the event data.
 * 
 * <p>Java class for Position_Group_Freeze_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Position_Group_Freeze_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Position_Reference" type="{urn:com.workday/bsvc}Position_RestrictionsObjectType"/&gt;
 *         &lt;element name="Freeze_Event_Data" type="{urn:com.workday/bsvc}Position_Group_Freeze_Event_DataType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position_Group_Freeze_DataType", propOrder = {
    "positionReference",
    "freezeEventData"
})
public class PositionGroupFreezeDataType {

    @XmlElement(name = "Position_Reference", required = true)
    protected PositionRestrictionsObjectType positionReference;
    @XmlElement(name = "Freeze_Event_Data", required = true)
    protected PositionGroupFreezeEventDataType freezeEventData;

    /**
     * Gets the value of the positionReference property.
     * 
     * @return
     *     possible object is
     *     {@link PositionRestrictionsObjectType }
     *     
     */
    public PositionRestrictionsObjectType getPositionReference() {
        return positionReference;
    }

    /**
     * Sets the value of the positionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionRestrictionsObjectType }
     *     
     */
    public void setPositionReference(PositionRestrictionsObjectType value) {
        this.positionReference = value;
    }

    /**
     * Gets the value of the freezeEventData property.
     * 
     * @return
     *     possible object is
     *     {@link PositionGroupFreezeEventDataType }
     *     
     */
    public PositionGroupFreezeEventDataType getFreezeEventData() {
        return freezeEventData;
    }

    /**
     * Sets the value of the freezeEventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionGroupFreezeEventDataType }
     *     
     */
    public void setFreezeEventData(PositionGroupFreezeEventDataType value) {
        this.freezeEventData = value;
    }

}
