ALTER TABLE COI_INT_STAGE_AWARD_PERSON 
ADD COLUMN DISCLOSURE_REQUIRED_FLAG VARCHAR(20) AFTER STATUS;


ALTER TABLE COI_INT_STAGE_AWARD 
ADD COLUMN DISCLOSURE_VALIDATION_FLAG VARCHAR(20) AFTER SRC_SYS_UPDATED_BY;
