
DROP PROCEDURE IF EXISTS GET_COI_DISCL_REVIEW_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_GENERAL_DETAILS;


\. ./Procedures/GET_COI_DISCL_REVIEW_DETAILS.sql
\. ./Procedures/GET_COI_DISCL_GENERAL_DETAILS.sql
