
DROP PROCEDURE IF EXISTS GET_COI_DISCL_REVIEW_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_DISCL_GENERAL_DETAILS;
DROP PROCEDURE IF EXISTS GET_APPROVERS_FOR_ROLE_TYPE;


\. ./Procedures/GET_COI_DISCL_REVIEW_DETAILS.sql
\. ./Procedures/GET_COI_DISCL_GENERAL_DETAILS.sql
\. ./Procedures/GET_APPROVERS_FOR_ROLE_TYPE.sql;
