DROP FUNCTION IF EXISTS COI_INT_PROJECT_DISCL_STATUS
DROP PROCEDURE IF EXISTS GET_COI_DISCL_REVIEW_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_PROJECT_PRSN_DISCL_STATUS;

\. ./Procedures/COI_INT_PROJECT_DISCL_STATUS.sql
\. ./Procedures/GET_COI_DISCL_REVIEW_DETAILS.sql
\. ./Procedures/COI_INT_PROJECT_PRSN_DISCL_STATUS.sql

