
ALTER TABLE `MQ_EXCEPTION_LOG` CHANGE COLUMN `ERROR_MESSAGE` `ERROR_MESSAGE` VARCHAR(255) NULL DEFAULT NULL ;
ALTER TABLE `MQ_EXCEPTION_LOG` ADD COLUMN `EVENT_TYPE` VARCHAR(3) NULL AFTER `USER_TYPE`;
ALTER TABLE `MQ_EXCEPTION_LOG` ADD COLUMN `TRIGGER_TYPE` VARCHAR(25) NULL AFTER `EVENT_TYPE`;

ALTER TABLE `mq_router_configuration` RENAME TO  `MQ_ROUTER_ACTION_CONFIGURATION` ;
ALTER TABLE `MQ_ROUTER_ACTION_CONFIGURATION` CHANGE COLUMN `id` `MQ_ROUTER_ACTION_CONFIG_ID` INT NOT NULL AUTO_INCREMENT;




