INSERT INTO `eps_prop_person_role` (`UNIT_DETAILS_REQUIRED`, `PROP_PERSON_ROLE_ID`, `DESCRIPTION`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `CERTIFICATION_REQUIRED`, `PROP_PERSON_ROLE_CODE`, `SPONSOR_HIERARCHY_NAME`, `READ_ONLY_ROLE`, `IS_MULTI_PI`, `SORT_ID`, `IS_ACTIVE`, `SHOW_PROJECT_ROLE`, `INCLUDE_IN_CURRENT_AND_PENDING`)
VALUES ('N', '8', 'PI/Multiple', now(), 'quickstart', 'Y', 'MPI', 'DEFAULT', 'N', 'D', '2', 'Y', 'N', 'N');

UPDATE `eps_prop_person_role` SET `SORT_ID` = '9' WHERE (`PROP_PERSON_ROLE_ID` = '9');
