
ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON ADD COLUMN STATUS VARCHAR(1) DEFAULT 'A' AFTER PERCENTAGE_OF_EFFORT;
ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON ADD COLUMN CERTIFICATION_FLAG VARCHAR(20) DEFAULT NULL AFTER STATUS;
ALTER TABLE COI_INT_STAGE_DEV_PROPOSAL_PERSON ADD COLUMN DISCLOSURE_REQUIRED_FLAG VARCHAR(20) DEFAULT NULL AFTER CERTIFICATION_FLAG;

DROP TABLE IF EXISTS coi_int_stage_proposal_person;
DROP TABLE IF EXISTS coi_int_stage_proposal;
DROP TABLE IF EXISTS coi_int_stage_award_person;
DROP TABLE IF EXISTS coi_int_stage_award;


CREATE TABLE COI_INT_STAGE_AWARD (
  STAGE_AWARD_ID int NOT NULL AUTO_INCREMENT,
  PROJECT_ID varchar(12) NOT NULL,
  PROJECT_NUMBER varchar(12) NOT NULL,
  PARENT_PROJECT_NUMBER varchar(12) DEFAULT NULL,
  ROOT_PROJECT_NUMBER varchar(12) DEFAULT NULL,
  VERSION_NUMBER int NOT NULL,
  ACCOUNT_NUMBER varchar(100) DEFAULT NULL,
  SPONSOR_GRANT_NUMBER varchar(70) DEFAULT NULL,
  LEAD_UNIT_NUMBER varchar(8) DEFAULT NULL,
  LEAD_UNIT_NAME varchar(200) DEFAULT NULL,
  PROJECT_START_DATE date DEFAULT NULL,
  PROJECT_END_DATE date DEFAULT NULL,
  PROJECT_TYPE_CODE varchar(8) DEFAULT NULL,
  PROJECT_TYPE varchar(100) DEFAULT NULL,
  TITLE varchar(1000) DEFAULT NULL,
  PROJECT_STATUS_CODE VARCHAR(12) DEFAULT NULL,
  PROJECT_STATUS varchar(100) DEFAULT NULL,
  SPONSOR_CODE varchar(10) DEFAULT NULL,
  SPONSOR_NAME varchar(200) DEFAULT NULL,
  PRIME_SPONSOR_CODE varchar(10) DEFAULT NULL,
  PRIME_SPONSOR_NAME varchar(200) DEFAULT NULL,
  ANTICIPATED_TOTAL decimal(12,2) DEFAULT NULL,
  OBLIGATED_TOTAL decimal(12,2) DEFAULT NULL,
  DOCUMENT_URL text,
  FIRST_FED_TIMESTAMP datetime DEFAULT NULL,
  LAST_FED_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATE_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATED_BY varchar(40) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_VALUE varchar(255) DEFAULT NULL,
  PRIMARY KEY (STAGE_AWARD_ID),
  INDEX idx_project_number (PROJECT_NUMBER)  
);

CREATE TABLE COI_INT_STAGE_AWARD_PERSON (
  PROJECT_NUMBER varchar(12) NOT NULL,
  KEY_PERSON_ROLE_CODE int NOT NULL,
  KEY_PERSON_ROLE_NAME varchar(25) NOT NULL,
  KEY_PERSON_ID varchar(40) NOT NULL,
  KEY_PERSON_NAME varchar(90) DEFAULT NULL,
  STATUS varchar(1) DEFAULT NULL,
  PERCENT_OF_EFFORT decimal(5,2) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  INDEX idx_key_person_id (KEY_PERSON_ID),
  INDEX idx_project_number (PROJECT_NUMBER),
  PRIMARY KEY (`PROJECT_NUMBER`,`KEY_PERSON_ID`)
);

CREATE TABLE COI_INT_STAGE_PROPOSAL (
  STAGE_PROPOSAL_ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROJECT_ID varchar(12) NOT NULL,
  PROJECT_NUMBER varchar(12) NOT NULL,
  VERSION_NUMBER int NOT NULL,
  LINKED_AWARD_PROJECT_NUMBER varchar(12) DEFAULT NULL,
  SPONSOR_GRANT_NUMBER varchar(70) DEFAULT NULL,
  LEAD_UNIT_NUMBER varchar(8) DEFAULT NULL,
  LEAD_UNIT_NAME varchar(200) DEFAULT NULL,
  PROJECT_START_DATE date DEFAULT NULL,
  PROJECT_END_DATE date DEFAULT NULL,
  PROJECT_TYPE_CODE varchar(12) DEFAULT NULL, 
  PROJECT_TYPE varchar(100) DEFAULT NULL,
  TITLE varchar(1000) DEFAULT NULL,
  PROJECT_STATUS_CODE VARCHAR(12) DEFAULT NULL,
  PROJECT_STATUS varchar(100) DEFAULT NULL,
  SPONSOR_CODE varchar(10) DEFAULT NULL,
  SPONSOR_NAME varchar(200) DEFAULT NULL,
  PRIME_SPONSOR_CODE varchar(10) DEFAULT NULL,
  PRIME_SPONSOR_NAME varchar(200) DEFAULT NULL,
  DOCUMENT_URL text,
  FIRST_FED_TIMESTAMP datetime DEFAULT NULL,
  LAST_FED_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATE_TIMESTAMP datetime DEFAULT NULL,
  SRC_SYS_UPDATED_BY varchar(40) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_4_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_5_VALUE varchar(255) DEFAULT NULL,
  INDEX idx_project_number (PROJECT_NUMBER)
);

CREATE TABLE coi_int_stage_proposal_person (
  PROJECT_NUMBER varchar(12) NOT NULL,
  KEY_PERSON_ROLE_CODE int NOT NULL,
  KEY_PERSON_ROLE_NAME varchar(25) NOT NULL,
  KEY_PERSON_ID varchar(40) NOT NULL,
  KEY_PERSON_NAME varchar(90) DEFAULT NULL,
  STATUS varchar(1) DEFAULT NULL,
  PERCENT_OF_EFFORT decimal(5,2) DEFAULT NULL,
  ATTRIBUTE_1_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_1_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_2_VALUE varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_LABEL varchar(255) DEFAULT NULL,
  ATTRIBUTE_3_VALUE varchar(255) DEFAULT NULL,
  INDEX idx_key_person_id (KEY_PERSON_ID),
  INDEX idx_project_number (PROJECT_NUMBER),
  PRIMARY KEY (`PROJECT_NUMBER`,`KEY_PERSON_ID`)
);
