


DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST_COUNT;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION;
DROP FUNCTION IF EXISTS FN_CHK_DISCL_SYNC_FLAG_REQ_IN_IP;
DROP FUNCTION IF EXISTS FN_CHK_DISCL_SYNC_FLAG_REQ_IN_AWD;
DROP PROCEDURE IF EXISTS COI_SYNC_REMOVE_DEACTIVATED_PROJECTS;

\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST_COUNT.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_PERSON_ENTITIES.sql
\. ./Procedures/COI_EVALUATE_VALIDATION.sql
\. ./Procedures/FN_CHK_DISCL_SYNC_FLAG_REQ_IN_IP.sql
\. ./Procedures/FN_CHK_DISCL_SYNC_FLAG_REQ_IN_AWD.sql
\. ./Procedures/COI_SYNC_REMOVE_DEACTIVATED_PROJECTS.sql

