
DROP FUNCTION IF EXISTS FN_CHK_DISCL_SYNC_FLAG_REQ_IN_IP;
DROP FUNCTION IF EXISTS FN_CHK_DISCL_SYNC_FLAG_REQ_IN_AWD;
DROP FUNCTION IF EXISTS FN_EVAL_DISCLOSURE_STATUS;
DROP FUNCTION IF EXISTS FN_INT_CAN_CREATE_PROP_DISCL;

DROP PROCEDURE IF EXISTS COI_DISCL_ENT_PROJ_DETAILS;
DROP PROCEDURE IF EXISTS COI_DISCL_PROJ_ENTITY_INSERTION;
DROP PROCEDURE IF EXISTS COI_EVALUATE_VALIDATION;
DROP PROCEDURE IF EXISTS COI_SYNC_DISCLOSURE_RISK;
DROP PROCEDURE IF EXISTS COI_SYNC_FCOI_DISCLOSURE;
DROP PROCEDURE IF EXISTS COI_SYNC_INSERT_DISCL_PROJECTS;
DROP PROCEDURE IF EXISTS COI_SYNC_REMOVE_DEACTIVATED_PROJECTS;
DROP PROCEDURE IF EXISTS COI_SYNC_UPDATE_DISCL_INTEG_UPDATES;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST;
DROP PROCEDURE IF EXISTS GET_ALL_SYSTEM_ENTITY_LIST_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_HISTORY;
DROP PROCEDURE IF EXISTS GET_COI_PERSON_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS GET_COI_PROJECTS;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_PROJECTS;
DROP PROCEDURE IF EXISTS GET_PERSON_ENTITIES;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP PROCEDURE IF EXISTS VALIDATE_PROJECT_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_ENTITY_TAB_STATUS;
DROP PROCEDURE IF EXISTS COI_INT_GET_ENTITY_DETAILS;
DROP PROCEDURE IF EXISTS COI_INT_KC_SPON_ORG_RESPONSE;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_HEADER;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_INDUSTRY_CATE;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_REGISTRATION;
DROP PROCEDURE IF EXISTS ENRICH_ENTITY_TELEPHONE;
DROP PROCEDURE IF EXISTS ENRICH_TRADE_STYLE_NAME;
DROP PROCEDURE IF EXISTS ENRICH_FOREIGN_NAME;
DROP PROCEDURE IF EXISTS CLENSEMATCH_ENT_INFO_BY_DUNS;


\. ./Functions/FN_CHK_DISCL_SYNC_FLAG_REQ_IN_IP.sql
\. ./Functions/FN_CHK_DISCL_SYNC_FLAG_REQ_IN_AWD.sql
\. ./Functions/FN_EVAL_DISCLOSURE_STATUS.sql
\. ./Functions/FN_INT_CAN_CREATE_PROP_DISCL.sql

\. ./Procedures/COI_DISCL_ENT_PROJ_DETAILS.sql
\. ./Procedures/COI_DISCL_PROJ_ENTITY_INSERTION.sql
\. ./Procedures/COI_EVALUATE_VALIDATION.sql
\. ./Procedures/COI_SYNC_DISCLOSURE_RISK.sql
\. ./Procedures/COI_SYNC_FCOI_DISCLOSURE.sql
\. ./Procedures/COI_SYNC_INSERT_DISCL_PROJECTS.sql
\. ./Procedures/COI_SYNC_REMOVE_DEACTIVATED_PROJECTS.sql
\. ./Procedures/COI_SYNC_UPDATE_DISCL_INTEG_UPDATES.sql
\. ./Procedures/COI_VALIDATE_DISCLOSURE_CONFLICTS.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST.sql
\. ./Procedures/GET_ALL_SYSTEM_ENTITY_LIST_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_ADMIN_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./Procedures/GET_COI_PERSON_ENTITY_DETAILS.sql
\. ./Procedures/GET_COI_PROJECTS.sql
\. ./Procedures/GET_DISCLOSURE_PROJECTS.sql
\. ./Procedures/GET_PERSON_ENTITIES.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Procedures/VALIDATE_PROJECT_DISCLOSURE.sql
\. ./Procedures/GET_COI_TRAVEL_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_ENTITY_TAB_STATUS.sql
\. ./Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./Procedures/COI_INT_GET_ENTITY_DETAILS.sql
\. ./Procedures/COI_INT_KC_SPON_ORG_RESPONSE.sql
\. ./Procedures/ENRICH_ENTITY_HEADER.sql
\. ./Procedures/ENRICH_ENTITY_INDUSTRY_CATE.sql
\. ./Procedures/ENRICH_ENTITY_REGISTRATION.sql
\. ./Procedures/ENRICH_ENTITY_TELEPHONE.sql
\. ./Procedures/ENRICH_TRADE_STYLE_NAME.sql
\. ./Procedures/ENRICH_FOREIGN_NAME.sql
\. ./Procedures/CLENSEMATCH_ENT_INFO_BY_DUNS.sql