
DROP PROCEDURE IF EXISTS COI_UPD_ANS_TO_NEW_QUEST_VERSN;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS INSERT_OPA_DISCLOSURE_DETAILS;
DROP PROCEDURE IF EXISTS PROC_SYNC_OPA_PER_ENTITY;
DROP PROCEDURE IF EXISTS SYNC_SFIS_AND_DISCLOSURE;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP PROCEDURE IF EXISTS GET_PROJECT_OVERVIEW;
DROP FUNCTION IF EXISTS FN_EVAL_DISCLOSURE_STATUS;
DROP PROCEDURE IF EXISTS GET_PERSON_HAS_PERMISSION;
DROP PROCEDURE IF EXISTS GET_DISCLOSURE_RELATIONS;

\. ./Procedures/COI_UPD_ANS_TO_NEW_QUEST_VERSN.sql
\. ./Procedures/COI_VALIDATE_DISCLOSURE_CONFLICTS.sql
\. ./Procedures/INSERT_OPA_DISCLOSURE_DETAILS.sql
\. ./Procedures/PROC_SYNC_OPA_PER_ENTITY.sql
\. ./Procedures/SYNC_SFIS_AND_DISCLOSURE.sql
\. ./Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./Procedures/GET_PROJECT_OVERVIEW.sql
\. ./Functions/FN_EVAL_DISCLOSURE_STATUS.sql
\. ./Procedures/GET_PERSON_HAS_PERMISSION.sql
\. ./Procedures/GET_DISCLOSURE_RELATIONS.sql;
