
DROP PROCEDURE IF EXISTS COI_UPD_ANS_TO_NEW_QUEST_VERSN;
DROP PROCEDURE IF EXISTS COI_VALIDATE_DISCLOSURE_CONFLICTS;
DROP PROCEDURE IF EXISTS INSERT_OPA_DISCLOSURE_DETAILS;
DROP PROCEDURE IF EXISTS PROC_SYNC_OPA_PER_ENTITY;
DROP PROCEDURE IF EXISTS SYNC_SFIS_AND_DISCLOSURE;


\. ./Procedures/COI_UPD_ANS_TO_NEW_QUEST_VERSN.sql
\. ./Procedures/COI_VALIDATE_DISCLOSURE_CONFLICTS.sql
\. ./Procedures/INSERT_OPA_DISCLOSURE_DETAILS.sql
\. ./Procedures/PROC_SYNC_OPA_PER_ENTITY.sql
\. ./Procedures/SYNC_SFIS_AND_DISCLOSURE.sql
