import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import {HttpClient} from '@angular/common/http';
import {CommonService} from '../common/services/common.service';

@Injectable()

export class OpaService {

// tslint:disable:max-line-length

    dummyData = {
        'applicableFormsBuilderIds': [1],
        'primaryForm': {
            'formBuilderId': 1,
            'formBuilderNumber': '1001',
            'formName': 'Testing Form ',
            'formSections': [
                {
                    'sectionId': 111,
                    'sectionName': 'Staff Outside Professional',
                    'sectionOrder': 1,
                    'sectionDescription': 'This is a dummy content used for testing of the UI development for the same',
                    'sectionBusinessRule': null,
                    'sectionHelpText': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'sectionHeader': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'sectionFooter': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'sectionComponent': [
                        {
                            'componentId': 1,
                            'sectionId': 111,
                            'componentDescription': null,
                            'componentType': 'QN',
                            'componentRefId': '1055',
                            'componentData': '',
                            'componentHeader': 'Header Instruction',
                            'componentFooter': 'Footer Instruction',
                            'programmedElement': null,
                            'questionnaire': {
                                'applicableQuestionnaire': null,
                                'questionnaireId': 1055,
                                'moduleItemKey': null,
                                'moduleSubItemKey': null,
                                'moduleItemCode': null,
                                'moduleSubItemCode': null,
                                'questionnaireAnswerHeaderId': null,
                                'questionnaireAnsAttachmentId': null,
                                'questionnaireCompleteFlag': null,
                                'actionUserId': null,
                                'actionPersonId': null,
                                'actionPersonName': null,
                                'acType': null,
                                'questionnaireName': null,
                                'newQuestionnaireVersion': false,
                                'questionEditted': false,
                                'questionnaireList': null,
                                'questionnaireGroup': null,
                                'header': {
                                    'TRIGGER_POST_EVALUATION': null,
                                    'QUESTIONNAIRE_VERSION': 3,
                                    'UPDATE_USER': 'willsmith',
                                    'ANS_UPDATE_TIMESTAMP': null,
                                    'ANS_PERSON_FULL_NAME': null,
                                    'QUESTIONNAIRE_DESCRIPTION': null,
                                    'IS_FINAL': true,
                                    'QUESTIONNAIRE_NUMBER': 1020,
                                    'QUESTIONNAIRE_ID': 1055,
                                    'QUEST_GROUP_TYPE_CODE': null,
                                    'AC_TYPE': 'U',
                                    'QUESTIONNAIRE_NAME': 'Ethics Review (Human Subjects)',
                                    'UPDATE_TIMESTAMP': '2022-05-04T16:08:57.000+00:00'
                                },
                                'questionnaire': {
                                    'maxGroupNumber': null,
                                    'questions': [
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 242,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': 'Y',
                                            'QUESTION': 'Are you using Human Subjects in Research ?',
                                            'SHOW_QUESTION': true,
                                            'GROUP_NAME': 'G0',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 1,
                                            'QUESTION_ID': 1471,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Y/N',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': null
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 243,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': null,
                                            'QUESTION': 'Please specify your other researches in which used human subjects are used, If Any',
                                            'GROUP_NAME': 'G4',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': '<p>Specify multiple protocol numbers comma seperated</p>',
                                            'SORT_ORDER': 2,
                                            'QUESTION_ID': 1472,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Text',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1471
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 244,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': 'Y',
                                            'QUESTION': 'Did you apply for IRB Approval ?',
                                            'GROUP_NAME': 'G1',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 3,
                                            'QUESTION_ID': 1473,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Y/N',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1471
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 245,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': null,
                                            'QUESTION': 'Please specify a date in which you will apply for IRB Approval',
                                            'GROUP_NAME': 'G3',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 4,
                                            'QUESTION_ID': 1474,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Date',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1473
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 246,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': null,
                                            'QUESTION': 'Please specify the IRB Approval Number',
                                            'GROUP_NAME': 'G2',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 5,
                                            'QUESTION_ID': 1475,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Text',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1473
                                        }
                                    ],
                                    'conditions': [
                                        {
                                            'QUESTION_CONDITION_ID': 1090,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G1',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1471,
                                            'CONDITION_VALUE': 'Yes'
                                        },
                                        {
                                            'QUESTION_CONDITION_ID': 1091,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G2',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1473,
                                            'CONDITION_VALUE': 'Yes'
                                        },
                                        {
                                            'QUESTION_CONDITION_ID': 1092,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G3',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1473,
                                            'CONDITION_VALUE': 'No'
                                        },
                                        {
                                            'QUESTION_CONDITION_ID': 1093,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G4',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1471,
                                            'CONDITION_VALUE': 'No'
                                        }
                                    ],
                                    'options': [
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1987,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1471,
                                            'OPTION_LABEL': 'Yes',
                                            'REQUIRE_EXPLANATION': 'N'
                                        },
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1988,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1471,
                                            'OPTION_LABEL': 'No',
                                            'REQUIRE_EXPLANATION': 'N'
                                        },
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1989,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1473,
                                            'OPTION_LABEL': 'Yes',
                                            'REQUIRE_EXPLANATION': 'N'
                                        },
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1990,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1473,
                                            'OPTION_LABEL': 'No',
                                            'REQUIRE_EXPLANATION': 'N'
                                        }
                                    ],
                                    'deleteList': null,
                                    'questionnaireQuestions': null,
                                    'questionnaireConditions': null,
                                    'questionnaireOptions': null,
                                    'questionnaireAnswers': null,
                                    'quesAttachmentList': null,
                                    'lookUpDetails': null
                                },
                                'usage': null,
                                'fileName': null,
                                'fileContent': null,
                                'length': null,
                                'remaining': null,
                                'fileTimestamp': null,
                                'contentType': null,
                                'personId': null,
                                'multipartFile': null,
                                'moduleList': null,
                                'isInserted': null,
                                'updateTimestamp': null,
                                'copyModuleItemKey': null,
                                'questionnaireNumbers': null,
                                'lookUpDetails': null,
                                'newQuestionnaireId': null,
                                'moduleSubItemCodes': [],
                                'questionnaireBusinessRules': null,
                                'ruleId': null,
                                'rulePassed': null,
                                'questionnaireMode': null,
                                'copyInActiveQuestionAnswers': false
                            },
                            'customElement': null,
                            'componentOrder': 1
                        },
                        {
                            'componentId': 2,
                            'sectionId': 111,
                            'componentDescription': null,
                            'componentType': 'CE',
                            'componentRefId': '49',
                            'componentData': '',
                            'componentHeader': 'Header Instruction',
                            'componentFooter': 'Footer Instruction',
                            'programmedElement': null,
                            'questionnaire': null,
                            'customElement': {
                                'customDataElement': {
                                    'customElementId': 49,
                                    'columnId': 41,
                                    'columnVersionNumber': 1,
                                    'columnLabel': 'Level 2 Sup Org',
                                    'dataType': '7',
                                    'customDataTypes': {
                                        'dataTypeCode': '7',
                                        'description': 'Autosuggest',
                                        'updateTimestamp': '2020-03-18T09:17:16.000+00:00',
                                        'updateUser': 'admin',
                                        'isActive': true
                                    },
                                    'dataLength': null,
                                    'defaultValue': 'unitNumber',
                                    'isLatestVesrion': 'Y',
                                    'hasLookup': false,
                                    'lookupWindow': '',
                                    'lookupArgument': 'unitName',
                                    'isActive': 'Y',
                                    'updateUser': 'quickstart',
                                    'updateTimestamp': '2021-03-17T11:27:12.000+00:00',
                                    'customElementName': 'Level_2_Sup_Org',
                                    'customDataElementUsage': [
                                        {
                                            'customElementUsageId': 106,
                                            'moduleCode': 1,
                                            'module': {
                                                'moduleCode': 1,
                                                'description': 'Award',
                                                'updateTimestamp': '2019-05-31T10:51:02.000+00:00',
                                                'updateUser': 'admin',
                                                'isActive': true
                                            },
                                            'isRequired': 'N',
                                            'updateUser': 'quickstart',
                                            'updateTimestamp': '2021-03-25T13:37:10.000+00:00',
                                            'orderNumber': null,
                                            'acType': 'U'
                                        }
                                    ],
                                    'acType': null
                                },
                                'customDataElements': null,
                                'responseMessage': null,
                                'customDataElementId': 49,
                                'customDataTypes': null,
                                'elementOptions': [],
                                'customResponses': null,
                                'moduleCode': null,
                                'customElements': null,
                                'updateUser': null,
                                'updateTimestamp': null,
                                'moduleItemKey': null,
                                'applicableModules': null,
                                'deleteOptions': null,
                                'isDataChange': null,
                                'dataTypeCode': null,
                                'systemLookups': null,
                                'lookUps': null,
                                'elementAnswered': true
                            },
                            'componentOrder': 2
                        }
                    ]
                },
                {
                    'sectionId': 112,
                    'sectionName': 'Staff Data Record',
                    'sectionOrder': 1,
                    'sectionDescription': '',
                    'sectionBusinessRule': null,
                    'sectionHelpText': '',
                    'sectionHeader': '',
                    'sectionFooter': '',
                    'sectionComponent': [
                        {
                            'componentId': 3,
                            'sectionId': 112,
                            'componentDescription': null,
                            'componentType': 'QN',
                            'componentRefId': '1055',
                            'componentData': '',
                            'componentHeader': 'Header Instruction',
                            'componentFooter': 'Footer Instruction',
                            'programmedElement': null,
                            'questionnaire': {
                                'applicableQuestionnaire': null,
                                'questionnaireId': 1055,
                                'moduleItemKey': null,
                                'moduleSubItemKey': null,
                                'moduleItemCode': null,
                                'moduleSubItemCode': null,
                                'questionnaireAnswerHeaderId': null,
                                'questionnaireAnsAttachmentId': null,
                                'questionnaireCompleteFlag': null,
                                'actionUserId': null,
                                'actionPersonId': null,
                                'actionPersonName': null,
                                'acType': null,
                                'questionnaireName': null,
                                'newQuestionnaireVersion': false,
                                'questionEditted': false,
                                'questionnaireList': null,
                                'questionnaireGroup': null,
                                'header': {
                                    'TRIGGER_POST_EVALUATION': null,
                                    'QUESTIONNAIRE_VERSION': 3,
                                    'UPDATE_USER': 'willsmith',
                                    'ANS_UPDATE_TIMESTAMP': null,
                                    'ANS_PERSON_FULL_NAME': null,
                                    'QUESTIONNAIRE_DESCRIPTION': null,
                                    'IS_FINAL': true,
                                    'QUESTIONNAIRE_NUMBER': 1020,
                                    'QUESTIONNAIRE_ID': 1055,
                                    'QUEST_GROUP_TYPE_CODE': null,
                                    'AC_TYPE': 'U',
                                    'QUESTIONNAIRE_NAME': 'Ethics Review (Human Subjects)',
                                    'UPDATE_TIMESTAMP': '2022-05-04T16:08:57.000+00:00'
                                },
                                'questionnaire': {
                                    'maxGroupNumber': null,
                                    'questions': [
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 242,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': 'Y',
                                            'QUESTION': 'Are you using Human Subjects in Research ?',
                                            'SHOW_QUESTION': true,
                                            'GROUP_NAME': 'G0',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 1,
                                            'QUESTION_ID': 1471,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Y/N',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': null
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 243,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': null,
                                            'QUESTION': 'Please specify your other researches in which used human subjects are used, If Any',
                                            'GROUP_NAME': 'G4',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': '<p>Specify multiple protocol numbers comma seperated</p>',
                                            'SORT_ORDER': 2,
                                            'QUESTION_ID': 1472,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Text',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1471
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 244,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': 'Y',
                                            'QUESTION': 'Did you apply for IRB Approval ?',
                                            'GROUP_NAME': 'G1',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 3,
                                            'QUESTION_ID': 1473,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Y/N',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1471
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 245,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': null,
                                            'QUESTION': 'Please specify a date in which you will apply for IRB Approval',
                                            'GROUP_NAME': 'G3',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 4,
                                            'QUESTION_ID': 1474,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Date',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1473
                                        },
                                        {
                                            'LOOKUP_TYPE': null,
                                            'LOOKUP_FIELD': null,
                                            'ANSWER_LENGTH': null,
                                            'RULE_ID': null,
                                            'GROUP_LABEL': null,
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_NUMBER': 246,
                                            'LOOKUP_NAME': null,
                                            'HAS_CONDITION': null,
                                            'QUESTION': 'Please specify the IRB Approval Number',
                                            'GROUP_NAME': 'G2',
                                            'HELP_LINK': null,
                                            'QUESTION_VERSION_NUMBER': 3,
                                            'DESCRIPTION': null,
                                            'SORT_ORDER': 5,
                                            'QUESTION_ID': 1475,
                                            'ANSWERS': {
                                                '1': ''
                                            },
                                            'ANSWER_TYPE': 'Text',
                                            'NO_OF_ANSWERS': 1,
                                            'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                                            'PARENT_QUESTION_ID': 1473
                                        }
                                    ],
                                    'conditions': [
                                        {
                                            'QUESTION_CONDITION_ID': 1090,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G1',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1471,
                                            'CONDITION_VALUE': 'Yes'
                                        },
                                        {
                                            'QUESTION_CONDITION_ID': 1091,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G2',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1473,
                                            'CONDITION_VALUE': 'Yes'
                                        },
                                        {
                                            'QUESTION_CONDITION_ID': 1092,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G3',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1473,
                                            'CONDITION_VALUE': 'No'
                                        },
                                        {
                                            'QUESTION_CONDITION_ID': 1093,
                                            'CONDITION_TYPE': 'EQUALS',
                                            'GROUP_NAME': 'G4',
                                            'UPDATE_USER': 'willsmith',
                                            'QUESTION_ID': 1471,
                                            'CONDITION_VALUE': 'No'
                                        }
                                    ],
                                    'options': [
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1987,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1471,
                                            'OPTION_LABEL': 'Yes',
                                            'REQUIRE_EXPLANATION': 'N'
                                        },
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1988,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1471,
                                            'OPTION_LABEL': 'No',
                                            'REQUIRE_EXPLANATION': 'N'
                                        },
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1989,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1473,
                                            'OPTION_LABEL': 'Yes',
                                            'REQUIRE_EXPLANATION': 'N'
                                        },
                                        {
                                            'EXPLANTION_LABEL': null,
                                            'QUESTION_OPTION_ID': 1990,
                                            'OPTION_NUMBER': null,
                                            'QUESTION_ID': 1473,
                                            'OPTION_LABEL': 'No',
                                            'REQUIRE_EXPLANATION': 'N'
                                        }
                                    ],
                                    'deleteList': null,
                                    'questionnaireQuestions': null,
                                    'questionnaireConditions': null,
                                    'questionnaireOptions': null,
                                    'questionnaireAnswers': null,
                                    'quesAttachmentList': null,
                                    'lookUpDetails': null
                                },
                                'usage': null,
                                'fileName': null,
                                'fileContent': null,
                                'length': null,
                                'remaining': null,
                                'fileTimestamp': null,
                                'contentType': null,
                                'personId': null,
                                'multipartFile': null,
                                'moduleList': null,
                                'isInserted': null,
                                'updateTimestamp': null,
                                'copyModuleItemKey': null,
                                'questionnaireNumbers': null,
                                'lookUpDetails': null,
                                'newQuestionnaireId': null,
                                'moduleSubItemCodes': [],
                                'questionnaireBusinessRules': null,
                                'ruleId': null,
                                'rulePassed': null,
                                'questionnaireMode': null,
                                'copyInActiveQuestionAnswers': false
                            },
                            'customElement': null,
                            'componentOrder': 1
                        },
                        {
                            'componentId': 4,
                            'sectionId': 112,
                            'componentDescription': null,
                            'componentType': 'RT',
                            'componentRefId': null,
                            'componentData': '<h1> Hello </h1>',
                            'componentHeader': 'Header Instruction',
                            'componentFooter': 'Footer Instruction',
                            'programmedElement': null,
                            'questionnaire': null,
                            'customElement': null,
                            'componentOrder': 2
                        },
                        {
                            'componentId': 4,
                            'sectionId': 112,
                            'componentDescription': null,
                            'componentType': 'HL',
                            'componentRefId': null,
                            'componentData': 'background:#d0d0d0;height:5px',
                            'componentHeader': 'Header Instruction',
                            'componentFooter': 'Footer Instruction',
                            'programmedElement': null,
                            'questionnaire': null,
                            'customElement': null,
                            'componentOrder': 2
                        }
                    ]
                }
            ]
        }
    };

    dummy2 = {
        'applicableFormsBuilderIds': [1],
        'primaryForm': {
          'formBuilderId': 1,
          'formBuilderNumber': '1001',
          'formName': 'Testing Form  <--> ACTION TIME :  12639',
          'formSections': [
            {
              'sectionId': 111,
              'sectionName': 'Staff Outside Professional',
              'sectionOrder': 1,
              'sectionDescription': 'Staff Outside Professional',
              'sectionBusinessRule': null,
              'sectionHelpText': 'Hello this is the help text',
              'sectionHeader': 'This is the header instructions',
              'sectionFooter': 'This is the footer instructions',
              'sectionComponent': [
                {
                  'componentId': 1,
                  'sectionId': 111,
                  'componentDescription': null,
                  'componentType': 'QN',
                  'componentRefId': '1055',
                  'componentData': '',
                  'componentHeader': 'Header Instruction',
                  'componentFooter': 'Footer Instruction',
                  'programmedElement': null,
                  'questionnaire': {
                    'applicableQuestionnaire': null,
                    'questionnaireId': 1055,
                    'moduleItemKey': null,
                    'moduleSubItemKey': null,
                    'moduleItemCode': 23,
                    'moduleSubItemCode': 0,
                    'questionnaireAnswerHeaderId': null,
                    'questionnaireAnsAttachmentId': null,
                    'questionnaireCompleteFlag': null,
                    'actionUserId': null,
                    'actionPersonId': null,
                    'actionPersonName': null,
                    'acType': null,
                    'questionnaireName': null,
                    'newQuestionnaireVersion': false,
                    'questionEditted': false,
                    'questionnaireList': null,
                    'questionnaireGroup': null,
                    'header': {
                      'TRIGGER_POST_EVALUATION': null,
                      'QUESTIONNAIRE_VERSION': 3,
                      'UPDATE_USER': 'willsmith',
                      'ANS_UPDATE_TIMESTAMP': null,
                      'ANS_PERSON_FULL_NAME': null,
                      'QUESTIONNAIRE_DESCRIPTION': null,
                      'IS_FINAL': true,
                      'QUESTIONNAIRE_NUMBER': 1020,
                      'QUESTIONNAIRE_ID': 1055,
                      'QUEST_GROUP_TYPE_CODE': null,
                      'AC_TYPE': 'U',
                      'QUESTIONNAIRE_NAME': 'Ethics Review (Human Subjects)',
                      'UPDATE_TIMESTAMP': '2022-05-04T16:08:57.000+00:00'
                    },
                    'questionnaire': {
                      'maxGroupNumber': null,
                      'questions': [
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 242,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': 'Y',
                          'QUESTION': 'Are you using Human Subjects in Research ?',
                          'SHOW_QUESTION': true,
                          'GROUP_NAME': 'G0',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 1,
                          'QUESTION_ID': 1471,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Y/N',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': null
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 243,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': null,
                          'QUESTION': 'Please specify your other researches in which used human subjects are used, If Any',
                          'GROUP_NAME': 'G4',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': '<p>Specify multiple protocol numbers comma separated</p>',
                          'SORT_ORDER': 2,
                          'QUESTION_ID': 1472,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Text',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1471
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 244,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': 'Y',
                          'QUESTION': 'Did you apply for IRB Approval ?',
                          'GROUP_NAME': 'G1',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 3,
                          'QUESTION_ID': 1473,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Y/N',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1471
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 245,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': null,
                          'QUESTION': 'Please specify a date in which you will apply for IRB Approval',
                          'GROUP_NAME': 'G3',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 4,
                          'QUESTION_ID': 1474,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Date',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1473
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 246,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': null,
                          'QUESTION': 'Please specify the IRB Approval Number',
                          'GROUP_NAME': 'G2',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 5,
                          'QUESTION_ID': 1475,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Text',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1473
                        }
                      ],
                      'conditions': [
                        {
                          'QUESTION_CONDITION_ID': 1090,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G1',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1471,
                          'CONDITION_VALUE': 'Yes'
                        },
                        {
                          'QUESTION_CONDITION_ID': 1091,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G2',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1473,
                          'CONDITION_VALUE': 'Yes'
                        },
                        {
                          'QUESTION_CONDITION_ID': 1092,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G3',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1473,
                          'CONDITION_VALUE': 'No'
                        },
                        {
                          'QUESTION_CONDITION_ID': 1093,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G4',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1471,
                          'CONDITION_VALUE': 'No'
                        }
                      ],
                      'options': [
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1987,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1471,
                          'OPTION_LABEL': 'Yes',
                          'REQUIRE_EXPLANATION': 'N'
                        },
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1988,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1471,
                          'OPTION_LABEL': 'No',
                          'REQUIRE_EXPLANATION': 'N'
                        },
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1989,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1473,
                          'OPTION_LABEL': 'Yes',
                          'REQUIRE_EXPLANATION': 'N'
                        },
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1990,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1473,
                          'OPTION_LABEL': 'No',
                          'REQUIRE_EXPLANATION': 'N'
                        }
                      ],
                      'deleteList': null,
                      'questionnaireQuestions': null,
                      'questionnaireConditions': null,
                      'questionnaireOptions': null,
                      'questionnaireAnswers': null,
                      'quesAttachmentList': null,
                      'lookUpDetails': null
                    },
                    'usage': null,
                    'fileName': null,
                    'fileContent': null,
                    'length': null,
                    'remaining': null,
                    'fileTimestamp': null,
                    'contentType': null,
                    'personId': null,
                    'multipartFile': null,
                    'moduleList': null,
                    'isInserted': null,
                    'updateTimestamp': null,
                    'copyModuleItemKey': null,
                    'questionnaireNumbers': null,
                    'lookUpDetails': null,
                    'newQuestionnaireId': null,
                    'moduleSubItemCodes': [],
                    'questionnaireBusinessRules': null,
                    'ruleId': null,
                    'rulePassed': null,
                    'questionnaireMode': null,
                    'copyInActiveQuestionAnswers': false
                  },
                  'customElement': null,
                  'componentOrder': 1
                },
                {
                  'componentId': 2,
                  'sectionId': 111,
                  'componentDescription': null,
                  'componentType': 'CE',
                  'componentRefId': '49',
                  'componentData': '',
                  'componentHeader': 'Header Instruction',
                  'componentFooter': 'Footer Instruction',
                  'programmedElement': null,
                  'questionnaire': null,
                  'customElement': {
                    'customDataElement': {
                      'customElementId': 49,
                      'columnId': 41,
                      'columnVersionNumber': 1,
                      'columnLabel': 'Level 2 Sup Org',
                      'dataType': '7',
                      'customDataTypes': {
                        'dataTypeCode': '7',
                        'description': 'Autosuggest',
                        'updateTimestamp': '2020-03-18T09:17:16.000+00:00',
                        'updateUser': 'admin',
                        'isActive': true
                      },
                      'dataLength': null,
                      'defaultValue': 'unitNumber',
                      'isLatestVesrion': 'Y',
                      'hasLookup': false,
                      'lookupWindow': '',
                      'lookupArgument': 'unitName',
                      'isActive': 'Y',
                      'updateUser': 'quickstart',
                      'updateTimestamp': '2021-03-17T11:27:12.000+00:00',
                      'customElementName': 'Level_2_Sup_Org',
                      'customDataElementUsage': [
                        {
                          'customElementUsageId': 106,
                          'moduleCode': 1,
                          'module': {
                            'moduleCode': 1,
                            'description': 'Award',
                            'updateTimestamp': '2019-05-31T10:51:02.000+00:00',
                            'updateUser': 'admin',
                            'isActive': true
                          },
                          'isRequired': 'N',
                          'updateUser': 'quickstart',
                          'updateTimestamp': '2021-03-25T13:37:10.000+00:00',
                          'orderNumber': null,
                          'acType': 'U'
                        }
                      ],
                      'acType': null
                    },
                    'customDataElements': null,
                    'responseMessage': null,
                    'customDataElementId': 49,
                    'customDataTypes': null,
                    'elementOptions': [],
                    'customResponses': null,
                    'moduleCode': 23,
                    'customElements': null,
                    'updateUser': null,
                    'updateTimestamp': null,
                    'moduleItemKey': null,
                    'applicableModules': null,
                    'deleteOptions': null,
                    'isDataChange': null,
                    'dataTypeCode': null,
                    'systemLookups': null,
                    'lookUps': null,
                    'elementAnswered': true,
                    'subModuleCode': 0,
                    'subModuleItemKey': null
                  },
                  'componentOrder': 2
                }
              ]
            },
            {
              'sectionId': 112,
              'sectionName': 'Staff Data Record',
              'sectionOrder': 2,
              'sectionDescription': 'Staff Data Record',
              'sectionBusinessRule': null,
              'sectionHelpText': 'Hello this is the help text',
              'sectionHeader': 'This is the header instructions',
              'sectionFooter': 'This is the footerinstructions',
              'sectionComponent': [
                {
                  'componentId': 3,
                  'sectionId': 112,
                  'componentDescription': null,
                  'componentType': 'QN',
                  'componentRefId': '1055',
                  'componentData': '',
                  'componentHeader': 'Header Instruction',
                  'componentFooter': 'Footer Instruction',
                  'programmedElement': null,
                  'questionnaire': {
                    'applicableQuestionnaire': null,
                    'questionnaireId': 1055,
                    'moduleItemKey': null,
                    'moduleSubItemKey': null,
                    'moduleItemCode': 23,
                    'moduleSubItemCode': 0,
                    'questionnaireAnswerHeaderId': null,
                    'questionnaireAnsAttachmentId': null,
                    'questionnaireCompleteFlag': null,
                    'actionUserId': null,
                    'actionPersonId': null,
                    'actionPersonName': null,
                    'acType': null,
                    'questionnaireName': null,
                    'newQuestionnaireVersion': false,
                    'questionEditted': false,
                    'questionnaireList': null,
                    'questionnaireGroup': null,
                    'header': {
                      'TRIGGER_POST_EVALUATION': null,
                      'QUESTIONNAIRE_VERSION': 3,
                      'UPDATE_USER': 'willsmith',
                      'ANS_UPDATE_TIMESTAMP': null,
                      'ANS_PERSON_FULL_NAME': null,
                      'QUESTIONNAIRE_DESCRIPTION': null,
                      'IS_FINAL': true,
                      'QUESTIONNAIRE_NUMBER': 1020,
                      'QUESTIONNAIRE_ID': 1055,
                      'QUEST_GROUP_TYPE_CODE': null,
                      'AC_TYPE': 'U',
                      'QUESTIONNAIRE_NAME': 'Ethics Review (Human Subjects)',
                      'UPDATE_TIMESTAMP': '2022-05-04T16:08:57.000+00:00'
                    },
                    'questionnaire': {
                      'maxGroupNumber': null,
                      'questions': [
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 242,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': 'Y',
                          'QUESTION': 'Are you using Human Subjects in Research ?',
                          'SHOW_QUESTION': true,
                          'GROUP_NAME': 'G0',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 1,
                          'QUESTION_ID': 1471,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Y/N',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': null
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 243,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': null,
                          'QUESTION': 'Please specify your other researches in which used human subjects are used, If Any',
                          'GROUP_NAME': 'G4',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': '<p>Specify multiple protocol numbers comma seperated</p>',
                          'SORT_ORDER': 2,
                          'QUESTION_ID': 1472,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Text',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1471
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 244,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': 'Y',
                          'QUESTION': 'Did you apply for IRB Approval ?',
                          'GROUP_NAME': 'G1',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 3,
                          'QUESTION_ID': 1473,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Y/N',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1471
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 245,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': null,
                          'QUESTION': 'Please specify a date in which you will apply for IRB Approval',
                          'GROUP_NAME': 'G3',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 4,
                          'QUESTION_ID': 1474,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Date',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1473
                        },
                        {
                          'LOOKUP_TYPE': null,
                          'LOOKUP_FIELD': null,
                          'ANSWER_LENGTH': null,
                          'RULE_ID': null,
                          'GROUP_LABEL': null,
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_NUMBER': 246,
                          'LOOKUP_NAME': null,
                          'HAS_CONDITION': null,
                          'QUESTION': 'Please specify the IRB Approval Number',
                          'GROUP_NAME': 'G2',
                          'HELP_LINK': null,
                          'QUESTION_VERSION_NUMBER': 3,
                          'DESCRIPTION': null,
                          'SORT_ORDER': 5,
                          'QUESTION_ID': 1475,
                          'ANSWERS': { '1': '' },
                          'ANSWER_TYPE': 'Text',
                          'NO_OF_ANSWERS': 1,
                          'UPDATE_TIMESTAMP': '2022-05-03T23:00:00.000+00:00',
                          'PARENT_QUESTION_ID': 1473
                        }
                      ],
                      'conditions': [
                        {
                          'QUESTION_CONDITION_ID': 1090,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G1',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1471,
                          'CONDITION_VALUE': 'Yes'
                        },
                        {
                          'QUESTION_CONDITION_ID': 1091,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G2',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1473,
                          'CONDITION_VALUE': 'Yes'
                        },
                        {
                          'QUESTION_CONDITION_ID': 1092,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G3',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1473,
                          'CONDITION_VALUE': 'No'
                        },
                        {
                          'QUESTION_CONDITION_ID': 1093,
                          'CONDITION_TYPE': 'EQUALS',
                          'GROUP_NAME': 'G4',
                          'UPDATE_USER': 'willsmith',
                          'QUESTION_ID': 1471,
                          'CONDITION_VALUE': 'No'
                        }
                      ],
                      'options': [
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1987,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1471,
                          'OPTION_LABEL': 'Yes',
                          'REQUIRE_EXPLANATION': 'N'
                        },
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1988,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1471,
                          'OPTION_LABEL': 'No',
                          'REQUIRE_EXPLANATION': 'N'
                        },
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1989,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1473,
                          'OPTION_LABEL': 'Yes',
                          'REQUIRE_EXPLANATION': 'N'
                        },
                        {
                          'EXPLANTION_LABEL': null,
                          'QUESTION_OPTION_ID': 1990,
                          'OPTION_NUMBER': null,
                          'QUESTION_ID': 1473,
                          'OPTION_LABEL': 'No',
                          'REQUIRE_EXPLANATION': 'N'
                        }
                      ],
                      'deleteList': null,
                      'questionnaireQuestions': null,
                      'questionnaireConditions': null,
                      'questionnaireOptions': null,
                      'questionnaireAnswers': null,
                      'quesAttachmentList': null,
                      'lookUpDetails': null
                    },
                    'usage': null,
                    'fileName': null,
                    'fileContent': null,
                    'length': null,
                    'remaining': null,
                    'fileTimestamp': null,
                    'contentType': null,
                    'personId': null,
                    'multipartFile': null,
                    'moduleList': null,
                    'isInserted': null,
                    'updateTimestamp': null,
                    'copyModuleItemKey': null,
                    'questionnaireNumbers': null,
                    'lookUpDetails': null,
                    'newQuestionnaireId': null,
                    'moduleSubItemCodes': [],
                    'questionnaireBusinessRules': null,
                    'ruleId': null,
                    'rulePassed': null,
                    'questionnaireMode': null,
                    'copyInActiveQuestionAnswers': false
                  },
                  'customElement': null,
                  'componentOrder': 1
                },
                {
                  'componentId': 4,
                  'sectionId': 112,
                  'componentDescription': null,
                  'componentType': 'RT',
                  'componentRefId': null,
                  'componentData': '<h1> Hello </h1>',
                  'componentHeader': 'Header Instruction',
                  'componentFooter': 'Footer Instruction',
                  'programmedElement': null,
                  'questionnaire': null,
                  'customElement': null,
                  'componentOrder': 2
                },
                {
                    'componentId': 4,
                    'sectionId': 112,
                    'componentDescription': null,
                    'componentType': 'RT',
                    'componentRefId': null,
                    'componentData': '<h1> Hello mahesh here how is this going </h1>',
                    'componentHeader': 'Header Instruction',
                    'componentFooter': 'Footer Instruction',
                    'programmedElement': null,
                    'questionnaire': null,
                    'customElement': null,
                    'componentOrder': 2
                },
                {
                    'componentId': 4,
                    'sectionId': 112,
                    'componentDescription': null,
                    'componentType': 'HL',
                    'componentRefId': null,
                    'componentData': 'background:#d0d0d0;height:5px',
                    'componentHeader': 'Header Instruction',
                    'componentFooter': 'Footer Instruction',
                    'programmedElement': null,
                    'questionnaire': null,
                    'customElement': null,
                    'componentOrder': 2
                }
              ]
            }
          ]
        }
      };

    constructor( private _http: HttpClient, private _commonService: CommonService) { }


    getFormBuilderData() {
        return this._http.post(this._commonService.baseUrl + '/formbuilder/getBlankForm', {
            'moduleItemCode': '23',
            'moduleSubItemCode': '0'
        });
    }

}
