//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 05:00:45 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.staffing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Encapsulating Element for all Organization Role Assignment data.
 * 
 * <p>Java class for Assign_Roles_Role_Assignment_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Roles_Role_Assignment_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Role_Assigner_Reference" type="{urn:com.workday/bsvc}Role_AssignerObjectType"/&gt;
 *         &lt;element name="Assignable_Role_Reference" type="{urn:com.workday/bsvc}Assignable_RoleObjectType"/&gt;
 *         &lt;element name="Remove_Existing_Assignees_for_Assignable_Role_on_Role_Assigner" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Update_Later_Dated_Assignments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Assignees_to_Add_Reference" type="{urn:com.workday/bsvc}Rolee_SelectorObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Assignees_to_Remove_Reference" type="{urn:com.workday/bsvc}Rolee_SelectorObjectType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Supervisory_Organization_Single_Assignment_Manager_Reference" type="{urn:com.workday/bsvc}Rolee_SelectorObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Remove_Supervisory_Organization_Single_Assignment_Manager" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Roles_Role_Assignment_DataType", propOrder = {
    "roleAssignerReference",
    "assignableRoleReference",
    "removeExistingAssigneesForAssignableRoleOnRoleAssigner",
    "updateLaterDatedAssignments",
    "assigneesToAddReference",
    "assigneesToRemoveReference",
    "supervisoryOrganizationSingleAssignmentManagerReference",
    "removeSupervisoryOrganizationSingleAssignmentManager"
})
public class AssignRolesRoleAssignmentDataType {

    @XmlElement(name = "Role_Assigner_Reference", required = true)
    protected RoleAssignerObjectType roleAssignerReference;
    @XmlElement(name = "Assignable_Role_Reference", required = true)
    protected AssignableRoleObjectType assignableRoleReference;
    @XmlElement(name = "Remove_Existing_Assignees_for_Assignable_Role_on_Role_Assigner")
    protected Boolean removeExistingAssigneesForAssignableRoleOnRoleAssigner;
    @XmlElement(name = "Update_Later_Dated_Assignments")
    protected Boolean updateLaterDatedAssignments;
    @XmlElement(name = "Assignees_to_Add_Reference")
    protected List<RoleeSelectorObjectType> assigneesToAddReference;
    @XmlElement(name = "Assignees_to_Remove_Reference")
    protected List<RoleeSelectorObjectType> assigneesToRemoveReference;
    @XmlElement(name = "Supervisory_Organization_Single_Assignment_Manager_Reference")
    protected RoleeSelectorObjectType supervisoryOrganizationSingleAssignmentManagerReference;
    @XmlElement(name = "Remove_Supervisory_Organization_Single_Assignment_Manager")
    protected Boolean removeSupervisoryOrganizationSingleAssignmentManager;

    /**
     * Gets the value of the roleAssignerReference property.
     * 
     * @return
     *     possible object is
     *     {@link RoleAssignerObjectType }
     *     
     */
    public RoleAssignerObjectType getRoleAssignerReference() {
        return roleAssignerReference;
    }

    /**
     * Sets the value of the roleAssignerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleAssignerObjectType }
     *     
     */
    public void setRoleAssignerReference(RoleAssignerObjectType value) {
        this.roleAssignerReference = value;
    }

    /**
     * Gets the value of the assignableRoleReference property.
     * 
     * @return
     *     possible object is
     *     {@link AssignableRoleObjectType }
     *     
     */
    public AssignableRoleObjectType getAssignableRoleReference() {
        return assignableRoleReference;
    }

    /**
     * Sets the value of the assignableRoleReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignableRoleObjectType }
     *     
     */
    public void setAssignableRoleReference(AssignableRoleObjectType value) {
        this.assignableRoleReference = value;
    }

    /**
     * Gets the value of the removeExistingAssigneesForAssignableRoleOnRoleAssigner property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoveExistingAssigneesForAssignableRoleOnRoleAssigner() {
        return removeExistingAssigneesForAssignableRoleOnRoleAssigner;
    }

    /**
     * Sets the value of the removeExistingAssigneesForAssignableRoleOnRoleAssigner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveExistingAssigneesForAssignableRoleOnRoleAssigner(Boolean value) {
        this.removeExistingAssigneesForAssignableRoleOnRoleAssigner = value;
    }

    /**
     * Gets the value of the updateLaterDatedAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdateLaterDatedAssignments() {
        return updateLaterDatedAssignments;
    }

    /**
     * Sets the value of the updateLaterDatedAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdateLaterDatedAssignments(Boolean value) {
        this.updateLaterDatedAssignments = value;
    }

    /**
     * Gets the value of the assigneesToAddReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assigneesToAddReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssigneesToAddReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleeSelectorObjectType }
     * 
     * 
     */
    public List<RoleeSelectorObjectType> getAssigneesToAddReference() {
        if (assigneesToAddReference == null) {
            assigneesToAddReference = new ArrayList<RoleeSelectorObjectType>();
        }
        return this.assigneesToAddReference;
    }

    /**
     * Gets the value of the assigneesToRemoveReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assigneesToRemoveReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssigneesToRemoveReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleeSelectorObjectType }
     * 
     * 
     */
    public List<RoleeSelectorObjectType> getAssigneesToRemoveReference() {
        if (assigneesToRemoveReference == null) {
            assigneesToRemoveReference = new ArrayList<RoleeSelectorObjectType>();
        }
        return this.assigneesToRemoveReference;
    }

    /**
     * Gets the value of the supervisoryOrganizationSingleAssignmentManagerReference property.
     * 
     * @return
     *     possible object is
     *     {@link RoleeSelectorObjectType }
     *     
     */
    public RoleeSelectorObjectType getSupervisoryOrganizationSingleAssignmentManagerReference() {
        return supervisoryOrganizationSingleAssignmentManagerReference;
    }

    /**
     * Sets the value of the supervisoryOrganizationSingleAssignmentManagerReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleeSelectorObjectType }
     *     
     */
    public void setSupervisoryOrganizationSingleAssignmentManagerReference(RoleeSelectorObjectType value) {
        this.supervisoryOrganizationSingleAssignmentManagerReference = value;
    }

    /**
     * Gets the value of the removeSupervisoryOrganizationSingleAssignmentManager property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoveSupervisoryOrganizationSingleAssignmentManager() {
        return removeSupervisoryOrganizationSingleAssignmentManager;
    }

    /**
     * Sets the value of the removeSupervisoryOrganizationSingleAssignmentManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveSupervisoryOrganizationSingleAssignmentManager(Boolean value) {
        this.removeSupervisoryOrganizationSingleAssignmentManager = value;
    }

}
