//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 05:00:45 PM IST 
//


package com.polus.fibicomp.manpowerintegration.dto.staffing;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Wrapper Element for the Assign Roles web service
 * 
 * <p>Java class for Assign_Roles_Event_DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Assign_Roles_Event_DataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Effective_Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="Effective_Timezone_Reference" type="{urn:com.workday/bsvc}Time_ZoneObjectType" minOccurs="0"/&gt;
 *         &lt;element name="Event_Target_Assignee_Reference" type="{urn:com.workday/bsvc}Rolee_SelectorObjectType"/&gt;
 *         &lt;element name="Remove_All_Role_Assignments_for_Event_Target_Assignee" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Assign_Roles_Role_Assignment_Data" type="{urn:com.workday/bsvc}Assign_Roles_Role_Assignment_DataType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assign_Roles_Event_DataType", propOrder = {
    "effectiveDate",
    "effectiveTimezoneReference",
    "eventTargetAssigneeReference",
    "removeAllRoleAssignmentsForEventTargetAssignee",
    "assignRolesRoleAssignmentData"
})
public class AssignRolesEventDataType {

    @XmlElement(name = "Effective_Date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "Effective_Timezone_Reference")
    protected TimeZoneObjectType effectiveTimezoneReference;
    @XmlElement(name = "Event_Target_Assignee_Reference", required = true)
    protected RoleeSelectorObjectType eventTargetAssigneeReference;
    @XmlElement(name = "Remove_All_Role_Assignments_for_Event_Target_Assignee")
    protected Boolean removeAllRoleAssignmentsForEventTargetAssignee;
    @XmlElement(name = "Assign_Roles_Role_Assignment_Data")
    protected List<AssignRolesRoleAssignmentDataType> assignRolesRoleAssignmentData;

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the effectiveTimezoneReference property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZoneObjectType }
     *     
     */
    public TimeZoneObjectType getEffectiveTimezoneReference() {
        return effectiveTimezoneReference;
    }

    /**
     * Sets the value of the effectiveTimezoneReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZoneObjectType }
     *     
     */
    public void setEffectiveTimezoneReference(TimeZoneObjectType value) {
        this.effectiveTimezoneReference = value;
    }

    /**
     * Gets the value of the eventTargetAssigneeReference property.
     * 
     * @return
     *     possible object is
     *     {@link RoleeSelectorObjectType }
     *     
     */
    public RoleeSelectorObjectType getEventTargetAssigneeReference() {
        return eventTargetAssigneeReference;
    }

    /**
     * Sets the value of the eventTargetAssigneeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleeSelectorObjectType }
     *     
     */
    public void setEventTargetAssigneeReference(RoleeSelectorObjectType value) {
        this.eventTargetAssigneeReference = value;
    }

    /**
     * Gets the value of the removeAllRoleAssignmentsForEventTargetAssignee property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRemoveAllRoleAssignmentsForEventTargetAssignee() {
        return removeAllRoleAssignmentsForEventTargetAssignee;
    }

    /**
     * Sets the value of the removeAllRoleAssignmentsForEventTargetAssignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRemoveAllRoleAssignmentsForEventTargetAssignee(Boolean value) {
        this.removeAllRoleAssignmentsForEventTargetAssignee = value;
    }

    /**
     * Gets the value of the assignRolesRoleAssignmentData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assignRolesRoleAssignmentData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssignRolesRoleAssignmentData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssignRolesRoleAssignmentDataType }
     * 
     * 
     */
    public List<AssignRolesRoleAssignmentDataType> getAssignRolesRoleAssignmentData() {
        if (assignRolesRoleAssignmentData == null) {
            assignRolesRoleAssignmentData = new ArrayList<AssignRolesRoleAssignmentDataType>();
        }
        return this.assignRolesRoleAssignmentData;
    }

}
