package com.polus.fibicomp.report.vo;

public interface ReportSQL {
	
	String ROUTING_ANALYSIS = "SELECT DATE_FORMAT(T1.WORKFLOW_START_DATE, \"%m/%d/%Y\") AS WORKFLOW_START_DATE,\r\n" + 
			"	    DATE_FORMAT(T1.WORKFLOW_END_DATE,\"%m/%d/%Y\") AS WORKFLOW_END_DATE,\r\n" + 
			"		T1.WORKFLOW_START_PERSON,\r\n" + 
			"		T1.WORKFLOW_END_PERSON,\r\n" + 
			"        T1.MODULE_ITEM_ID AS PROPOSAL_ID,\r\n" + 
			"		COUNT(T2.WORKFLOW_DETAIL_ID) AS APPROVER_COUNT,\r\n" + 
			"		datediff(T1.WORKFLOW_START_DATE,T1.WORKFLOW_END_DATE) AS DAY_SPENT_ON_APPROVAL,\r\n" + 
			"        T4.PERSON_ID AS PI_PERSON_ID,\r\n" + 
			"		T4.FULL_NAME AS PI_FULL_NAME, \r\n" + 
			"		T3.HOME_UNIT_NAME AS UNIT_NAME,\r\n" + 
			"		T3.HOME_UNIT_NUMBER AS UNIT_NUMBER,\r\n" + 
			"		T3.SPONSOR_CODE,\r\n" + 
			"		T3.SPONSOR_NAME\r\n" + 
			"FROM WORKFLOW T1 \r\n" + 
			"INNER JOIN  WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID\r\n" + 
			"INNER JOIN EPS_PROPOSAL T3 on T1.MODULE_ITEM_ID = T3.PROPOSAL_ID\r\n" + 
			"INNER JOIN  EPS_PROPOSAL_PERSONS T4 ON T4.PROPOSAL_ID = T3.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3\r\n" + 
			"WHERE T1.MODULE_CODE = 3\r\n" + 
			"AND T1.IS_WORKFLOW_ACTIVE = 'Y'\r\n" + 
			"GROUP BY T2.WORKFLOW_ID";
	
	String ACTIVE_AWARDS = "SELECT\r\n" + 
			"        T1.AWARD_NUMBER, \r\n" + 
			"        T1.SPONSOR_AWARD_NUMBER, \r\n" + 
			"        T2.SPONSOR_NAME,\r\n" + 
			"        T2.SPONSOR_CODE AS SPONSOR_CODE, \r\n" + 
			"       DATE_FORMAT(T1.AWARD_EFFECTIVE_DATE,\"%m/%d/%Y\")  AS AWARD_EFFECTIVE_DATE, \r\n" + 
			"        T3.FULL_NAME AS PI_FULL_NAME , \r\n" + 
			"        T3.PERSON_ID AS PI_PERSON_ID,\r\n" + 
			"        DATE_FORMAT(T1.FINAL_EXPIRATION_DATE,\"%m/%d/%Y\") AS FINAL_EXPIRATION_DATE,\r\n" + 
			"        T4.UNIT_NAME ,\r\n" + 
			"        T4.UNIT_NUMBER AS UNIT_NUMBER,\r\n" + 
			"        T5.TOTAL_DIRECT_COST,\r\n" + 
			"        T5.TOTAL_INDIRECT_COST,\r\n" + 
			"        T5.TOTAL_COST\r\n" + 
			"FROM AWARD T1 \r\n" + 
			"INNER JOIN  SPONSOR T2 ON T2.SPONSOR_CODE = T1.SPONSOR_CODE\r\n" + 
			"LEFT OUTER JOIN UNIT T4 ON T4.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER \r\n" + 
			"LEFT OUTER JOIN AWARD_PERSONS T3 ON T3.AWARD_ID = T1.AWARD_ID AND T3.CONTACT_ROLE_CODE = 'PI'\r\n" + 
			"LEFT OUTER JOIN AWARD_BUDGET_HEADER T5 ON T5.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID\r\n" + 
			"WHERE T1.AWARD_SEQUENCE_STATUS = 'ACTIVE'";
	
	String AWARD_BY_START_DATE = "SELECT\r\n" + 
			"	T1.AWARD_NUMBER,\r\n" + 
			"	T1.SPONSOR_AWARD_NUMBER,\r\n" + 
			"	T2.SPONSOR_NAME,\r\n" + 
			"	T2.SPONSOR_CODE AS SPONSOR_CODE, \r\n" + 
			"	DATE_FORMAT(T1.AWARD_EFFECTIVE_DATE,\"%m/%d/%Y\") AS AWARD_EFFECTIVE_DATE, \r\n" + 
			"	T3.FULL_NAME AS PI_FULL_NAME , \r\n" + 
			"	T3.PERSON_ID AS PI_PERSON_ID,\r\n" + 
			"	DATE_FORMAT(T1.FINAL_EXPIRATION_DATE,\"%m/%d/%Y\") AS FINAL_EXPIRATION_DATE,\r\n" + 
			"	T4.UNIT_NAME ,\r\n" + 
			"	T4.UNIT_NUMBER AS UNIT_NUMBER, \r\n" + 
			"	T5.TOTAL_DIRECT_COST,\r\n" + 
			"	T5.TOTAL_INDIRECT_COST,\r\n" + 
			"	T5.TOTAL_COST,\r\n" + 
			"	T6.DESCRIPTION AS AWARD_TYPE, \r\n" + 
			"	T7.DESCRIPTION AS ACTIVITY_TYPE,\r\n" + 
			"	T8.DESCRIPTION AS AWARD_STATUS \r\n" + 
			"FROM AWARD T1 \r\n" + 
			"INNER JOIN  SPONSOR T2 ON T2.SPONSOR_CODE = T1.SPONSOR_CODE\r\n" + 
			"LEFT OUTER JOIN UNIT T4 ON T4.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER \r\n" + 
			"LEFT OUTER JOIN AWARD_PERSONS T3 ON T3.AWARD_ID = T1.AWARD_ID AND T3.CONTACT_ROLE_CODE = 'PI'\r\n" + 
			"LEFT OUTER JOIN AWARD_BUDGET_HEADER T5 ON T5.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID \r\n" + 
			"LEFT OUTER JOIN AWARD_TYPE T6 ON T1.AWARD_TYPE_CODE = T6.AWARD_TYPE_CODE\r\n" + 
			"LEFT OUTER JOIN ACTIVITY_TYPE T7 ON T7.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE\r\n" + 
			"LEFT OUTER JOIN AWARD_STATUS T8 ON T8.STATUS_CODE = T1.STATUS_CODE\r\n" + 
			"WHERE T1.AWARD_SEQUENCE_STATUS = 'ACTIVE'\r\n" + 
			"ORDER BY T1.BEGIN_DATE DESC";
	
	String PENDING_PROPOSAL = "SELECT \r\n" + 
			"	T1.PROPOSAL_NUMBER, \r\n" + 
			"	T1.SPONSOR_NAME ,\r\n" + 
			"	T1.SPONSOR_CODE AS SPONSOR_CODE, \r\n" + 
			"	DATE_FORMAT(T1.START_DATE,\"%m/%d/%Y\") AS START_DATE,\r\n" + 
			"	T1.HOME_UNIT_NUMBER AS UNIT_NUMBER, \r\n" + 
			"	T1.TITLE, \r\n" + 
			"	T2.DESCRIPTION AS ACTIVITY_TYPE,\r\n" + 
			"	T3.DESCRIPTION AS PROPOSAL_TYPE, \r\n" + 
			"	T1.TOTAL_DIRECT_COST, \r\n" + 
			"	T1.TOTAL_INDIRECT_COST, \r\n" + 
			"	T1.TOTAL_COST, \r\n" + 
			"	T4.PERSON_ID AS PI_PERSON_ID,\r\n" + 
			"	T4.FULL_NAME AS PI_FULL_NAME\r\n" + 
			"FROM PROPOSAL T1\r\n" + 
			"INNER JOIN ACTIVITY_TYPE T2 ON T2.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE\r\n" + 
			"INNER JOIN PROPOSAL_TYPE T3 ON T3.TYPE_CODE = T1.TYPE_CODE\r\n" + 
			"INNER JOIN PROPOSAL_PERSONS T4 ON T4.PROPOSAL_ID = T1.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3\r\n" + 
			"WHERE T1.STATUS_CODE <> 2";
	
	String FUNDING_STATUS = "SELECT \r\n" + 
			"	T1.PROPOSAL_NUMBER, \r\n" + 
			"	T1.SPONSOR_NAME ,\r\n" + 
			"	T1.SPONSOR_CODE AS SPONSOR_CODE, \r\n" + 
			"	DATE_FORMAT(T1.START_DATE,\"%m/%d/%Y\") AS START_DATE,\r\n" + 
			"	T1.HOME_UNIT_NUMBER AS UNIT_NUMBER, \r\n" + 
			"	T1.TITLE, \r\n" + 
			"	T2.DESCRIPTION AS ACTIVITY_TYPE,\r\n" + 
			"	T3.DESCRIPTION AS PROPOSAL_TYPE, \r\n" + 
			"	T1.TOTAL_DIRECT_COST, \r\n" + 
			"	T1.TOTAL_INDIRECT_COST, \r\n" + 
			"	T1.TOTAL_COST, \r\n" + 
			"	T4.PERSON_ID AS PI_PERSON_ID,\r\n" + 
			"	T4.FULL_NAME AS PI_FULL_NAME,\r\n" + 
			"	T7.OBLIGATED_TOTAL_DIRECT,\r\n" + 
			"	T7.OBLIGATED_TOTAL_INDIRECT,\r\n" + 
			"	T7.AMOUNT_OBLIGATED_TO_DATE \r\n" + 
			"FROM PROPOSAL T1\r\n" + 
			"INNER JOIN ACTIVITY_TYPE T2 ON T2.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE\r\n" + 
			"INNER JOIN PROPOSAL_TYPE T3 ON T3.TYPE_CODE = T1.TYPE_CODE\r\n" + 
			"INNER JOIN PROPOSAL_PERSONS T4 ON T4.PROPOSAL_ID = T1.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3\r\n" + 
			"LEFT JOIN AWARD_FUNDING_PROPOSALS T5 ON T5.PROPOSAL_ID = T1.PROPOSAL_ID\r\n" + 
			"LEFT JOIN AWARD T6 ON T5.AWARD_ID = T6.AWARD_ID \r\n" + 
			"LEFT JOIN \r\n" + 
			"		(\r\n" + 
			"			select S1.AWARD_ID, S1.OBLIGATED_TOTAL_DIRECT, S1.OBLIGATED_TOTAL_INDIRECT,S1.AMOUNT_OBLIGATED_TO_DATE \r\n" + 
			"			FROM AWARD_AMOUNT_INFO S1\r\n" + 
			"			where S1.AWARD_AMOUNT_INFO_ID = (select max(S2.AWARD_AMOUNT_INFO_ID) from AWARD_AMOUNT_INFO S2 where S1.AWARD_ID = S2.AWARD_ID)\r\n" + 
			"		) T7 ON T7.AWARD_ID = T6.AWARD_ID  \r\n" + 
			"WHERE T1.STATUS_CODE <> 2";
	
	String PROPOSAL_BY_GRANT_CALL = "SELECT T1.GRANT_HEADER_ID AS GRANT_HEADER_ID, T1.NAME,T1.HOME_UNIT_NAME, T1.HOME_UNIT_NUMBER AS HOME_UNIT_NUMBER,T3.TOTAL_DIRECT_COST, \r\n" + 
			"T3.TOTAL_INDIRECT_COST, T3.TOTAL_COST, T2.PROPOSAL_NUMBER,T4.FULL_NAME AS PI_NAME, T4.PERSON_ID AS PI_PERSON_ID, T1.SPONSOR_CODE AS SPONSOR_CODE,T2.START_DATE AS START_DATE\r\n" + 
			"FROM GRANT_CALL_HEADER T1\r\n" + 
			"LEFT JOIN PROPOSAL T2 ON T2.GRANT_HEADER_ID = T1.GRANT_HEADER_ID\r\n" + 
			"LEFT JOIN PROPOSAL_PERSONS T4 ON T4.PROPOSAL_ID = T2.PROPOSAL_ID\r\n" + 
			"LEFT JOIN BUDGET_HEADER T3 ON T3.BUDGET_HEADER_ID = T2.BUDGET_HEADER_ID";
	
	String SUCCESS_RATE ="SELECT  T1.ALL_PROPOSAL as ALL_PROPOSAL,\r\n" + 
			"                T1.FULL_NAME,T1.UNIT_NAME ,\r\n" + 
			"        ifnull(T2.FUNDED_PROPOSAL,0) AS FUNDED_PROPOSAL,\r\n" + 
			"        (ifnull(T2.FUNDED_PROPOSAL,0)/T1.ALL_PROPOSAL)*100 as SUCCESS_RATE,\r\n" + 
			"        T1.PERSON_ID as  PERSON_ID,\r\n" + 
			"        T1.HOME_UNIT_NUMBER as HOME_UNIT_NUMBER   \r\n" + 
			"                \r\n" + 
			"FROM\r\n" + 
			"(\r\n" + 
			"  \r\n" + 
			"        SELECT  COUNT(T1.PROPOSAL_NUMBER)  AS ALL_PROPOSAL,T2.FULL_NAME,T3.UNIT_NAME,T1.HOME_UNIT_NUMBER,T2.PERSON_ID\r\n" + 
			"        FROM PROPOSAL T1 \r\n" + 
			"        INNER JOIN PROPOSAL_PERSONS T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.PROP_PERSON_ROLE_ID = 3\r\n" + 
			"        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT_NUMBER\r\n" + 
			"        WHERE T1.SEQUENCE_NUMBER IN (SELECT MAX(S1.SEQUENCE_NUMBER) FROM PROPOSAL S1 WHERE S1.PROPOSAL_NUMBER = T1.PROPOSAL_NUMBER)\r\n" + 
			"        GROUP BY T1.HOME_UNIT_NUMBER,T2.FULL_NAME\r\n" + 
			") T1\r\n" + 
			"LEFT OUTER JOIN (\r\n" + 
			"\r\n" + 
			"        SELECT  COUNT(T1.PROPOSAL_NUMBER)  AS FUNDED_PROPOSAL,T2.FULL_NAME,T3.UNIT_NAME,T1.HOME_UNIT_NUMBER,T2.PERSON_ID \r\n" + 
			"        FROM PROPOSAL T1 \r\n" + 
			"        INNER JOIN PROPOSAL_PERSONS T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.PROP_PERSON_ROLE_ID = 3\r\n" + 
			"        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT_NUMBER\r\n" + 
			"        WHERE T1.SEQUENCE_NUMBER IN (SELECT MAX(S1.SEQUENCE_NUMBER) FROM PROPOSAL S1 WHERE S1.PROPOSAL_NUMBER = T1.PROPOSAL_NUMBER)\r\n" + 
			"        AND T1.STATUS_CODE = 2\r\n" + 
			"        GROUP BY T1.HOME_UNIT_NUMBER,T2.FULL_NAME\r\n" + 
			" )  T2 ON T1.PERSON_ID = T2.PERSON_ID AND T1.HOME_UNIT_NUMBER = T2.HOME_UNIT_NUMBER  ";
	
}
