SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `fb_comp_custom_element` (
  `CUSTOM_DATA_ELEMENTS_ID` int NOT NULL AUTO_INCREMENT,
  `COLUMN_LABEL` varchar(255) DEFAULT NULL,
  `DATA_LENGTH` int DEFAULT NULL,
  `DATA_TYPE` varchar(255) DEFAULT NULL,
  `DEFAULT_VALUE` varchar(255) DEFAULT NULL,
  `HAS_LOOKUP` varchar(255) DEFAULT 'N',
  `LOOKUP_ARGUMENT` varchar(255) DEFAULT NULL,
  `LOOKUP_WINDOW` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'N',
  `CUSTOM_ELEMENT_NAME` varchar(70) DEFAULT NULL,
  `IS_MULTI_SELECT_LOOKUP` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`CUSTOM_DATA_ELEMENTS_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_FK1` (`DATA_TYPE`),
  CONSTRAINT `FB_COMP_CUSTOM_ELEMENT_FK1` FOREIGN KEY (`DATA_TYPE`) REFERENCES `form_section_component_type` (`COMPONENT_TYPE_CODE`)
);

CREATE TABLE `fb_comp_custom_element_answer` (
  `CUSTOM_DATA_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOM_DATA_ELEMENTS_ID` int DEFAULT NULL,
  `MODULE_ITEM_CODE` int DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(255) DEFAULT NULL,
  `MODULE_SUB_ITEM_CODE` int DEFAULT NULL,
  `MODULE_SUB_ITEM_KEY` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `VALUE` varchar(4000) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOM_DATA_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx2` (`MODULE_ITEM_KEY`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx3` (`CUSTOM_DATA_ELEMENTS_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx4` (`MODULE_ITEM_KEY`,`CUSTOM_DATA_ELEMENTS_ID`)
);

CREATE TABLE `fb_comp_custom_element_options` (
  `CUSTOM_DATA_OPTION_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOM_DATA_ELEMENTS_ID` int DEFAULT NULL,
  `OPTION_NAME` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOM_DATA_OPTION_ID`)
);

CREATE TABLE `form_builder_counter` (
  `COUNTER_NAME` varchar(255) NOT NULL,
  `COUNTER_VALUE` int DEFAULT NULL,
  PRIMARY KEY (`COUNTER_NAME`)
);

SET FOREIGN_KEY_CHECKS=1;
