
DROP PROCEDURE IF EXISTS GENERATE_FORM_BUILDER_NUMBER;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD_COUNT;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_COI_DISCLOSURE_HISTORY;
DROP PROCEDURE IF EXISTS GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD;
DROP PROCEDURE IF EXISTS GET_ALL_RIGHTS_FOR_A_MODULE;
DROP FUNCTION IF EXISTS FN_COI_PERSON_HAS_AUTHORIZATION;

\. ./Procedures/GENERATE_FORM_BUILDER_NUMBER.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD_COUNT.sql
\. ./Procedures/GET_COI_DISCLOSURE_DASHBOARD.sql
\. ./Procedures/GET_COI_DISCLOSURE_HISTORY.sql
\. ./Procedures/GET_CONSULTING_DISCLOSURE_ADMIN_DASHBOARD.sql
\. ./Procedures/GET_ALL_RIGHTS_FOR_A_MODULE.sql
\. ./Functions/FN_COI_PERSON_HAS_AUTHORIZATION.sql
